### ISSUE TITLE
Segfault on "for local i:byte = EachIn string" 

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#102]
When trying to iterate over a string (like an array) the result is a segfault.

Vanilla blames usage of strings in EachIn-constellations: `Compile Error: EachIn index variable must be an object`

**Comment by woollybah** [comment]
This works for me...
```blitzmax
SuperStrict

Framework brl.standardio

Local a:String = "abcdefg"

For Local i:Byte = EachIn a
	Print i
Next
```
Yes, this usage or Eachin (on strings) is not supported by legacy BlitzMax.

Byte, or course, is not Unicode friendly.

How are you using this in your program?

**Comment by GWRon** [comment]
I do not use that...but found the error when writing a sample.

In my code it segfaulted when trying 

Eachin "text" 

So NOT a variable

**Comment by GWRon** [comment]
Used it when trying to write to a stream using writebyte

**Comment by woollybah** [comment]
Do you have a (non) working version of this that I can test ?

**Comment by GWRon** [comment]
```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.Retro

For Local i:Byte = EachIn "Hi"
	Print i
Next
```

I do not expect it to be a runnable example...
Vanilla errors on compilation, NG compiles and segfaults on run. Thats what I wanted to have "corrected"

The important difference is that I do not use a variable but the "string" itself right in the for-loop.

**Comment by woollybah** [comment]
It works for me.

**Comment by GWRon** [comment]
```
$ ./bcc -v
bcc[ng] Release Version 0.55
```

```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.Retro

For Local i:Byte = EachIn "Hi"
    Print i
Next
```
```
Building untitled1
/home/ronny/Arbeit/Programmieren/Projekte/Apps/BlitzMax_Compiler/bmk-ng
Compiling:untitled1.bmx
Segmentation fault (core dumped)
Build Error: failed to compile /home/ronny/Arbeit/Programmieren/BlitzMaxNG/tmp/untitled1.bmx
Process complete
```

**Comment by woollybah** [comment]
Okay, so where you say "NG compiles and segfaults on run", it doesn't actually compile it and never gets to the point of running it ?

**Comment by GWRon** [comment]
I thought so because some temp files were created, but as I wanted to send you the content of the c-files I saw that there is way to much going on ... so I saw it segfaulted during compilation.

Added that some seconds before you wrote your reply

**Comment by woollybah** [comment]
This works for me on both Linux and OS X...
Shall I mark it as invalid?

**Comment by GWRon** [comment]
It still segfaults

```console
ronny@RonnyPC ~/BlitzMaxNG/bin $ ./bmk -v
bmk 2.25 linux-x86 / gcc 040802 (cpu x4)

ronny@RonnyPC ~/BlitzMaxNG/bin $ ./bcc -v
bcc[ng] Release Version 0.56
ronny@RonnyPC ~/BlitzMaxNG/bin $ tail eachin.bmx
SuperStrict
Framework Brl.StandardIO
Import Brl.Retro

For Local i:Byte = EachIn "Hi"
    Print i
Next
ronny@RonnyPC ~/BlitzMaxNG/bin $ ./bmk makeapp -t console -gdb -a "eachin.bmx"
Compiling:eachin.bmx
Segmentation fault (core dumped)
Build Error: failed to compile /home/ronny/BlitzMaxNG/bin/eachin.bmx
```

I recompiled bcc and modules before trying it.

**Comment by woollybah** [comment]
Okay, but I cannot reproduce it, and have no idea where your problem is from the information you've provided.

**Comment by GWRon** [comment]
I am trying to collect information ...

```
Executing bcc.debug
....
DebugLog:Found Class :  TListEnum
DebugLog:
DebugLog:Found Class :  TList
DebugLog:
...null access
```

highlighted line "try" in bcc.bmx:
```BlitzMax
If opt_buildtype = BUILDTYPE_MODULE Then
	If opt_filepath.ToLower() = ModuleSource(opt_modulename).ToLower() Then
		opt_ismain = True
	End If
End If

Local app:TAppDecl 
Local trans:TCTranslator 
Try
	app = ParseApp(opt_filepath)

	app.Semant()

	trans = New TCTranslator

	trans.TransApp(app)
Catch error:String
	WriteStderr error
	End
```

**Comment by woollybah** [comment]
Comment out the Try/Catch part and see where it originally throws.

**Comment by GWRon** [comment]
- "App.Semant"
- - Type TForEachinStmt Extends TLoopStmt
- - - Method OnSemant()
- - - - If TObjectType(TArrayType( expr.exprType ).elemType) Then
Last one seems ot have a null thing

Debugwindow means the errorneous line is the one with the __Eachin "Hi"__

**Comment by GWRon** [comment]
I prepended a simple check before this line:

```BlitzMax
				' array of object ?
				
				If TObjectType(TArrayType( expr.exprType ).elemType) Then
```
got
```BlitzMax
				' array of object ?
				If Not TArrayType( expr.exprType ) Then Print "expr is not of type array"
				
				If TObjectType(TArrayType( expr.exprType ).elemType) Then
```

and right before crashing it printed "expr is not of type array"

**Comment by GWRon** [comment]
Closed... latest revision fixed the issue
