### ISSUE TITLE
Shorthand multiplication ":*" - rhs uses lhs number type (wrong for rhs floats)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#103]
When using the "shorthand" multiplicator ":*" the rhs number type is incorrectly casted to the lhs one. So when multiplying an integer with a float this way, the float is casted to an int before - which leads to wrong results (of course).

```BlitzMax
SuperStrict
Framework Brl.StandardIO


Local value:Int

value = 50
value = value * 0.6
Print value

value = 50
value :* 0.6
Print value 'is 0 - seems "0.6" is interpreted as "int" -> "0" here...

value = 50
value :* 1.6
Print value 'is 50 - seems "1.6" is interpreted as "int" -> "1" here...

Local fvalue:Float = 50
fvalue :* 1.6
Print fvalue 'is 80 - seems "1.6" is interpreted correctly now
```

**Comment by GWRon** [comment]
Problematic line is this:
stmt.bmx:

```
Type TAssignStmt Extends TStmt
...
	Method OnSemant()
...
				rhs=rhs.Cast( lhs.exprType )
```

I assume this should only be done for specific things.

**Comment by woollybah** [comment]
It looks like Monkey's handling of this changed since my original copy of it. I'll have a look at reimplementing it.
