### ISSUE TITLE
Modulo operator for "floats" has an "arithmetic exception"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#105]
```BlitzMax
Framework Brl.StandardIO
Print (0.8 Mod 0.3) 'should be "0.2"
```

When using modulo on floating point numbers the NG compiler compiles the file but when executing it segfaults with: `Program received signal SIGFPE, Arithmetic exception.`

**Comment by woollybah** [comment]
I should probably be using fmod() here...
