### ISSUE TITLE
Fail to assign "param var" to "param2 var"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#111]
```BlitzMax
SuperStrict
Framework Brl.StandardIO


Type A
	Field i:Int = 1
	Field j:Int = 5
End Type


Type TCollection
	Field _a:A

	Method _Assign(objSource:Object Var, objTarget:Object Var)
		If objSource
			Print "assigning objTarget to objSource"
			objTarget = objSource
		EndIf
	End Method	
End Type

Global collection:TCollection = New TCollection
Global obj:A = New A

'try to replace "_a" with the obj
collection._Assign(obj, collection._a)

If collection._a 
	Print "assignment: OK"
Else
	Print "assignment: Failed"
EndIf
```

Vanilla output:
```
assigning objTarget to objSource
assignment: OK
```

NG output:
```
assigning objTarget to objSource
assignment: Failed
```

What am I doing with this? I have an type "TSaveGame" with "fields" of every important collection/type I use in my game. When it comes to saving a game, all references (memory adresses?) to instances of the collections / lists ... are stored in this TSaveGame-instance and then serialized using Bruceys bah.mod/TPersistence.mod. When it comes to loading, it is done in reverse: TSaveGame-field-pointers are set to the individual collections/lists/... 
As it works with "vanilla" I assume to have done it right.

Edit: this is the c-code of the generated "_assign"-method:
```C
void __ng_var_TCollection__Assign(struct _ng_var_TCollection_obj* o,BBOBJECT* bbt_objSource,BBOBJECT* bbt_objTarget){
	if(*bbt_objSource!= &bbNullObject){
		brl_standardio_Print(&_s0);
		*bbt_objTarget=*bbt_objSource;
	}
}
```

**Comment by GWRon** [comment]
```
Compiling:persistenceTest.bmx
/BlitzMaxNG/tests/persistenceTest.bmx: In function ‘_bb_main’:
/BlitzMaxNG/tests/persistenceTest.bmx:24:80: error: lvalue required as unary ‘&’ operand
 collection._Assign(New A, collection._a)
                                                                                ^
Build Error: failed to compile /BlitzMaxNG/tests/.bmx/persistenceTest.bmx.console.debug.linux.x86.c
```

**Comment by woollybah** [comment]
Thanks. It took me a while to work out that your posted code is not the same as your tested code...

**Comment by GWRon** [comment]
Ahh yes.. .my version was __collection._Assign(New A, collection._a)__ instead of using a variable. Sorry for added confusion.


bye
Ron

**Comment by GWRon** [comment]
What about Function results?

Copy(GetInstance(), instanceVariable)
