### ISSUE TITLE
Question: How to handle "?win32 and bmxng"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#120]
While "BCC NG" properly handles "?win32 and bmxng", vanilla is not capable of doing such things.

Up to now no problem but what if you cannot do things with "bmx ng" yet?

In my case I have to do SetGraphicsDriver(). While vanilla supports DX, this is not the case for BMX-NG yet. So I thought of doing "?win32 and bmxng" and "?win32 and not bmxng" - hey and it worked for NG. But when trying to compile with vanilla, it fails because it does not recognize what we want from it.

As you cannot chain conditionals
```
?win32
  ?bmxng
    print "running on win32 with ng"
  ?not bmxng
    print "running on win32 with vanilla"
  ?
?
```
this enforces you to do everything in extra files:

```
?win32
  import "special.win32.bmx"
?
```
and within that special file you could do your `?bmxng` conditional.
special.win32.bmx:
```
?bmxng
  print "running on win32 with ng"
?not bmxng
  print "running on win32 with vanilla"
?
```

Ideas how to circumvent the problem (except waiting for DX to work on NG :-) ).

**Comment by woollybah** [comment]
You probably need to split the files up. I've done that in a couple of places with the mods.

**Comment by GWRon** [comment]
This is what I have done ... but it is not "pretty" :D
