### ISSUE TITLE
Assertions aren't evaluated in debug build

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#121]
_From @FWeinb on July 2, 2015 8:38_

I just tried the latest version and noticed that assertions aren't evaluated in any way. 

Here is a reduced test case:
```bmx
SuperStrict
Framework BRL.System

Function test(value:Int)
  Assert value > 0, "This is not possible"
  DebugLog "Function run"
End Function

Try
   test(-1)
   DebugLog "This is wrong!"
Catch e:Object
   DebugLog e.toString()
End Try
```
With the original bcc/bmk in debug build this evaluated to:
```
DebugLog:This is not possible

Process complete
``` 

In bmx-ng the assertion is ignored in a debug build and this is evaluated to:
```
DebugLog:Function run
DebugLog:This is wrong!
```

_Copied from original issue: bmx-ng/bmx-ng#4_

**Comment by FWeinb** [comment]
Thanks for moving, wasn't sure where to put it,

**Comment by woollybah** [comment]
Assertions are one of the remaining core features yet to be implemented...

**Comment by FWeinb** [comment]
Okay, good to know. I am experimenting with building a dependency injection module ([injection.mod](https://github.com/FWeinb/injection.mod)) based on reflection and to avoid a runtime penalty I try to check most things in the debug build with assertions.

**Comment by FWeinb** [comment]
Awesome! Great I will try it right now.

**Comment by FWeinb** [comment]
Thanks for fix it. Everything is working fine for me.
