### ISSUE TITLE
Unicode characters encoded (bmx->c conversion)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#126]
Example code:
```blitzmax
SuperStrict
Framework Brl.StandardIO

Const CURRENCYSIGN:String = Chr(8364) 'eurosign

Print "Eurosign. " + CURRENCYSIGN
```
(if your console allows unicode) will print "Eurosign. €".

When doing this with the win-build of maxide and vanilla bmx you will only get `Eurosign. ࢂ` (win console just cannot display it) ... when compiling with NG you get `Eurosign. â¬` instead ...

When running my game with graphics context and trying to render the glyph of "8364" I get a \1396 or so printed instead.

I used the "Chr()" approach as it does not enforce the source file to be UTF8. Nonetheless: using `Print "Eurosign. €"`does result in the same corrupted output.

**Comment by woollybah** [comment]
The generated C-code stores the same values for the characters as legacy bcc.
If I change the Print to Notify, the notify window on OS X displays the euro sign correctly.

**Comment by GWRon** [comment]
Nonetheless is the output in the process-output-window of maxide different on Windows. So maybe it is not the char encoding but some kind of string handling difference in the module-conversion.

will try to create a "drawtext"-example tomorrow

**Comment by woollybah** [comment]
This example appears to work for me on OS X (legacy and ng) :
```blitzmax
SuperStrict
Framework Brl.StandardIO
Import brl.glmax2d
Import brl.freetypefont

Const CURRENCYSIGN:String = Chr(8364) 'eurosign

Graphics 800, 600, 0

SetBlend alphablend

Local font:TImageFont = LoadImageFont("/Library/Fonts/Arial Unicode.ttf", 20)

SetImageFont font

While Not KeyDown(key_escape)

	Cls

	DrawText "Eurosign. " + CURRENCYSIGN, 200, 200

	Flip

Wend
```
... change path to supported font as required.

**Comment by GWRon** [comment]
Yes, this works for me too (tested on windows).

Will have to extract the functionality from my bitmapfont-class (Dig-Framework) as it happened there with NG.

**Comment by GWRon** [comment]
Ok, issue is now happening, when using "Chr(8364)" directly in the corresponding file, so I assume it has something to do strings "imported" from other files (I declare the string)...

So I extended your code:

utf8ng.bmx
```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import brl.glmax2d
Import brl.freetypefont

Import "utf8ng_import.bmx"
Include "utf8ng_include.bmx"
Graphics 800, 600, 0

SetBlend alphablend

Local font:TImageFont = LoadImageFont("SourceSansPro-Regular.ttf", 20)

SetImageFont font

While Not KeyDown(key_escape)

    Cls

    DrawText "Eurosign. " + CURRENCYSIGN, 200, 200
    DrawText "Eurosign. " + CURRENCYSIGNIMPORT, 200, 240

    Flip

Wend
```

utf8ng_import.bmx
```BlitzMax
SuperStrict

Const CURRENCYSIGNIMPORT:String = Chr(8364) 'eurosign
```

utf8ng_include.bmx
```BlitzMax
Const CURRENCYSIGN:String = Chr(8364) 'eurosign
```

Result:
![utf8](https://cloud.githubusercontent.com/assets/2625226/9157043/40e1da3a-3eee-11e5-9168-d87e58561321.png)
