### ISSUE TITLE
For loop: not able to use "complex"-variables as Index variable

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#130]
Fails on NG, compiles and runs fine on vanilla:

What works: you can use declared variables or declare "local" ones for the for-loop.
What doesn't: you cannot use "indirect" variables: globals of a type, fields of a type instance, children of an array.

```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.LinkedList
Import Brl.Random

Type TA
	Field num:Int
	
	Method Init:TA()
		num = Rand(0,100)
		Return Self
	End Method
End Type


Type TC
	Field a:TA
End Type


Global l:TList = CreateList()
Global c:TC = New TC
l.AddLast(New TA.Init())
l.AddLast(New TA.Init())


For c.a = EachIn l
	Print c.a.num
Next


'Fails for globals too
Global arr:TA[1]
For arr[0] = EachIn l
	Print arr[0].num
Next
```

```
Compile Error: Syntax error - expecting '='.
```

Original bug report: http://www.blitzmax.com/Community/post.php?topic=105048&post=1277099

**Comment by woollybah** [comment]
Hopefully these changes don't break anything else...
