### ISSUE TITLE
Float Ptr definition error in release mode only

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#137]
Strict

Local fl:Float
Local fptr:Float Ptr = Varptr fl

builds ok in debug but fails in release mode with

Building untitled3
[ 99%] Processing:untitled3.bmx
[ 99%] Compiling:untitled3.bmx.console.release.win32.x64.c
C:/BlitzMax/tmp/.bmx/untitled3.bmx.console.release.win32.x64.c: In function '_bb_main':
C:/BlitzMax/tmp/.bmx/untitled3.bmx.console.release.win32.x64.c:40:20: error: incompatible types when initializing type 'BBFLOAT {aka float}' using type 'BBFLOAT * {aka float *}'
   BBFLOAT bbt_fptr=(&bbt_fl);
                    ^
Build Error: failed to compile (1) C:/BlitzMax/tmp/.bmx/untitled3.bmx.console.release.win32.x64.c
Process complete

**Comment by woollybah** [comment]
This works with the latest bcc.

**Comment by davecamp** [comment]
Indeed it does. I was using the v0.66.3.07 package from the 'release' folder. After pulling the latest all is good.

**Comment by woollybah** [comment]
Yes, I need to push a new release...
