### ISSUE TITLE
Framework issue - duplicate identifier from an 'outside' module

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#138]
I have a module with a Cls Function defined inside it. I use 'Framework my.module' to get rid of the other modules and when building I get a duplicate identifier error found in brl.max2d and in my module for the Cls function.

**Comment by davecamp** [comment]
This is resolved in the latest version. Thanks!

**Comment by woollybah** [comment]
It is? Cool. I was just about to ask you a bunch of questions ;-)
