### ISSUE TITLE
Method return values not requiring parentheses?

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#140]
Is this a feature or 'feature bug' ?

    SuperStrict
    Type test
    	Method me:Int()
    		Return 10
    	EndMethod
    EndType

    Local t:test = New test
    Print t.me					' no parentheses required?

**Comment by GWRon** [comment]
Isn't this possible with vanilla too?

Although SetColor and SetAlpha are the only functions I use without brackets.

**Comment by davecamp** [comment]
Nah, in vanilla you don't have to use parenthesis when around arguments going into a method/function. In this example vanilla bmx complains of 'cannot convert Int() to String'. Also using
    Print String(t.me)
gives the same error.

**Comment by GWRon** [comment]
Your sample is saying the same (no parentheses needed).

Seems I do not correctly get/understand your issue (English/language wise).

**Comment by davecamp** [comment]
No worries. A better example In vanilla: the syntax is...

    SuperStrict
    Type math_int
    	Field _value:Int
    	Method Add:Int(x:Int, y:Int)
    		_value = x+y
    		Return _value
    	EndMethod
    EndType

    Local m:math_int = New math_int
    m.add 10,20 ' no parentheses are needed as we don't want the return result
    Print m.add(10,20) ' parentheses are needed so the result can be used in another expression/statement

**Comment by GWRon** [comment]
Maybe it depends on how the function chain is evaluated... from the right to left.. or ..left to right.

so vanilla allows this (I blamed something similar some months ago...when we wrote about if's without then's

If x x
-> if x() then x() 'run twice

**Comment by davecamp** [comment]
I think that bcc should have a clear distinction between a function call used as a statement and used as an expression argument and have it used accordingly when semanted as such through out the whole compilation.
Do you have a link for the 'If' issue that you're referring to so that I can take a look?

**Comment by davecamp** [comment]
Oh wait... Further testing ( I didn't test my 3rd post in NG as I used it to illustrate the parenthesis understanding ),
NG only seems to run the call without parentheses when there are no parameters. The example I gave does indeed complain about using a statement as an expression.
The original issue that I raised now looks isolated to a function call without parameters.

**Comment by GWRon** [comment]
I was not able to find the real thread in which we wrote about the ifs, but the basic thing was

```BlitzMax
SuperStrict
Framework Brl.Standardio


'a function with a default param
Function Test:int(param:int = 10)
  print "Test - param="+param
  return param * 2
End Function

'works
Test 5

'works
if Test then Test 6

'works
if Test Test

'works (outputs 7 - wich is correct)
if Test Test 7

'fails
'if Test Test Test 7

'fails
'if Test(Test) then Test 5


'fails
'if Test Test then Test 5

'fails to compile
'if not Test Test test 5


'fails to compile
'if test test else test test 2

'fails to compile
'if test test else test test
```

All of these should be valid regarding the language syntax - but the failing onesof them are "ambiguous". The last one is - imho - the same thing as the working ones, it could clearly be split into various function calls ...

**Comment by davecamp** [comment]
Why is it that 'If Test' works? What type of expression is being checked? Is it checking the boolean value ( after converting the integer return value to a boolean ) or something else?

**Comment by GWRon** [comment]
Each number > 0 should be evaluated as "true". Same for "not null" objects or "not empty" strings.

**Comment by davecamp** [comment]
Yes I totally understand that.
I was just curious as to what is 'Test' being semanted as in this context?
'If Test' is a statement ( 'If' ) and an expression ( 'Test' ).
'Test' is a function which is invoked as a statement as there are no parentheses, no?, which means its not an expression in that context?
If you do use the parenthesis you are then disambiguating that you want to use the 'return type and value' as the expression part of the 'If' statement.
That's always been my understanding until today :D
