### ISSUE TITLE
Global with Type scope

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#142]
Possibly a regression bug? but this compiles and runs

    Strict

    Type TestType
    EndType

    Global ThisVariable:Int = 20
    Print TestType.ThisVariable

**Comment by GWRon** [comment]
It's not a "new" regression as this "works" for some revisions now.

First commit having this issue is this one: f18881bb2ea24f78657485a2da07da8c2bc664cc (Improved parsing of For statements.)
