### ISSUE TITLE
imported array of function pointers wont compile

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#144]
main source

    Superstrict
    Import "funcs.bmx"

funcs.bmx :-
    
    SuperStrict

    Type param
    EndType
    
    Global funcs:Int(p:param)[2]
    funcs[0] = func_0
    funcs[1] = func_1

    Function func_0:Int(p:param)
    EndFunction

    Function func_1:Int(p:param)
    EndFunction

it errors out with a 'syntax error - expecting identifier' and highlights the last line in the corresponsing .i file

    [...snip...]
    param^Object{
    -New()="______funcs_param_New"
    }="_____funcs_param"
    func_0%(p:param)="_____funcs_func_0"
    func_1%(p:param)="_____funcs_func_1"
    funcs%(p:param)&[]&=mem:p("_____funcs_funcs")

The imported code works as expected when moved into the main source file.

**Comment by davecamp** [comment]
Also using Local function pointers in the imported source doesn't compile. It seems to want to run the function and compains about missing parameters.

Using the imported file from above and replacing the 'Global funcs...' , 'funcs[0]...'  and 'funcs[1]...' statements with

    Local foo:Int(p:param) = func_0
    Local goo:Int(p:param) = func_1

causing the issue. Changing the Local to Global seems to compile ok.

**Comment by davecamp** [comment]
Oh wow... confusing times ahead :p

The original imported file above - changing the global declaration of the array to a local declaration compiles and runs.

**Comment by woollybah** [comment]
Probably an issue with the generated .i or iparser.bmx or both.
