### ISSUE TITLE
Named loops not supported?

### ISSUE THREAD

**Issue by Leushenko** [bmx-ng/bcc#153]
NG doesn't seem to like this:

    #Outer
    For Local i:Int = 0 Until 10
    	Print i
    	If i = 5 Then Exit Outer
    Next
    Print "done."
    End

... giving the error `Identifier 'Outer' not found`.

**Comment by Leushenko** [comment]
Are you, um, sure? The error message has changed, but code trying to use named loops still doesn't compile for me:

    Build Error: failed to compile /Users/alex/BlitzMax.NG/tmp/untitled1.bmx

No further details now. But it goes away if I get rid of named loops.

**Comment by GWRon** [comment]
- fetched latest bcc, compiled bcc and copied it over to NG
- fetched latest bmk, compiled bmk (threaded) and copied it over to NG,

- opened MaxIDE and pasted your sample in a new document, clicked compile n run
```
Building untitled1
[ 99%] Processing:untitled1.bmx
[ 99%] Compiling:untitled1.bmx.console.release.linux.x86.c
[100%] Linking:untitled1
Executing:untitled1
0
1
2
3
4
5
done.

Process complete
```

So maybe you did miss a step?

**Comment by Leushenko** [comment]
@GWRon ah thanks, I didn't build bmk in threaded mode earlier (that's...unusual, but fair enough).

**Comment by GWRon** [comment]
That threaded-mode just allows for a faster module-recompilation - but it should not tackle your problem here. Your issue should have been solved with the latest revisions of BCC.

Did it work?

**Comment by Leushenko** [comment]
It works now. I did rebuild bcc from new sources a few hours ago... don't know in that case what the difference actually was, but it seems to be fixed with a total fresh rebuild.

**Comment by GWRon** [comment]
You missed an important output:

```
Building untitled1
[ 99%] Processing:untitled1.bmx
Internal Error.
[/BlitzMaxNG/mod/brl.mod/blitz.mod/blitz.debug.linux.x86.i;107;0]
Build Error: failed to compile (65280) /BlitzMaxNG/tmp/untitled1.bmx
Process complete
```

So it seems to stumble over something else. You could btw run run a debug-bcc with MaxIDE (given proper command line params (MaxIDE -Menu "Program" - Command Line). So you could check at which point the Internal Error happens... 
For now we will leave that for Brucey.
