### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by Leushenko** [bmx-ng/bcc#156]
Following error when compiling:

    sh: /usr/bin/gcc: Argument list too long
    Build Error: failed to compile (32256) /Users/alex/Projects/...<etc>

No further details offered by the compiler. This is at around 63% completion.

**Comment by woollybah** [comment]
Interesting. I had the same issue whilst testing on AROS, but the Amiga's max command-line length is *much* shorter than Linux...
Looks like we can use @file, and dump the compiler options into a temp file during the build..

**Comment by GWRon** [comment]
Please take into consideration that this "temp file" must use a individual file name, just to avoid problems in a multithreaded compilation process when writing to "args.tmp".

I do not know how fast an md5 hash is (compared to the rest) but maybe hashing the complete content of that tempfile will result in a unique file name. But even then thread 1 might want to remove a file which thread 2 is using. This is of course only possible if there is the possibility of exactly the same arguments (compiling the same file?).

**Comment by woollybah** [comment]
md5 is too slow. I'll use a system API for this probably.

**Comment by GWRon** [comment]
Just as I was interested in measuring it:
```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import "base.util.hashes.bmx"

Global hash:String
Global hashString:string = ""
For local i:int = 0 to 300
	hashString :+ "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua." 
Next


Global startTime:int = Millisecs()
For local i:int = 0 to 100
	hash = Hashes.MD5(hashString)
Next
Global endTime:int = Millisecs()

print "length of string: "+hashString.length
print "hash: " + hash
print "time: " + ((endTime - startTime)/100.0) +" ms"
```
Result:
```
Executing:md5time
length of string: 46655
hash: 31ec1dc4be15cdeafd394365dc1007b4
time: 0.569999993 ms
```
I assume the actual compilation takes longer than this hashing process.

**Comment by woollybah** [comment]
Yeah. I still prefer an API solution. Just because we are programmers, doesn't necessitate us designing new wheels every time ;-) :black_small_square:

**Comment by woollybah** [comment]
Out of interest, what result do you get from:
```
getconf ARG_MAX
```

Thanks!

**Comment by GWRon** [comment]
```
$ getconf ARG_MAX
2097152
```

Sorry for the delay, just came home to my linux box

**Comment by GWRon** [comment]
For __Windows__ the limits are discussed there:
https://blogs.msdn.microsoft.com/oldnewthing/20031210-00/?p=41553

CreateProcess: 32767 characters
CMD.exe: 8192 characters
ShellExecute/Ex: 2048 characters
Environment: 32767 characters
_spawnv(): 1024 bytes

**Comment by woollybah** [comment]
This issue was moved to bmx-ng/bmk#21
