### ISSUE TITLE
conflicting types for function

### ISSUE THREAD

**Issue by Leushenko** [bmx-ng/bcc#158]
Given this code:

    Private
    Extern
    	Function _pipe:Int(p:Byte Ptr) = "pipe"
    	Function _fork:Int() = "fork"
    	Function _close:Int(fd:Int) = "close"
    	Function _dup2:Int(oldfd:Int, newfd:Int) = "dup2"
    	Function _execvp:Int(file:Byte Ptr, argv:Byte Ptr) = "execvp"
    	Function _fcntl1:Int(fd:Int, cmd:Int, arg:Int) = "fcntl"
    	Function _waitpid:Int(pid:Int, status:Int Ptr, options:Int) = "waitpid"
    	Function _read:Int(fd:Int, buf:Byte Ptr, sz:Int) = "read"
    	Function _write:Int(fd:Int, buf:Byte Ptr, sz:Int) = "write"
    	Function _kill:Int(pid:Int, sig:Int) = "kill"
    	
    	Global _errno:Int = "errno"
    	Function _strerror:Byte Ptr(e:Int) = "strerror"
    End Extern
    Public
    Local e:Int = _errno
    Print _strerror(e)

NG produces the following error:

    In file included from /Users/alex/BlitzMax.NG/tmp/.bmx/untitled2.bmx.gui.debug.macos.x86.c:1:
    /Users/alex/BlitzMax.NG/tmp/.bmx/untitled2.bmx.gui.debug.macos.x86.h:42:16: error: conflicting types for 'strerror'
    extern BBBYTE* strerror(BBINT bbt_e);
                   ^
    /usr/include/string.h:81:7: note: previous declaration is here
    char    *strerror(int) __DARWIN_ALIAS(strerror);
             ^
    /Users/alex/BlitzMax.NG/tmp/.bmx/untitled2.bmx.gui.debug.macos.x86.c:61:9: error: use of undeclared identifier 'errno'
                    bbt_e=errno;
                          ^
    2 errors generated.

If I remove the `Private` declaration, then `errno` is declared and usable, but the issue with `strerror` remains. The other functions above are apparently not a problem.

Similar problem here:

    Function ArraySort(a:Object[], cmp:Int(l:Object Var, r:Object Var)) NoDebug
    	Extern "C"
    		Function qsort(base:Byte Ptr, num:Int, sz:Int, cmpf:Byte Ptr)
    	End Extern
    	qsort(Object(a), a.Length, SizeOf(Byte Ptr(0)), cmp)  '#NGFIX bug in byte ptr conversion
    End Function

...produces:

    In file included from /Users/alex/Projects/anathema/Anathema-0-3/runtime/.bmx/Util.bmx.debug.macos.x86.c:1:
    /Users/alex/Projects/anathema/Anathema-0-3/runtime/.bmx/util.bmx.debug.macos.x86.h:236:13: error: conflicting types for 'qsort'
    extern void qsort(BBBYTE* bbt_base,BBINT bbt_num,BBINT bbt_sz,BBBYTE* bbt_cmpf);
                ^
    /usr/include/stdlib.h:157:7: note: previous declaration is here
    void     qsort(void *, size_t, size_t,
             ^
    1 error generated.

Since BlitzMax doesn't actually have a `void *` type, this seems difficult.

One idea might be to not include standard headers at all in emitted code, and instead have the compiler insert declarations only for those functions it actually intends to call. This would presumably provide compatibility with BlitzMax's existing behaviour for those of us misdeclaring C and other runtime functions with the wrong signatures because we know the linker will fix it anyway.

**Comment by woollybah** [comment]
If you create a Util.x file in the same dir as as your Util.bmx, and in there add the line
```
void qsort(void *, size_t, size_t, void *)!
```
(note the exclamation at the end)
Does that sort out the error?

**Comment by Leushenko** [comment]
It does indeed, thanks! What is that feature / where can I read about it?

**Comment by GWRon** [comment]
Regarding "read about it":

http://www.blitzmax.com/Community/post.php?topic=105123&post=1291111

_Brucey:_
> The next issue is a "feature" of the way NG generates C headers for compiling everything.
When you declare a function as extern, it will add this declaration to a header using the types your specified. Unfortunately for Windows APIs, they usually already declared (via windows.h).
And so you see a list of "conflicting types for 'function'" errors.
>
> To get around this issue, I came up with a new filetype that you can include which lists the externs, their correct arg types, and whether you actually want to generate the declaration in the header.
The file should be called FileNameWithExtern.x (where the name of the file matches the one where you have the extern).
>
> Then you add the list of offending functions to the file.
>
> For example, for the error
```BlitzMax
generated code :
extern BBINT __stdcall  ReleaseDC(BBINT bbt_hwnd,BBINT bbt_hdc);
actual code:
WINUSERAPI int WINAPI ReleaseDC(HWND hWnd,HDC hDC);
```
>you would add to the file
```BlitzMax
int ReleaseDC(HWND ,HDC )!
```
>Note the exclamation on the end. It tells the compiler not to generate this in our own header.
And note that the argument names are not included, only their types.
>
>In this particular example, your extern will need changed anyway, since HWND and HDC are both pointers.

**Comment by Leushenko** [comment]
@GWRon thank you.

**Comment by woollybah** [comment]
If you can think of a better way of handling the issue (letting bcc know when it can or shouldn't generate extern declarations in the header), I'd be happy to consider changing the current implementation.
