### ISSUE TITLE
New Value chooses static rather than runtime type

### ISSUE THREAD

**Issue by Leushenko** [bmx-ng/bcc#160]
The following code:

    Type Foo Abstract
    	Method Copy:Foo()
    		Return New Self
    	End Method
    End Type

    Type Bar Extends Foo Final
    	Method ToString:String()
    		Return "Bar"
    	End Method
    End Type

    Type Baz Extends Foo Final
    	Method ToString:String()
    		Return "Baz"
    	End Method
    End Type

    Local a:Foo = New Bar, b:Foo = New Baz
    Local c:Foo = New a, d:Foo = New b
    Local e:Foo = a.Copy(), f:Foo = b.Copy()

...produces errors under NG, `Cannot create instance of an abstract class.` First at `Local c`, and if that is commented out, at `New Self`.

Whereas under BRL BlitzMax, this compiles, and the following addition produces the indicated output by selecting the *runtime* type of the object passed as argument to `New`:

    Print a.ToString()  'Bar
    Print b.ToString()  'Baz
    Print c.ToString()  'Bar
    Print d.ToString()  'Baz
    Print e.ToString()  'Bar
    Print f.ToString()  'Baz

I vaguely remember some discussion of this on the forums a while back. IMO this is a really, *really* cool and useful feature.

**Comment by woollybah** [comment]
That's cool. No idea you could do that...
