### ISSUE TITLE
Reversed function casting error?

### ISSUE THREAD

**Issue by Leushenko** [bmx-ng/bcc#163]
Mismatched types for function pointers seem to have reversed behaviour..?

This compiles without complaint:

    Function Foo:Int(x:Int)
    End Function
    Local Bar:Int(x:Int, y:Int)
    Bar = Foo

The C compiler doesn't complain, although it would be within its rights to do so, without a cast in the emitted code. BRL BlitzMax gives the error `Unable to convert from 'Int(Int)' to 'Int(Int,Int)'`.

Whereas changing the last line to this, as one would to get around the BRL compiler's error -

    Bar = Byte Ptr(Foo)

...produces the error `Missing function argument 'x'.`

**Comment by woollybah** [comment]
I've fixed the first part of your issue. It's really tightened up the cast tests for function pointers. Thanks ;-)
Still investigating the second part...
