### ISSUE TITLE
extern base interface call convention ignored

### ISSUE THREAD

**Issue by SRSSoftware** [bmx-ng/bcc#164]
Sorrrrrry.

After enhancing some more code that uses a base interface enclosed within a win32 block, I've just noticed that the very first base interface methods don't have the stdcall convention applied. Rather strange as the derived interfaces do.

**Comment by davecamp** [comment]
SRSSoftware is one of my older github accounts, lol.

**Comment by woollybah** [comment]
In my tests I get this:
```c
typedef struct Derived Derived;
struct DerivedVtbl {
	void( __stdcall * One)(struct Derived*);
	void( __stdcall * Two)(struct Derived*);
	void(*_ctor)();
	void(*_dtor)();
	void( __stdcall * Three)(struct Derived*);
...
```
Can you point me to some code that isn't working?
Thanks!

**Comment by woollybah** [comment]
Fixed. :-)

**Comment by davecamp** [comment]
Cool!
Just for the record it was when a base interface and the derived interface are defined in separate files within their own separate extern win32 block.

**Comment by davecamp** [comment]
This isn't fixed just yet.
I've narrowed it down so that you can reproduce it...

1. Module A, you have an Extern"Win32" block with an interface inside it ( interface A ).
2. Module B also has an interface ( interface B ) inside an Extern"Win32" block.
3. Module B imports module A.
4. Interface B extends interface A.

In the generated code for interface A the stdcall is missing.
In interface B the methods of the base interface A also have the stdcall missing. However the specific Interface B methods do have the stdcall decoration.

In the case that I'm using this approach it doesn't actually have any effect, hence how I missed previously, but it is an error.

**Comment by woollybah** [comment]
I set up a project as above - two modules with interfaces. Everything appears to be generating as expected:
```blitzmax
SuperStrict
Module test.t1

Extern "win32"

	Interface it1
	
		Method one(a:Int)
		Method two:Int(a:Int)
		
	End Interface

End Extern
```

```blitzmax
SuperStrict
Module test.t2

Import test.t1

Extern "win32"

	Interface it2 Extends it1
	
		Method three(a:Int)
		
	End Interface

End Extern
```

and a test app
```blitzmax
SuperStrict

Framework test.t2

Extern "win32"

Type abc implements it2

	Method one(a:Int)
	Method two:Int(a:Int)
	Method three(a:Int)

End Type

End Extern
```
generated headers, respectively:
```c
struct it1Vtbl {
	void( __stdcall * one)(struct it1*,BBINT);
	BBINT( __stdcall * two)(struct it1*,BBINT);
};
```

```c
struct it2Vtbl {
	void( __stdcall * one)(struct it1*,BBINT);
	BBINT( __stdcall * two)(struct it1*,BBINT);
	void( __stdcall * three)(struct it2*,BBINT);
};
```

```c
struct abcVtbl {
	void( __stdcall * three)(struct abc*,BBINT);
	void(*_ctor)();
	void(*_dtor)();
	void( __stdcall * one)(struct abc*,BBINT);
	BBINT( __stdcall * two)(struct abc*,BBINT);
};
```

Did I miss something else?

**Comment by davecamp** [comment]
That's strange, in this commit of the d3d11 driver :- https://github.com/SRSSoftware/srs.mod/tree/d698ef4a9dd3bae55fd8384cf53230584b2ba925 ( the very latest commit uses superstrict in all ng files and apps don't compile, another issue that may be my fault, ive not gone through it just yet ) In win32.mod/ win32.bmx the IUnknown interface always gets generated without the stdcall in the c file.
