### ISSUE TITLE
latest bcc 'rebuild all modules' error

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#166]
Using the latest bcc and forcing a rebuild of the modules gives this error

    Compile Error: Syntax error - expecting identifier.
    [C:/BlitzMax/mod/pub.mod/directx.mod/.bmx/dd.bmx.debug.win32.x64.i;543;0]
    Build Error: failed to compile (-1) C:/BlitzMax/mod/pub.mod/directx.mod/directx.bmx
    Process complete

which opens up file dd.bmx.debug.win32.x64.i and highlights the very last line of this...

    IDirectDraw^IUnknown{
    -Compact%()="Compact"
    -CreateClipper%()="CreateClipper"
    -CreatePalette%()="CreatePalette"
    -CreateSurface%(surfacedesc@*,surf?IDirectDrawSurface*,outer@*)="CreateSurface"
    -DuplicateSurface%()="DuplicateSurface"
    -EnumDisplayModes%(flags%,surf@*,context:Object,callback% (surf@*,context:Object))="EnumDisplayModes"
    -EnumSurfaces%()="EnumSurfaces"
    -FlipToGDISurface%()="FlipToGDISurface"
    -GetCaps%(driverCaps@*,helCaps@*)="GetCaps"
    -GetDisplayMode%()="GetDisplayMode"
    -GetFourCCCodes%()="GetFourCCCodes"
    -GetGDISurface%()="GetGDISurface"
    -GetMonitorFrequency%()="GetMonitorFrequency"
    -GetScanLine%()="GetScanLine"
    -GetVerticalBlankStatus%()="GetVerticalBlankStatus"
    -Initialize%()="Initialize"
    -RestoreDisplayMode%()="RestoreDisplayMode"
    -SetCooperativeLevel%(hwnd%,flags%)="SetCooperativeLevel"
    -SetDisplayMode%(width%,height%,bpp%)="SetDisplayMode"
    -WaitForVerticalBlank%(flags%,event%)="WaitForVerticalBlank"
    }EW=0

**Comment by GWRon** [comment]
Currently BCC just checks:
- EI
- EIW
- ES
- ESW

```Blitzmax
							ApplyFunctionAttributes(class, DECL_ABSTRACT)
						Else If CParse("EI")
							class.attrs :| DECL_EXTERN | CLASS_INTERFACE
							
							ApplyFunctionAttributes(class, DECL_EXTERN | DECL_ABSTRACT)
						Else If CParse("EIW")
							class.attrs :| DECL_EXTERN | CLASS_INTERFACE | DECL_API_WIN32
							
							ApplyFunctionAttributes(class, DECL_EXTERN | DECL_ABSTRACT | DECL_API_WIN32)
						Else If CParse("ES")
							class.attrs :| DECL_EXTERN | CLASS_STRUCT
						Else If CParse("ESW")
							class.attrs :| DECL_EXTERN | CLASS_STRUCT | DECL_API_WIN32 
						End If
```

So it does not handle "DECL_EXTERN | DECL_API_WIN32". Maybe Brucey just missed it (feel free to add it on your own):

```Blitzmax
						Else If CParse("EW")
							class.attrs :| DECL_EXTERN | DECL_API_WIN32 
```
But it might also need something more (not able to test now).

**Comment by woollybah** [comment]
EW... yeah, it did cross my mind at the time..
