### ISSUE TITLE
print FunctionWithVoidReturn() should fail before bmx->c step

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#175]
```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.GLMax2D


'GlEnable(...) returns void
Print GlEnable(GL_LINE_SMOOTH)
```
This compiles bmx to c and then fails:

```
/BlitzMaxNG_overload/tmp/.bmx/untitled3.bmx.gui.release.linux.x86.c: In function â_bb_mainâ:
/BlitzMaxNG_overload/tmp/.bmx/untitled3.bmx.gui.release.linux.x86.c:9:3: error: invalid use of void expression
   brl_standardio_Print(bbStringFromInt(glEnable((GLenum)2848)));
   ^
```

Think the "end-user/coder" expects a error output before the C-step. Same error happens for "return VoidFunction()" within a Function/Method.

I do not have an idea how that message could be. "Invalid use of a void-value." / "Void-values cannot be used this way."

**Comment by woollybah** [comment]
glEnable() returns void.
Your code is broken :-)

Or rather, glEnable() is defined in a Strict source, which incorrectly applies :Int as a return type, and which allows bmx code to parse and semant successfully.

A fix would be to SuperStrict pub.glew.  Good luck! :-)

**Comment by GWRon** [comment]
I know that the code is broken ... but the error is not really "helping" normal users.

So the usage of a void-result should be resulting in a better / more clear error message - not pointing to the c-code, but the erroneous-bmx-code-line.

**Comment by woollybah** [comment]
Well, when you come up with a solution you can PR it :-)

As a start, you will need to determine a way for Strict code to not apply :Int return types for specific cases of Extern functions.
