### ISSUE TITLE
[Overload] type widening fails

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#177]
I do not know wether I misunderstood what you brought in with "type widening".

Imho this means, BCC accepts number types defined within the range of another. So using "int" for "float" is ok and more expanded: "byte for short, int, float, double, long".

But this does not compile:
```
SuperStrict

Framework Brl.StandardIO

'should work int->double
Sin( MilliSecs() )
'should work float->double
Sin( Float(MilliSecs()) )

'same for Ceil(), Floor(), ...
```
Output: `Compile Error: Unable to find overload for sin(Int). `

**Comment by woollybah** [comment]
I've amended the error message. it will now say : ```Identifier 'sin' not found.```

**Comment by GWRon** [comment]
Lol ...ok recognized I missed "Import Brl.Retro" for Sin() ... 

Regarding `Identifier 'sin' not found.` - dunno if it is more clear to the end user if you distinguish between functions/methods/variables: this time we call "sin(x)" so it is a function/method.
`Function/Method 'sin' not found.`. Identifier sounds like const, global, local, field - which could contain callbacks ...hmmm, just forget about it ;-)
