### ISSUE TITLE
Inbuilt functions Abs() returns "double" - vanilla returns same as given

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#178]
In vanilla Blitzmax, the inbuilt functions (Abs, ~~Ceil, Floor~~, ~~Min, Max, ...~~) return the same number type than what you gave as parameter. In NG "double" is returned regardless of what you gave

```BlitzMax
SuperStrict

Framework Brl.StandardIO
Import Brl.Reflection

'vanilla: unable to convert from 'Double' to 'Object'
Local tA:TTypeId = TTypeId.ForObject( Abs(1.0!) )

'vanilla: unable to convert from 'Float' to 'Object'
Local tB:TTypeId = TTypeId.ForObject( Abs(1.0) )

'vanilla: unable to convert from 'Int' to 'Object'
Local tC:TTypeId = TTypeId.ForObject( Abs(1) )
```

__Edit__: above example wont compile with the same message in NG [overload] - as it tries to find a overloaded function "ForObject( numberInsteadObject )".

__Edit2__: removed mistakingly assumed "inbuilt"-functions (Floor, Ceil) and added `Min()` and `Max()`.

__Edit3__: seems only `Abs()` was problematic.

**Comment by woollybah** [comment]
Ceil and Floor are not builtin functions. They are declared in BRL.Math.

**Comment by GWRon** [comment]
Oh ... you're right, my mistake.

sorry for the fuzz.

**Comment by GWRon** [comment]
Same for "Min()" and "Max()", they return the "biggest used number type".

```BlitzMax

SuperStrict

Framework Brl.StandardIO
Import Brl.Reflection

'vanilla: unable to convert from 'Double' to 'Object'
'Local tA:TTypeId = TTypeId.ForObject( Max(2.0!, 1.0) )

'vanilla: unable to convert from 'Float' to 'Object'
'Local tB:TTypeId = TTypeId.ForObject( Min(1, 2.0) )

'vanilla: unable to convert from 'Int' to 'Object'
Local tB:TTypeId = TTypeId.ForObject( Min(1, 2) )
```

**Comment by woollybah** [comment]
Min and Max use type balancing. What appears to be the problem with them?

**Comment by GWRon** [comment]
You are right, min/max is not affected. Was misassuming things (just checked with NG-overload and as the errors were the same ... think it's time for bed :smiley:
