### ISSUE TITLE
BCC.conf to define defaults

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#186]
This was suggested via mail some time ago, so I just print it here for documentation (and "closing" if included).

What about adding support for default-params in __bcc.conf__ ?
Lately (with the inclusion of overloading and the removal of implicit type conversion) people run into trouble compiling their (vanilla) modules.

My suggestion is:
- allow setting "default params" via __bcc.conf__
- arguments on the commandline override conf-values (so `warning:int = conf.GetBool("warning", False)` + `if arg = "w" then warning = true`)
- overrideable: "-s", "-w", "-d" (create "debug" if nothing defines "-r" - or vice versa)
- there might be a second param for "-w off" needed (to override a conf-w-enabling again)

That would allow to once-and-for-all place a __bcc.conf__ next to bcc[.exe] and it should behave more like vanilla BCC. And if you want to use the improved features, remove conf-file or use the desired parameters.

**Comment by woollybah** [comment]
I think adding options to disable options that might be enabled in a config file is a bit much... ?

**Comment by GWRon** [comment]
what do you mean with "adding options to disable options" ?

I think:
- bcc defines basic behaviour (`global mode_warning:int = True`)
- bcc.conf defines basic behaviour too but is adjustable by the user (`warning=0`), if there is something defined in bcc.conf, it overrides "basic behaviour" defined in the bcc-sourcecode
- bcc[.exe] args override the basic behaviour of both options above (it overrides the current behaviour defined in bcc, which might be overriden already by bcc.conf)

**Comment by woollybah** [comment]
I decided to implement this in bmk rather than bcc.

**Comment by GWRon** [comment]
No problem - albeit your implementation looks less "cool" than my suggestion,
