### ISSUE TITLE
sizeof reports wrong size for 64bit build

### ISSUE THREAD

**Issue by SRSSoftware** [bmx-ng/bcc#188]
Type DXGI_MODE_DESC
	Field Width:int
    	Field Height:int
      	Field RefreshRate_Numerator:int
    	Field RefreshRate_Denominator:int
    	Field Format:int
    	Field ScanlineOrdering:int
    	Field Scaling:int
    EndType

in an x64 build reports as size 32, in x86 build reports as a size of 28. should be 28 in both.

**Comment by woollybah** [comment]
It's currently calculated thus : 
```sizeof(struct _type_) - sizeof(void*)```
But I guess that will include padding on the end, etc.

I suppose it will just need to store a bcc-calculated value instead.

**Comment by SRSSoftware** [comment]
Yeah, a common issue with padding.
I noticed it when a c++ call returns an array of DXGI_MODE_DESCs into some MemAlloced memory, then stepping through that memory using the sizeof operator to get each instance of DXGI_MODE_DESC.

I have an easy fudge for the time being.
Cheers!
