### ISSUE TITLE
other sse datatypes?

### ISSUE THREAD

**Issue by SRSSoftware** [bmx-ng/bcc#189]
Hey Brucey,

I noticed that you added the Double128 type too. Great stuff.
Is it worth putting in the last one?

__m64 could map to Float64.

Also I have a module made up of all the sse/sse2/sse3/ssse3/sse41/sse42 functions.
As kind of expected there are some little issues to iron out, namely some functions that take pointers for parameters, for eg

```
__mm_load_ps(fp:float ptr)
```

I get a c compiler error of a type mismatch - shall I use a .x file for this or is there another way, or leave them out altogether?

**Comment by SRSSoftware** [comment]
Also some of the sse functions are #defined in the c headers, whats the best way to deal with these? If anything at all? Make my own version to remove the #define? or is there a better way?

Cheers!

**Comment by woollybah** [comment]
Hopefully everything is working now as expected?

**Comment by SRSSoftware** [comment]
The datatypes seem to be working great. I'm primarily using the float128 for vector and matrix work. I'm sure that if they work ok then the other types and functions will too.

Thanks again for implementing this!

**Comment by SRSSoftware** [comment]
Ahh, No biggie - I've just changed a little bit of code and noticed that types that have the new datatypes as a field member that don't have an initialiser cause a compilation error. If the field member has an initialiser then it compiles ok.
This compiles ok

    Type test
    	Field _a:float128 = _mm_setr_ps(0.0, 0.0, 0.0, 1.0)
    EndType

this fails

    Type test
    	Field _a:float128
    EndType

with

    error: expected expression before '{' token o->__m_untitled2_test__a = {};

**Comment by SRSSoftware** [comment]
I guess the other datatypes are initialised to 0 somewhere so I suppose these new ones needs the same.

**Comment by woollybah** [comment]
I found the correct zero initialisers. Hopefully that'll sort it out.

**Comment by SRSSoftware** [comment]
Nice one!
One other thing... casting... usually a cast is allowed as long as the number of bits are the same, so an Int128 is freely castable to float128 and visa versa etc. Is it possible to allow this too, or will it have complications?

**Comment by SRSSoftware** [comment]
That would mean that Floar128, Double128, Int128 are castable to each other. And I guess Float64 and Long ( int64?  there is no __m64 in 'Max as __m64 is used mainly in mmx and superseded by the bigger 128 sse versions ) would be castable to each other too.

**Comment by davecamp** [comment]
Lol, I'm meant no __m64i.

**Comment by woollybah** [comment]
Casting seems to be working now. The following is supported
xxx128 <---> xxx128
Float64 <---> Long/ULong/Size_T (which are all 64-bit types)

**Comment by woollybah** [comment]
I haven't investigated that function call type that you mentioned. If you have some good resources for it, I'll have a further read ;-)

**Comment by SRSSoftware** [comment]
Excellent!

To be honest...
1. I've read that *nix systems do it anyway yet I don't actually see it happening in real code.
2. google searches for 'gcc vectorcall' doesn't really give help and only returns 'patch requests' for including it circa 2014. I can't find anything in the manual.
3. It's an abi micro-optimisation.

There's a fair amount of info regarding its use in the later MS compilers, but GNU isn't MS ( thankfully :D )
Some info about it... 
https://en.wikipedia.org/wiki/X86_calling_conventions#Microsoft_vectorcall
https://blogs.msdn.microsoft.com/vcblog/2013/07/11/introducing-vector-calling-convention/

**Comment by woollybah** [comment]
Closing, as I don't think GCC is/will-ever-be capable of this.

Another option would be to port to the MS compiler... but that's probably quite a big job.
