### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by SRSSoftware** [bmx-ng/bcc#190]
First off, can you confirm that I should be using the legacy 'max compiler to build bcc yes?

I'm getting

     Compiling:iparser.bmx
     Compile Error: Unable to convert from 'String Array' to 'TClassDecl Array'
     [E:/BlitzMax_NG/src/bcc/iparser.bmx;535;3]
     Build Error: failed to compile E:/BlitzMax_NG/src/bcc/iparser.bmx
     Process complete

when building with the latest commit.

**Comment by GWRon** [comment]
As long as no new NG-feature is used in the BCC sources I think the best bet is tp use vanilla for compiling.

Nonetheless your issue might be a bug introduced in the latest commits.

**Comment by davecamp** [comment]
Hey Ronny,
Yeah I always use the legacy one for bcc so it looks it is a bug, cheers.
