### ISSUE TITLE
function is incorrectly called twice...

### ISSUE THREAD

**Issue by SRSSoftware** [bmx-ng/bcc#194]
It took a loooong time to find out what was causing what seemed like an intermittent bug but I found it. I've narrowed it down to returning an array and passing that array to a function via a ptr. Same thing happens for all array types -

    Strict

    AcceptData GetData()

    Function AcceptData(data:Int Ptr)
    	Print "AcceptData"
    EndFunction

    Function GetData:Int[]()
    	Print "GetData"
    	Return New Int[4]
    EndFunction

Outputs...

    GetData
    GetData
    AcceptData

**Comment by woollybah** [comment]
Apologies for hard to find bugs :-(

**Comment by GWRon** [comment]
> Apologies for hard to find bugs :-(

Seems easter holidays are everyday of the year.
