### ISSUE TITLE
DefData with comment

### ISSUE THREAD

**Issue by Bobysait** [bmx-ng/bcc#197]
if I add comments to my data, it doesn't compile and returns an error
"Labels must appear before a loop or DefData statement"

```
#somelabel
' some comment
DefData "some","data"

```
Removing the comment allows to compile, but, I almost always comment the data structur inside the defData (easier to read)

Also, inserting an empty line after the label will generate the same error

```
#somelabel

DefData "some","data"

```

**Comment by GWRon** [comment]
Are you using the latest revision of BCC?

Both samples compile fine here, using the latest BCC

**Comment by Bobysait** [comment]
I thought it was, I'm going to recheck that.

**Comment by GWRon** [comment]
Think the boss might close the issue then :-)

**Comment by woollybah** [comment]
Seems to be working.

**Comment by atv2016** [comment]
Boby can you contact me, i replied to your email but it seems to bounce. Or ping me through github.
