### ISSUE TITLE
Function pointer Var parameter

### ISSUE THREAD

**Issue by SRSSoftware** [bmx-ng/bcc#198]
Hiya,

The one doesn't compile

    Strict
    Global myCallback:Int(a:Float)
    
    GetCallback(myCallback)
    myCallback(10.0)
    
    Function GetCallback(callback:Int(a:Float) Var)
    	callback = CallTheFunction
    EndFunction
    
    Function CallTheFunction:Int(value:Float)
    	Print value
    EndFunction

with an error message of

    Building untitled1
    [ 99%] Processing:untitled1.bmx
    Compile Error: Syntax error - expecting ','.
    [E:/BlitzMax_NG/tmp/untitled1.bmx;9;0]
    Build Error: failed to compile E:/BlitzMax_NG/tmp/untitled1.bmx
    Process complete

while highlighting the function parameter of GetCallback.
However it does compile and run with legacy bcc.

**Comment by woollybah** [comment]
Thanks ;-)
