### ISSUE TITLE
Function/Method with a function pointer return type

### ISSUE THREAD

**Issue by SRSSoftware** [bmx-ng/bcc#199]
Hey :p

This also doesn't compile...

   Strict
   
   Function GetFunc:Int(a:Int)(b:Int)
   EndFunction

errors out with not understanding the true nature of the function pointer return type.

**Comment by GWRon** [comment]
Seems it parses it incorrect.

Think it should parse for brackets from the right part to the left until charPos = 0 or corresponding bracket found.

**Comment by woollybah** [comment]
Mmmm. Tricky one. Thanks :-)

Generating the C has been most fun...
```
BBINT(* _m_GetFunc(BBINT bbt_b))(BBINT) ...
```

**Comment by Bobysait** [comment]
Hey,

Jetez un coup œil à ces choses, c’est tellement drôle! Je ne pouvais pas arrêter de rire, lisez le ici <http://prakekuze.stephenhabgood.com/xonqkv>

Affectueusement... bybysait@free.fr
