### ISSUE TITLE
Interface and Derived in module file gives an error

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#201]
Hiya,

In a module file
A 'non externed' interface / type combination results in an error of

    Compile Error: Extern methods cannot be used to implement interface methods.

The exact same interface/type combo work ok when they are in the main application file.

**Comment by woollybah** [comment]
Your issues that include even small snippets of source are fixed more quickly than those where I need to think about setting everything up from scratch ;-)

**Comment by davecamp** [comment]
Uh huh, here you go :-)
djjc.mod/iface.mod/iface.bmx:

    Interface IFace
    	Method DoSometinhg()
    EndInterface

    Type TFace Implements IFace
    	Method DoSometinhg()
    	EndMethod
    EndType

Main file

    Import djjc.iface
    Local inst:IFace = New TFace

It seems when an interface is in a module theres an assumption that it's an Extern interface.

**Comment by woollybah** [comment]
Thanks. My test was working, but it wasn't quite the same as your example :-)

**Comment by davecamp** [comment]
Sorry about that, I should know by now that my words aren't always the clearest to understand :O)

**Comment by GWRon** [comment]
Welcome to the club. At least I can exculpt by mentioning that English isn't my mother tongue.

Am 11. Juni 2016 15:10:42 MESZ, schrieb davecamp <notifications@github.com>:

**Comment by Bobysait** [comment]
Salut,
Certains de mes amis pensent que c’est vraiment intéressant, jeter un coup d’œil <http://procrulafru.georgefinancialservices.com/xoyqaj>

Affectueusement... bybysait@free.fr

**Comment by Bobysait** [comment]
Hey,

J'ai trouvé un tutoriel très facile sur les choses que nous parlions, regardez ici <http://pilelade.instantapphere.com/xomocj>

Grosses bises, bybysait@free.fr
