### ISSUE TITLE
EAV on pub.lua compilation (also some brl modules)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#203]
During compilation of pub.lua with the most recent revision (7c636d94a331e5f107734b6935a3409e93cdbbe3) leads to an EAV in my Windows XP VM.

Running the compilation with "-v" leads to this lines segfaulting:

```
[ 97%] Processing:lua.bmx
"E:/BlitzMaxNG/bin/bcc.exe"  -g x86 -m pub.lua -v -s -w -p win32 -o "E:/BlitzMaxNG/mod/pub.mod/lua.mod/.bmx/lua.bmx.debug.win32.s" "E:/BlitzMaxNG/mod/pub.mod/lua.mod/lua.bmx"
Parsing...
```
and the same afterwards when doing the release build
```
[ 97%] Processing:lua.bmx
"E:/BlitzMaxNG/bin/bcc.exe"  -g x86 -m pub.lua -v -r -s -w -p win32 -o "E:/BlitzMaxNG/mod/pub.mod/lua.mod/.bmx/lua.bmx.release.win32.s" "E:/BlitzMaxNG/mod/pub.mod/lua.mod/lua.bmx"
Parsing...
```

running this ` -g x86 -m pub.lua -v -r -s -w -p win32 -o "E:/BlitzMaxNG/mod/pub.mod/lua.mod/.bmx/lua.bmx.release.win32.s" "E:/BlitzMaxNG/mod/pub.mod/lua.mod/lua.bmx"` as param in a MaxIDE-BCC-debug-build leads to:

```
Executing:bcc.debug.exe
Parsing...
Compile Error: Can't find interface for module 'brl.classes'
[E:/BlitzMaxNG/mod/pub.mod/lua.mod/lua.bmx;1;0]
```

I do not use a `bcc.conf` nor other files than `core.bmk` and `make.bmk`. Both, bcc and bmk are compiled

Same happens for "blitz.mod" and other modules too.

**Comment by GWRon** [comment]
Issue was not apparent 3 revisions before, dunno if the one with "invalid pointer error" has the issue already.

**Comment by woollybah** [comment]
It's probably an issue with your build. I have no problems here.
I did a full modules build with a legacy-compiled version of bcc. Then I built bcc again with NG, and built modules again. It seems to be working fine.

The ```Can't find interface for module...``` message is unrelated, and likely due to you not having a correctly set up bcc.conf

**Comment by GWRon** [comment]
Tried with and without bcc.conf

Tried various revisions - and all worked, until the 3rd-newest one was commited (the one with the pointer issue)

**Comment by GWRon** [comment]
Regarding `Can't find ...`, yes you were right with this (is unrelated) - just forgot to adjust the "bcc.conf"-file in the source directory too (from where the debug-bcc was run then ...)

**Comment by GWRon** [comment]
When compiling the module, it does EAV but creates the `lua.release.win32.x86.a` file ... while the `lua.release.win32.x86.i` is not created (nor updated if already existing).

**Comment by DruggedBunny** [comment]
This is my current status on trying to build all modules, for what it's worth (this update did fix the lua.bmx build for me):

`
...

[ 52%] Processing:opengles.bmx
[ 52%] Processing:stdc.bmx
[ 53%] Processing:com.bmx
Compile Error: Invalid Pointer type.
[I:/SpiderOak/DevTools/Blitz/Frisky_win32_v1_0/BNGDumps/1465682068/BlitzMaxNG/mod/pub.mod/win32.mod/com.bmx;105;0]
Build Error: failed to compile I:/SpiderOak/DevTools/Blitz/Frisky_win32_v1_0/BNGDumps/1465682068/BlitzMaxNG/mod/pub.mod/win32.mod/com.bmx
Process complete
`

Line 105 is:

`Method lfget_Application(ppDisp:IDispatch Ptr Ptr)`

... so it doesn't seem too happy with Ptr Ptr here.

**Comment by GWRon** [comment]
"Invalid Pointer" happened with the "semi-latest" revision.

**Comment by DruggedBunny** [comment]
Still happening with the 3 hours old version here, as it did prior to that, so not sure if that helps...

**Comment by GWRon** [comment]
So you are able to do `bmk makemods -a -r brl.blitz` ? Mine EAV's right at the end...  if this is possible for you, my setup is either borked - or your bcc is still outdated (somehow)

**Comment by DruggedBunny** [comment]
That seemed to go OK, Derron:

`I:\SpiderOak\DevTools\Blitz\BlitzMaxNG_077\bin>bmk makemods -a -r brl.blitz
[  1%] Compiling:allchblk.c
[  3%] Compiling:alloc.c
[  5%] Compiling:backgraph.c
[  7%] Compiling:blacklst.c
[  9%] Compiling:checksums.c
[ 11%] Compiling:darwin_stop_world.c
[ 13%] Compiling:dbg_mlc.c
[ 15%] Compiling:dyn_load.c
[ 17%] Compiling:finalize.c
[ 19%] Compiling:gc_dlopen.c
[ 21%] Compiling:gcj_mlc.c
[ 23%] Compiling:headers.c
[ 24%] Compiling:mach_dep.c
[ 26%] Compiling:malloc.c
[ 28%] Compiling:mallocx.c
[ 30%] Compiling:mark.c
[ 32%] Compiling:mark_rts.c
[ 34%] Compiling:misc.c
[ 36%] Compiling:new_hblk.c
[ 38%] Compiling:obj_map.c
[ 40%] Compiling:os_dep.c
[ 42%] Compiling:pcr_interface.c
[ 44%] Compiling:pthread_start.c
[ 46%] Compiling:pthread_stop_world.c
[ 48%] Compiling:pthread_support.c
[ 49%] Compiling:ptr_chck.c
[ 51%] Compiling:real_malloc.c
[ 53%] Compiling:reclaim.c
[ 55%] Compiling:specific.c
[ 57%] Compiling:stubborn.c
[ 59%] Compiling:thread_local_alloc.c
[ 61%] Compiling:typd_mlc.c
[ 63%] Compiling:win32_threads.c
[ 65%] Compiling:blitz_app.c
[ 67%] Compiling:blitz_array.c
[ 69%] Compiling:blitz_cclib.c
[ 71%] Compiling:blitz_debug.c
[ 73%] Compiling:blitz_ex.c
[ 75%] Compiling:blitz_gc.c
[ 76%] Compiling:blitz_handle.c
[ 78%] Compiling:blitz_incbin.c
[ 80%] Compiling:blitz_memory.c
[ 82%] Compiling:blitz_module.c
[ 84%] Compiling:blitz_object.c
[ 86%] Compiling:blitz_string.c
[ 88%] Compiling:blitz_thread.c
[ 90%] Compiling:blitz_types.c
[ 92%] Compiling:blitz_unicode.c
[ 94%] Compiling:tree.c
[ 96%] Processing:blitz.bmx
[ 98%] Compiling:blitz.bmx.release.win32.x86.c
[100%] Archiving:blitz.release.win32.x86.a
I:/SpiderOak/DevTools/Blitz/BlitzMaxNG_077/MinGW32/bin/ar.exe: creating I:/Spide
rOak/DevTools/Blitz/BlitzMaxNG_077/mod/brl.mod/blitz.mod/blitz.release.win32.x86
.a

I:\SpiderOak\DevTools\Blitz\BlitzMaxNG_077\bin>`

**Comment by DruggedBunny** [comment]
Er, the code tag thing doesn't really work, does it?

**Comment by GWRon** [comment]
You need to do 3 times that sign :-)

**Comment by DruggedBunny** [comment]
So, like I said... :P

I'm definitely using 4-hour old bcc, fresh from Github Desktop!

**Comment by woollybah** [comment]
There's currently an issue with pub win32 and win32 maxgui. I'm looking into it.

**Comment by DruggedBunny** [comment]
Cool, cheers, Brucey. Those are certainly the problem mods I've been running into, anyway.

**Comment by GWRon** [comment]
- Created new directory "E:\BlitzMaxNG.new"
- compiled current bcc.exe, current bmk.exe
- copied bcc.exe and bmk.exe to "E:\BlitzMaxNG.new\bin"
- created "E:\BlitzMaxNG.new\bin\bcc.conf" with `BMXPATH_WIN32=E:\BlitzMaxNG.new`
- copied core.bmk and make.bmk from the current-bmk-directory to "E:\BlitzMaxNG.new\bin"
- downloaded current pub.mod-master, brl.mod-master and extracted them to "E:\BlitzMaxNG.new\mod"
- copied "MinGW32" (tdm64-gcc-5.1.0-2.exe) into "E:\BlitzMaxNG.new\bin"

```
E:\BlitzMaxNG.new\bin>bmk makemods -r brl.blitz
[  1%] Compiling:allchblk.c
[  3%] Compiling:alloc.c
[  5%] Compiling:backgraph.c
[  7%] Compiling:blacklst.c
[  9%] Compiling:checksums.c
[ 11%] Compiling:darwin_stop_world.c
[ 13%] Compiling:dbg_mlc.c
[ 15%] Compiling:dyn_load.c
[ 17%] Compiling:finalize.c
[ 19%] Compiling:gc_dlopen.c
[ 21%] Compiling:gcj_mlc.c
[ 23%] Compiling:headers.c
[ 24%] Compiling:mach_dep.c
[ 26%] Compiling:malloc.c
[ 28%] Compiling:mallocx.c
[ 30%] Compiling:mark.c
[ 32%] Compiling:mark_rts.c
[ 34%] Compiling:misc.c
[ 36%] Compiling:new_hblk.c
[ 38%] Compiling:obj_map.c
[ 40%] Compiling:os_dep.c
[ 42%] Compiling:pcr_interface.c
[ 44%] Compiling:pthread_start.c
[ 46%] Compiling:pthread_stop_world.c
[ 48%] Compiling:pthread_support.c
[ 49%] Compiling:ptr_chck.c
[ 51%] Compiling:real_malloc.c
[ 53%] Compiling:reclaim.c
[ 55%] Compiling:specific.c
[ 57%] Compiling:stubborn.c
[ 59%] Compiling:thread_local_alloc.c
[ 61%] Compiling:typd_mlc.c
[ 63%] Compiling:win32_threads.c
[ 65%] Compiling:blitz_app.c
[ 67%] Compiling:blitz_array.c
[ 69%] Compiling:blitz_cclib.c
[ 71%] Compiling:blitz_debug.c
[ 73%] Compiling:blitz_ex.c
[ 75%] Compiling:blitz_gc.c
[ 76%] Compiling:blitz_handle.c
[ 78%] Compiling:blitz_incbin.c
[ 80%] Compiling:blitz_memory.c
[ 82%] Compiling:blitz_module.c
[ 84%] Compiling:blitz_object.c
[ 86%] Compiling:blitz_string.c
[ 88%] Compiling:blitz_thread.c
[ 90%] Compiling:blitz_types.c
[ 92%] Compiling:blitz_unicode.c
[ 94%] Compiling:tree.c
[ 96%] Processing:blitz.bmx
[ ==== EAV HERE ==== ]
[ 98%] Compiling:blitz.bmx.release.win32.x86.c
gcc.exe: error: E:/BlitzMaxNG.new/mod/brl.mod/blitz.mod/.bmx/blitz.bmx.release.win32.x86.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
Build Error: failed to compile (1) E:/BlitzMaxNG.new/mod/brl.mod/blitz.mod/.bmx/blitz.bmx.release.win32.x86.c

**Comment by GWRon** [comment]
If you want you could try my variant:  http://www.digidea.de/files/BlitzMaxNG.new.7z
(I just archived my BlitzMaxNG.new-directory).

If it fails for you then too: try to replace bcc.exe with yours. BTW: do not forget to adjust "bcc.conf" to reflect your directory structure.

**Comment by GWRon** [comment]
Did a not "quick" compile of BCC, copied this, and no segfault this time. Maybe it got borked somehow because I compiled on a samba-share (so file-time differs ... if that has a chance to be the culprit).

**Comment by Bobysait** [comment]
Bonjour, j'ai quelque chose de nouveau pour vous, vous allez définitivement aimez, Jetez un coup d’œil sur <http://lteprangonga.orlandopoolguard.com/xomnt>

Gros bisous, bybysait@free.fr

**Comment by GWRon** [comment]
Feel free to write in English about your issue.


Do you use the latest pub.lua from bmx-ng?

Am 19. Juni 2016 15:51:53 MESZ, schrieb Boby Sait <notifications@github.com>:

**Comment by woollybah** [comment]
It's just spam :-p

**Comment by GWRon** [comment]
So boby's account seems to be one of the acccounts used in that "github attack" of some days ago.

Maybe one should inforn him via the blitzmax forums (dunno if he reads github mails)

**Comment by Bobysait** [comment]
Hey, je pense avoir trouvé le truc que vous recherchez, il suffit de jeter un coup d'œil ici <http://provavasa.meridethboswell.com/xojrip>

Grosses bises, bybysait@free.fr

**Comment by Bobysait** [comment]
Bonjour,

Je viens de trouver de nouvelles méthodes pour résoudre le problème que vous faites face, lire plus ici <http://pungopina.bostonburgerbar.com/xowpsi>

Bisouxx, bybysait@free.fr

**Comment by Bobysait** [comment]
Hey,
Comme je l'ai compris de votre dernier message, vous recherchez des informations, je pense que les voici <http://priquutrithu.justthetipin.net/xoxrjf>
Affectueusement... bybysait@free.fr

**Comment by Bobysait** [comment]
Salut,

Vous devez voir ces choses incroyables! Je ne pouvais pas croire mes yeux, ce n’est vraiment pas une blague. Jeter juste un coup d'œil <http://prylujeshi.landlord2020.com/xoskd>

Affectueusement... bybysait@free.fr

**Comment by GWRon** [comment]
You should really consider changing the password of your mail account (as "reply by mail" -spam) sounds as if the account was compromised.
And afterwards you should revoke authentification tokens on github and change the password there too.

**Comment by woollybah** [comment]
I'll tidy things up ;-)

**Comment by Bobysait** [comment]
Dear friend! 

I've found some new  stuff recently,  it is really  gorgeous, please take a look here <http://huwyndyce.ballerblogger.com/e6odgqg>

Yours sincerely, bybysait

**Comment by Bobysait** [comment]
Dear friend! 

I've found some new  stuff recently,  it is really  gorgeous, please take a look here <http://huwyndyce.ballerblogger.com/e6odgqg>

Yours sincerely, bybysait

**Comment by Bobysait** [comment]
Hey! 

I just wanted to share some interesting  information with you, here it is <http://phahuntule.dalefranklin.us/e6wkan>


Cheers, bybysait

**Comment by Bobysait** [comment]
Greetings! 

Look at that! Wooow! It's so amazing and interesting, and even sometimes shocking! Just  take a  look  here <http://nkucicrigo.thecornerthree.com/e6lvtio>

Warm regards, bybysait

**Comment by Bobysait** [comment]
Hi! 


We've  been  at a  very  nice  place recently and we  loved it so much, I think it  is just a fantastic place, check it  out <http://nkipriquofri.12800woodside.info/e6knhcyn>

Bests, bybysait

**Comment by Bobysait** [comment]
I removed all the posts, really sorry about that, my account has been (obviously) compromised.
I modified the mail and password.
If anything happens again, just post on BlitzBasic.com, I'll probably see it (while I'm never checking whatever happens on github)
