### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by Tricky1975** [bmx-ng/bcc#204]
I could get Blitz NG compiled for Mac and working without trouble when compiling for mac.

With windows I have a load of trouble and I wonder if they are connected.

- MaxIDE causes an EXCEPTION_ACCESS_VIOLATION during start up
- bmk and bcc ignore me in "pure" Windows (both in Win10 on a real PC and WIN7 on a VM). When I start the programs I just get a plain dosprompt again, and nothing else happens.
- When typing "Wine bcc.exe -v" in Mac though bcc does throw me the version number like it should.
- When compiling the modules for Windows from Mac this is the result: "Cannot find a valid bcc. I am looking for it here : /Volumes/Irravonia/BlitzMAX/NG/bin/bcc.exe" (It worked before, throwing me an error on the modules, but now I get this).

Odd part on bcc not found is this:
~~~
Jeroens-Mac-mini:bin Rachel$ ls /Volumes/Irravonia/BlitzMAX/NG/bin/bcc.exe
/Volumes/Irravonia/BlitzMAX/NG/bin/bcc.exe
Jeroens-Mac-mini:bin Rachel$ wine /Volumes/Irravonia/BlitzMAX/NG/bin/bcc.exe
bcc[ng] Release Version 0.79
Jeroens-Mac-mini:bin Rachel$ 
~~~
Am I missing something here?

**Comment by GWRon** [comment]
EAV:

Have a look if the config file contains odd font sizes (12 comma 00000000 instead of 12 point 00000000).
If so...this is the reason for your crash. Recompile most current MaxIDE from the repos (I commited something for this bug).



BCC:
Did you compile in console mode (...you should do)

Am 14. Juni 2016 19:07:02 MESZ, schrieb Jeroen Broks <notifications@github.com>:

**Comment by Tricky1975** [comment]
> Did you compile in console mode (...you should do)

I did... Or as far as I remember I did... I shall compile it in console mode again to make sure

> Have a look if the config file

No odd things in the config file like that, however, I do wonder, I did (to save space) store both the mac and the windows build in the same folder. Could the mac config be bothering the Windows config? Trying to load a font native to Mac but not to Windows?
(If so I think I can fix it by making the win maxide load its own config file, but altering the source code, right?)

~~~ini
[Options]
language=incbin::default.language.ini
showtoolbar=1
restoreopenfiles=1
autocapitalize=1
syntaxhighlight=1
bracketmatching=1
autobackup=1
autoindent=1
tabsize=4
editfontname=Monaco
editfontsize=12
editcolor=0,0,19
normal_style=255,255,255,0
comment_style=187,238,255,0
quote_style=0,255,102,0
keyword_style=255,255,0,0
number_style=64,255,255,0
matched_style=255,64,64,1
console_style=Monaco,12.000000000000000,255,180,0,5,1,0,2
navi_style=Monaco,12.000000000000000,0,252,0,0,10,0,2
hide_output=0
external_help=0
system_keys=0
sort_code=0
[Defaults]
ide_version=1.44 beta [ng]
prg_quick=0
prg_debug=1
prg_threaded=0
prg_gui=1
prg_verbose=0
prg_platform=0
prg_architecture=0
win_size=28,0,1920,1053
win_max=1
split_position=306
split_orientation=1
cmd_line=
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/maxgui.mod/win32maxguiex.mod/glue.cpp
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/gamejolt.mod/gj.mod/gj.debug.macos.x86.i
file_recent=/Volumes/Irravonia/BlitzMAX/NG/tmp/untitled3.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/getfont.mod/getfont.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/getfont.mod/Import/Import_GetFont.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/getfont.mod/getfont.bmx
file_recent=/Volumes/Irravonia/Projects/BlitzMax/JCR6+/Units/GetFont/GetFont.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/gale.mod/image.mod/GALE_Image.bmx
file_recent=/Volumes/Irravonia/Projects/BlitzMax/JCR6+/GALE/GALE_Image.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/gale.mod/luablopplasma.mod/GALE_LuaBlopPlasma.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/gale.mod/jcr6api.mod/GALE_JCR6API.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/gale.mod/main.mod/GALE.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/gale.mod/keyboard.mod/Key_Name2Code.bmx
file_recent=/Volumes/Irravonia/Projects/BlitzMax/JCR6+/GALE/GALE_MaxLua4Gale.bmx
file_recent=/Volumes/Irravonia/Projects/BlitzMax/JCR6+/GALE/ModifiedMaxLua/Modified_MaxLua_NG.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/gale.mod/hof.mod/GALE_HOF.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/brl.mod/maxlua.mod/maxlua.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/tmp/untitled2.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/gale.mod/maxlua4gale.mod/Modified_MaxLua.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_kthura.mod/kthura_draw.mod/IMPORT_KTHURA_DRAW.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_kthura.mod/kthura_core.mod/IMPORT_KTHURA_CORE.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_ui.mod/tui_core.mod/Import/TUIC_ListBox.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_ui.mod/tui_core.mod/Import/TUIC_Picture.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_ui.mod/tui_core.mod/Import/TUIC_TextInput.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/rpgstats.mod/Import/Import_RPGStats.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/maxgui_initfile.mod/Import/Import_MaxGUI_Initfile.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/specialloadimage.mod/Import/Import_SpecialLoadImage.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/negatief.mod/Import/Import_Negatief.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/blackhole.mod/Import/Import_BlackHole.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/watereffect.mod/Import/Import_WaterEffect.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/trickycircle.mod/Import/Import_TrickyCircle.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/rectangles.mod/Import/Import_Rectangles.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/safestring.mod/Import/Import_SafeString.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/jcr6.mod/zlibdriver.mod/JCR6_ZLIBDRIVER.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/jcr6.mod/tar4jcr6.mod/JCR6_TAR4JCR6.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/jcr6.mod/jcr6webread.mod/JCR6_JCR6WebRead.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/jcr6.mod/jcr6main.mod/JCR6_Main.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/prefixsuffix.mod/Import/Import_prefixsuffix.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/maxgui_input.mod/Import/Import_MaxGUI_Input.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/filepicker.mod/Import/Import_FilePicker.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/console.mod/Import/.bmx/Import_Console.bmx.debug.macos.x86.i
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/dyrtvoid.mod/Import/Import_DyrtVoid.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/blopplasma.mod/Import/Import_BlopPlasma.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/altreadint.mod/Import/Import_altreadint.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/advdatetime.mod/Import/Import_advdatetime.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/tree.mod/Import/Import_Tree.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/trickyreadstring.mod/Import/Import_TrickyReadString.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/tricky_units.mod/stringmap.mod/Import/Import_StringMap.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/tmp/untitled1.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/brl.mod/systemdefault.mod/system.linux.c
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/pub.mod/lua.mod/lua.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/NG/mod/brl.mod/blitz.mod/blitz.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/mod/tricky_units.mod/prefixsuffix.mod/Import/Import_prefixsuffix.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/mod/tricky_units.mod/listdir.mod/Import/Import_ListDir.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/mod/tricky_units.mod/advdatetime.mod/Import/Import_advdatetime.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/mod/gale.mod/keyboard.mod/Key_Name2Code.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/mod/bah.mod/volumes.mod/volumes.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/mod/bah.mod/volumes.mod/main.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/tmp/untitled2.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/tmp/untitled1.bmx
file_recent=/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/mod/brl.mod/audio.mod/audio.bmx
proj_node=Samples|/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/samples||||0|0
proj_node=Modules Source|/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/mod||||0|0
proj_node=BlitzMax Source|/Volumes/Irravonia/BlitzMAX/BruceyBlitzMax/Full/src||||0|0
~~~

**Comment by GWRon** [comment]
Ou could copy the maxidesources to your directory and compile + execute a debug build to see where it segfaults.

**Comment by GWRon** [comment]
> I just get a plain dosprompt again, and nothing else happens.

This is what happens if you compiled as "GUI"-programme (non-console).


> When compiling the modules for Windows from Mac this is the result: `Cannot find a valid bcc. I am looking for it here` [...]

This line is printed as soon as BMK(NG) was not able to execute the process (running "bcc.exe")
This might be connected to your other issue (not getting the version string on execution of "bcc -v")

Let's wait what happens if you do a recompile in "non-gui"-mode

**Comment by Tricky1975** [comment]
Recompiled bmk and bcc. It may indeed seem I forgot to set the compiler to console as they do output standard stuff when I just call them now.

When cross-compiling from Mac, it sill get the message that bcc.exe could not be found (which really cannot be, because it DOES exist, and if you copy and paste the filename it tries (and fails) to look for in the unix prompt with the "ls" command my claim on this one will be confirmed.

Trying to use Windows itself to build the modules resulted into THIS:
![image](https://cloud.githubusercontent.com/assets/11202073/16070332/dbb6038a-32d4-11e6-8fe0-3f7d29438f43.png)

(MMODS.BAT will just define the MINGW environment vars and then start bmk with the "makemods" parameter).

trying to run maxide.debug.exe in my VM took forever, so maybe I gotta try that another time on a "real" Windows PC.

**Comment by woollybah** [comment]
These aren't really "Windows" issues. More that you are trying to build Windows stuff on OSX directly with Wine.

> I wonder, why does bcc call mingw in the UNIX way
Perhaps you have "config.bmk" in your bin directory - it is for cross-compiling with MinGW - Where you have a Mac/Linux version of MinGW on your system and use that to make Windows binaries.

You will find things will work much, much better if you use a VM instead.

**Comment by GWRon** [comment]
@ MinGW environment
Just put the MinGW of choice into "i:\BlitzMax\NG\MinGW32" and it will be found regardless of your MinGW-environment variables. This works for vanilla too, if you use Bruceys BMK (of course a current version).

**Comment by Tricky1975** [comment]
I never knew about copying MinGW to BlitzMax had this effect. Does the "vanilla" MaxIDE also detect this, so I can build modules in the IDE then?

> You will find things will work much, much better if you use a VM instead.

Yeah, it would only save me time if I could do this through wine. I shall try if removing/renaming config.bmk solves the "unix" style of calling mingw

**Comment by Tricky1975** [comment]
Update:
- I now placed all Windows stuff in a separate folder
- MaxIDE no longer crashes in loading as a result 
- I renamed config.bmk to config.bmk.mac (in the windows folder) and then it worked until ....

![image](https://cloud.githubusercontent.com/assets/11202073/16086387/a248ec02-331f-11e6-807d-22cbd8caba92.png)

**Comment by woollybah** [comment]
The current build does not exibit these issues.
