### ISSUE TITLE
Mixing array datatypes - produce a warning, error, or silent?

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#206]
Hiya,

Just wanted to mention that this little snippet doesn't create the arrays, they end up as Null arrays without any notification from the compiler. I noticed that mixing up variables of signed/unsigned type gives a nice compiler warning, maybe give a similar warning for arrays too as opposed to a 'potential regression issue creating' error?

```
Const Value:UInt = 10
Local Values:Int[] = [Value]
Local LongValues:Long[] = [Value]
```

Cheers!

**Comment by GWRon** [comment]
It is not only for the newly introduced datatypes:

```BlitzMax
SuperStrict
Framework Brl.StandardIO

Global arr:Int[] = ["hi"]
```

vanilla:
```
Compile Error: Unable to convert from 'String Array' to 'Int Array'
```

NG:
```
Building untitled1
[ 97%] Processing:untitled1.bmx
[ 98%] Compiling:untitled1.bmx.gui.release.linux.x86.c
[100%] Linking:untitled1
```

**Comment by GWRon** [comment]
It seems a proper fix would be to:

replace `expr.bmx Line 1306`
```BlitzMax
				If TArrayType(ty).dims = TArrayType(src).dims Then
						exprType = ty
				End If
```

with
```BlitzMax
				If TArrayType(ty).dims = TArrayType(src).dims Then
					if ty.EqualsType(src)
						exprType = ty
					endif
				End If
```
This should change behaviour to "BlitzMax vanilla". As vanilla does not allow casting autofilled arrays. So the only thing accepted after this change:
```BlitzMax
arr:object[] = [objectA, null, "string is object like"]
arr:string[] = ["test"]
arr:int[] = [1,2,3]
```

What is still missing (but another error):
```BlitzMax
'case 1
Global arr:String[] = ["test", Null]
'case 2
Global arr2:String[] = [Null]

```

__case 1__
vanilla: `Compile Error: Auto array element has no type`
NG: "compiles"

__case 1__
vanilla: `Compile Error: Auto array element has no type`
NG: `Internal Error.`

**Comment by GWRon** [comment]
Another option regarding "auto array element" is during the parsing-phase:

Either have "TArrayType" contain "field containsNull:int" (properly setup'd then) or give access to the elements, so that BCC could check individually if it contains a NULL-entry.

For the second option: There is surely a better option but I am not Brucey, so I will leave it up to him to come up with a smarter approach. It justs needs the ability to access the "args[]"-array of the expression in that line.

**Comment by davecamp** [comment]
They seem like good suggestions to me. I would think that as this is a semanting issue then keeping any checks away from the parser itself would be more appropriate, and I'd personally semant the type of every element in a rhs 'auto array' against the lhs declaration type.

It's always interesting to see what Brucey comes up with :o)

**Comment by GWRon** [comment]
Like assumed: Bruce comes up with a way more elegant solution. I just did not see that "exprs"-approach to check for varying types - but that is why Brucey is the "mastermind" here, not one of us :-)

**Comment by davecamp** [comment]
He most certainly does :p

For discussion...
Is it possible to evaluate constant numeric literals and check if their value falls within the 'type range' and auto assign them to the correct type if needed?
For example...

    Const ui:UInt = 20
    Local Array:UInt[] = [ 0,1,2,3,4,5, ui, 6, ui ]

would cause an 'auto elements must have identical type' error, and would need to be rewritten as 

    Local Array:UInt[] = [ 0:UInt,1:UInt,2:UInt,3:UInt,4:UInt,5:UInt, ui, 6:UInt, ui ]

which kind of uglifies the things a little.
As the values are constants then assigning from an unsigned to its signed version could also be checked to make sure that value is within its 'signed range' and either issue a warning or generate an error. Or would others prefer to keep it is as is?

**Comment by GWRon** [comment]
I too think that sometimes the compiler should be a bit more gentle and helpful to the developer.

My "simple" approach would be to allow everything to get "autocasted", if it does not change the resulting value: `if string(originalValue) = string( uint(originalValue) ) then print "autocast ok";result = uint(originalValue)` 

Of course this only would work for the basic numeric types and not complex objects.

**Comment by woollybah** [comment]
> Is it possible to evaluate constant numeric literals

Yes. It can probably be made a little more intelligent than it currently is.

**Comment by davecamp** [comment]
Sounds cool!
Is it something that you would look into to implement? Or not just yet? I understand there are probably more pressing issues so there's no rush - after all... we've had it this way with the legacy compiler for over a decade :p
Thanks!

**Comment by woollybah** [comment]
Well, I've already implemented something similar for function args, so there shouldn't be too much work to apply the same ideas to "auto" arrays.

**Comment by davecamp** [comment]
Sounds good.
Thanks for looking in to it!
