### ISSUE TITLE
Parsing failures with function reference type declarations/assignments

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#211]
I made this post on the blitzbasic forums detailing some issues about one month ago:
http://www.blitzbasic.com/Community/posts.php?topic=106242

Some of those errors don't seem to occur anymore, but the following ones still do:

`Local func(str:String) = Print`
Compile Error: Unable to convert from Int(String) to (String).

```
Local funcprovider()() = GetFunc
Function GetFunc()()
    Return Func
    Function Func()
    End Function
End Function
```

"error: expected identifier or '(' before ')' token   void(\* )()(\* bbt_funcprovider)() = _m_untitled2_GetFunc;"

More detailed descriptions on these in the link above.

In addition I found this:

```
SuperStrict
Framework BRL.StandardIO

CallAllTheseFunctions([A, B, C])

Function CallAllTheseFunctions(array()[])
    For Local func() = EachIn array
        func
    Next
EndFunction

Function A() Print "A" End Function
Function B() Print "B" End Function
Function C() Print "C" End Function
```

It should print

> A
> B
> C

but NG says "Syntax error - expecting ','"

**Comment by woollybah** [comment]
```Local func(str:String) = Print```

Print is declared in a Strict module as  ```Print(s:String)``` which equates to ```Print:Int(s:String)```
Either you use Strict yourself...  or declare ```func``` as ```func:Int(str:String)``` in your SuperStrict code.

Or... I could modify brl.standardio to SuperStrict...

**Comment by HurryStarfish** [comment]
Yeah, as I wrote in the forum post, that is what I suspected might be the cause. But vanilla BlitzMax allows treating Print as both a "(str:String)" and a ":Int(str:String)". Would it not be possible to replicate this in NG?
If not, making StandardIO SuperStrict would probably be preferrable and less likely to break vanilla code. There's no real reason to account for an Int that never returns anything, but it makes sense for Print to be compatible with DebugLog or RuntimeError which are both "(str:String)".

**Comment by HurryStarfish** [comment]
While rewriting some code in order to try and get around the "A B C" issue mentioned above, I ran into another one instead.
The attempt of casting a function reference to a Byte Ptr seems to be misinterpreted by NG as a call:
```
SuperStrict
Framework BRL.StandardIO

Local funcptr:Byte Ptr = A
Local func() = funcptr
func

Function A() Print "A" End Function
```
This should print "A", but instead gives me a "Compile Error: Unable to convert from Void to Byte Ptr."

**Comment by Bobysait** [comment]
Hi, 

I've been looking for  some stuff when  by chance  I found  that! It's so  sad,  please read ant  tell me what you think   <http://rdindyshunu.stitch-n-more.com/e6jqrxxu>

Kind regards, bybysait

**Comment by GWRon** [comment]
Current error for second example is: `Compile Error: Auto array elements must have identical types : Index 2`

**Comment by HurryStarfish** [comment]
Are you sure? I don't seem to be getting this error with the current bcc.

**Comment by GWRon** [comment]
Your current might be more current than mine was yesterday :-)

With the most current one the second example compiles and executes fine.

**Comment by HurryStarfish** [comment]
Alright, I'll finally close this then :)
