### ISSUE TITLE
'! native c support - and spanish comments

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#212]
Just recognized that a comment in my code made the new BCC fail:

```BlitzMax
		'!!!!
		'attention: LOAD PERSONS FIRST !!
		'!!!!
```

`Compile Error: Expecting expression but encountered '!'`

While this is something I am able to change easily, I thought of people speaking Spanish - they use their exclamation marks at the begin. So they might more often have comments starting with "!".

Maybe make it even more "rare" by using __'!:__ or so?

Just a thought, no bug report!

**Comment by woollybah** [comment]
And there was me thinking ```'!``` was quite obscure.

I would have preferred not to put it in comments at all, but MaxIDE sees the source and tries to format it otherwise - which is somewhat annoying.
