### ISSUE TITLE
Error building MaxGUI - Windows

### ISSUE THREAD

**Issue by eagle54** [bmx-ng/bcc#214]
See http://www.blitzbasic.com/Community/post.php?topic=105537&post=1311696

When i want to rebuild MaxGUI Mod, i have this error :

[ 93%] Processing:hyperlink.bmx
[ 94%] Processing:scrollpanel.bmx
[ 94%] Processing:splitter.bmx
[ 95%] Processing:win32maxguiex.bmx
Compile Error: Auto array elements must have identical types
[C:/BlitzMax/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.bmx;4759;0]
Build Error: failed to compile C:/BlitzMax/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.bmx
C:\BlitzMax\mod>

It's the same thing with Warning Flag On (Build Options)

Any suggestions?

[edit]
Split into two separate issues. See #217 for other issue.

**Comment by GWRon** [comment]
Debugger-information is also mentioned in #213 

@ win32maxguiex

The corresponding line `Local Rect[] = [_item,0,0,0]` mixes 3 bytes/shorts/integers with `_item` which is in this type defined as `Field	_item:Byte Ptr		'HTREEITEM`.

**Comment by eagle54** [comment]
1/ Ok for debugger-information mentionned (i didn't saw issue #213)

2/ About win32maxguiex, is there a fix for bcc or for maxgui (keep the compatibility with bmax legacy v1.50)?
Thanks for your answer

**Comment by GWRon** [comment]
Maybe Brucey comes up with a "fix".

Maybe it is better to fix maxgui instead, as I would interpret `Local Rect[]` as "Local Rect:int[]`. So I would assume, `_item` to be of type __int__ too - which is not the case.

**Comment by woollybah** [comment]
Should be working now.
