### ISSUE TITLE
Structs won't compile

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#218]
I saw issue #209 and decided to try out the example code given there. Since the issue is marked as closed, I assume the code given there is supposed be valid. But it turns out that trying to compile any Struct declaration, even an empty one, seems to result in an error in the generated C code:
```
SuperStrict
Framework BRL.Blitz

Struct S
End Struct
```

> error: 'BBDEBUGSCOPE_USERSTRUCT' undeclared here (not in a function)
>   BBDEBUGSCOPE_USERSTRUCT,
>   ^

**Comment by woollybah** [comment]
Do you have the latest brl.mod ?

**Comment by HurryStarfish** [comment]
...
I did, in fact, not. I guess I got used to regarding modules as "additional BlitzMax code" and forgot that some of the BRL modules can be ...kinda important for core language features.
Sorry about that.

**Comment by HurryStarfish** [comment]
One more question though: Since trying to add a Delete() method to a Struct results in a somewhat unwieldy error message, am I correct in assuming Structs are not intended to support destructors? 
I guess it's not exactly important that they support them, or even that it produces "nice looking" error, just thought I'd ask to make sure.

**Comment by woollybah** [comment]
Structs are not managed (by the GC), since they are just basic C structs on the stack (rather than allocated memory on the heap), so the idea of a "finalise"/delete method doesn't make much sense.

The New() constructor doesn't actually create a new instance of a struct, but is useful as a familiar (in as much as Types have them) method, for example, for initialising data.

I can certainly prevent the creation of Delete() method on Structs.

**Comment by HurryStarfish** [comment]
Ah well, I thought a parameterless New() method in Structs, if defined, would automatically get called whenever a struct instance is "created", like from the declaration of a local variable. So I imagined Delete getting called when the variable is about to get overwritten or go out of scope.
I don't know if something like that would actually be feasible or useful for anything though...

**Comment by davecamp** [comment]
Or you could keep Delete in structs which would allow some RAII ? For those that go low level this is quite handy no?
