### ISSUE TITLE
"Invalid debug typetag"

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#220]
This might or might not be related to #211, but since this one is not a compile error, I thought it might be better to open it as a separate issue.
```
SuperStrict
Framework BRL.StandardIO

Local a() = F
DebugStop

Function F() Print "asdf" End Function
```
If compiled in debug mode, this produces a
> Debugger Error:Invalid debug typetag: 

when execution reaches the DebugStop.

**Comment by davecamp** [comment]
You could add

    If Not tag.length Return ""

to brl.mod/debugger_mt_stdio.bmx @ line 190 just before the **DebugError "Invalid debug typetag:"+t** line.

It should then take care of function pointers with zero parameters.

**Comment by woollybah** [comment]
Recent update to brl.appstub fixed this.
