### ISSUE TITLE
Some *Struct* questions

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#224]
Hiya,

I'm in the process of changing the vulkan code over to use Structs so it can stay away from the GC.

A couple of questions...
a. SizeOf doesn't seem to work on Structs.
~~b. If I have a Struct that contains Field Structs, the parent struct has just pointers to the inner ones, is that to be expected?~~

Example code that doesn't compile

    Strict
    Struct Test
    	Field f0:Float
    	Field f1:Float
    	Field f2:Float
    	Field f3:Float
    EndStruct

    Local T:Test
    
    Print SizeOf( Test )
    Print SizeOf( T )

**Comment by davecamp** [comment]
Ooops, I made a mistake with question b. above :/
I meant an array of Structs... If I have an array of Structs then the array holds pointers to the individual Structs. my apologies.

**Comment by woollybah** [comment]
a. is a bug.
b. arrays in structs are not currently implemented - at least in the form I intend them to be - i.e like a normal C array embedded in the struct.

If you are talking about a general array with Structs in it, that should be flat structs, and not pointers to - in which case that would be a bug too. (I was sure I had tested that recently...)

**Comment by davecamp** [comment]
Ahh ok, in that case this could be an issue then

    Strict
    Struct Test
    	Field f0:Float
    	Field f1:Float
    	Field f2:Float
    	Field f3:Float
    	Field f4:Float
    EndStruct

    Local array:Test[3]
    DebugStop

In the debugger I get...

    Local array:Test[] = $00000000028a13f0
    	+ [0]=$000000000281410
    	+ [1]=$000000000281414
    	+ [2]=$000000000281418

Note that this is from an x64 build.
It doesn't seems to matter on the number of Fields in the 'Test' struct itself. I noticed this when using Structs that are over 500 bytes each in size in each array index.

**Comment by davecamp** [comment]
Funnily enough I took a punt and just ran the code. It seems to work during a call from a vulkan function that expects an array of structs as one of its parameters to output into - ie the function puts data into an array that you provide. So this could just be a red herring caused by the debugger?

I'll carry on and build up a basic example to see if its working as expected.

**Comment by woollybah** [comment]
Yes, it might just be a debugger display issue with arrays of structs.

**Comment by davecamp** [comment]
Everything looks good :-)
I'm still in the process of getting an example up and running, but everything is initialising as expected, so yeah, just an with the debugger.

Using structs also makes the code much much tidier. Instead of using MemAlloc, MemCopy and MemFree to copy stuff across language constructs I can pass in an array of structs and that its, done.

A great job!!

**Comment by woollybah** [comment]
Just tested the array issue.
It appears to work for me.

My Array entries have the address plus ```@Test``` on the end.
```
+ [0]=$000000000281410@Test
```
and also allows you to expand the node to show the Struct contents.

Do you have the latest of everything? (bcc/brl.mod). Specifically, it's the appstub module which handles this for the debugger.

**Comment by davecamp** [comment]
Thanks for the fast fix!!
I've not updated just yet due to a busy past few days. Will post back...
