### ISSUE TITLE
Defining inf or nan Globals or Constants in modules lead to invalid .i files

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#226]
A somewhat exotic issue:
I have a module that contains these lines:
```
Const INFINITY   :Float    =  1:Float / 0:Float
Const NEGINFINITY:Float    = -1:Float / 0:Float
Const NAN        :Float    =  0:Float / 0:Float
```
Trying to compile the module results in an error that looks like this:

> Compile Error: Syntax error - expecting identifier.
> [C:/Programmierung/BlitzMax-NG/mod/fbf.mod/numutils.mod/numutils.debug.win32.x86.i;11;0]

Changing these Consts into Globals turns the error into this:

> C:/Programmierung/BlitzMax-NG/mod/fbf.mod/numutils.mod/.bmx/numutils.bmx.debug.win32.x86.c:52:26: error: initializer element is not constant
>  BBFLOAT fbf_numutils_NAN=bbNEGNANf;

**Comment by HurryStarfish** [comment]
Okay, actually even vanilla BlitzMax shows very weird behavior with NaN values, module or not ("nan" vs. "-1.#IND0000" when printed, IsNan returning 1 or 0, depending on whether theyre stored in a Const or a Local/Global), so maybe it's best to just avoid them as much as possible...

**Comment by woollybah** [comment]
Const and global inf/nan are now working with the latest bcc and brl mod.
