### ISSUE TITLE
Metadata ignored in certain situations

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#230]
I am still trying to create a short example but am still failing.

In my game I use Brucey's Persistence.mod but am skipping all "Fields" containing `{nosave}`-Meta-Data.

While this works with vanilla, it fails for some objects when compiled with NG. So for some types it correctly finds that metadata, but for other ones it does not find them.

If you have access to it: Download the TVTower sources, build a 64bit variant and save a game via "s". It saves function references stored in the field "_onRunMatch" - which has the meta-data `{nosave}`.

I guess it has something to do how things get imported (a imports b, b imports c ...) and maybe how they are stored (field defined with "base" but assigned is an "extended" instance)

**Comment by GWRon** [comment]
So: where to look in the generated .c-files if they contain "valid" meta data or if that is already missing?

**Comment by woollybah** [comment]
I tried it, and I can't find _onRunMatch in my saved xml. What type does it belong to?

**Comment by GWRon** [comment]
It is stored in TNewsEventSportLeague which is in game.newsagency.sports.bmx

Maybe it is only faulty in my older bcc..as the most current fails to finish compiling modules here I use the one before operator overloading was added

**Comment by GWRon** [comment]
Hmm I use the bcc before the "class global order" commit. Maybe that one fixed it already. Just am not on my computer to test. Will report tomorrow if that already fixed that issue

**Comment by woollybah** [comment]
The following example runs the same for NG and legacy...

app.bmx
```blitzmax
SuperStrict

Framework brl.standardio
Import brl.reflection

Import "meta_1.bmx"

Local r:TRoundedBox = New TRoundedBox

Local t:TTypeId = TTypeId.ForObject(r)

While t

Print "*" + t.Name()


For Local f:TField = EachIn t.Fields()

	Print f.name() + " : " + f.MetaData()

Next

	t = t.SuperType()

Wend
```
meta_1.bmx
```blitzmax
SuperStrict

Import "meta_2.bmx"

Type TRoundedBox Extends TBox

	Field corner:Int {nosave}

End Type
```
meta_2.bmx
```blitzmax
SuperStrict


Type TBox

	Field x:Int { nosave }
	Field y:Int { nosave }
	Field w:Int { nosave }
	Field h:Int { nosave }

End Type
```

**Comment by woollybah** [comment]
How do I get TNewsEventSportLeague into my save game?

**Comment by GWRon** [comment]
That example looks similar to what I have tried too..without success.

@ savegame
i started a new game and pressed "s".
as the soccer simulation is started on game start, the savegame should contain it then already.

**Comment by woollybah** [comment]
Okay. I've got it too.
