### ISSUE TITLE
Function pointers in Structs

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#231]
Hiya,

I get a compile error when using this kind of arrangement for a Struct, it compiles and works as expected for a Type.
I've cut the example down to it bare bones

    
    Struct Funcs
    	Field funcptr:Int()
    	Field factoryfuncptr:Byte Ptr(inst:Byte Ptr, pFuncName$z)
    	
    	Method Init()
    		funcptr = factoryfuncptr("x","Test")
    	EndMethod
    EndStruct
    
    Rem
    Type tFuncs
    	Field funcptr:Int()
    	Field factoryfuncptr:Byte Ptr(inst:Byte Ptr, pFuncName$z)
    	
    	Method Init()
    		funcptr = factoryfuncptr("x","Test")
    	EndMethod
    EndType
    EndRem

EDITED:
Of course the error message would be of help too ;-)

Building untitled1
    [ 97%] Processing:untitled1.bmx
    [ 98%] Compiling:untitled1.bmx.gui.release.win32.x64.c
    C:/BlitzMaxNG/tmp/.bmx/untitled1.bmx.gui.release.win32.x64.c: In function '__m_untitled1_Funcs_Init_i':
    C:/BlitzMaxNG/tmp/.bmx/untitled1.bmx.gui.release.win32.x64.c:25:43: error: conversion to non-scalar type requested
  o->__m_untitled1_funcs_funcptr =((struct _m_untitled1_Funcs)o)->__m_untitled1_funcs_factoryfuncptr(bbt_,bbt_2);
                                               ^
    Build Error: failed to compile C:/BlitzMaxNG/tmp/.bmx/untitled1.bmx.gui.release.win32.x64.c
    Process complete

**Comment by woollybah** [comment]
Thanks. It appears to be generating ```((struct _m_untitled1_Funcs)o)``` incorrectly for a struct. Probably doesn't need a cast a all, there.

**Comment by woollybah** [comment]
Appears to be [this line](https://github.com/bmx-ng/bcc/blob/2da4d25c61d04b14c34cc27dd2a1416edb048c8b/ctranslator.bmx#L1160).

A quick hack might be something along the lines of...
```blitzmax
Local obj:String
If TClassDecl(scope) And Not TClassDecl(scope).IsStruct() Then
	obj = Bra(TransObject(decl.scope))
End If
```

I'll sort it out tonight 🍵

**Comment by davecamp** [comment]
No probs, cheers!
