### ISSUE TITLE
Failing to resolve interface calls

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#235]
There is an issue where calls to methods of multiple inherited interfaces is not resolving correctly.

The following example should output
```
A
B
C
```

```blitzmax
SuperStrict

Framework BRL.Standardio


Local test:TTest = New TTest

Local obj:TObj = test.doA().doB().doC()



Interface IA

	Method doA:IB()

End Interface

Interface IB

	Method doB:IC()

End Interface

Interface IC

	Method doC:TObj()

End Interface


Type TObj
End Type


Type TTest Implements IA, IB, IC

	Method doA:IB()
		Print "A"
		Return Self
	End Method

	Method doB:IC()
		Print "B"
		Return Self
	End Method

	Method doC:TObj()
		Print "C"
		Return New TObj
	End Method

End Type
```
```bbObjectInterface()``` does not appear to be generated in these cases.

**Comment by bornd37** [comment]
Interestingly if I split Local obj:TObj = test.doA().doB().doC() up into 3 calls:
`Local a:IB = test.doA()
Local b:IC = a.doB()
Local c:TObj = b.doC()
`
it outputs A, B, C as expected.
