### ISSUE TITLE
Illegal instruction in blitz.mod/blitz_string.c

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#237]
Dunno if this is a "bcc" thing or not:

- fetched most current bcc and bmk
- built the binaries, copied them (and core make config .bmk)
- fetched most current brl.mod pub.mod sdl.mod
- rebuilt all modules 
- rebuilt my sample code (and therefore framework files)

I tried to update my Dig-framework samples and did a "NG 64bit debug test compile":

```
$ gdb -r bitmapfont.debug
[...]
Starting program: /home/ronny/Arbeit/Programmieren/Projekte/Dig.git/samples/bitmapfont/bitmapfont.debug 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff550f700 (LWP 19846)]
[New Thread 0x7ffff4d0e700 (LWP 19847)]
[New Thread 0x7ffff450d700 (LWP 19848)]

Program received signal SIGILL, Illegal instruction.
0x0000000000691978 in bbStringFromBytes (n=20, p=0x6fd4f5 "BlitzMax Application")
    at /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/mod/brl.mod/blitz.mod/blitz_string.c:190
190		for( k=0;k<n;++k ) str->buf[k]=(unsigned char)p[k];
(gdb) bt
#0  0x0000000000691978 in bbStringFromBytes (n=20, p=0x6fd4f5 "BlitzMax Application")
    at /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/mod/brl.mod/blitz.mod/blitz_string.c:190
#1  bbStringFromCString (p=p@entry=0x6fd4f5 "BlitzMax Application")
    at /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/mod/brl.mod/blitz.mod/blitz_string.c:235
#2  0x000000000068f022 in bbStartup (argc=argc@entry=1, argv=argv@entry=0x7fffffffdf88, dummy1=dummy1@entry=0x0, 
    dummy2=dummy2@entry=0x0) at /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/mod/brl.mod/blitz.mod/blitz_app.c:394
#3  0x0000000000406988 in main (argc=1, argv=0x7fffffffdf88)
    at /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/mod/brl.mod/appstub.mod/appstub.linux.c:16

```

Ideas what could be wrong?

**Comment by GWRon** [comment]
It does not happen in other samples - so I think it is not a generic "brl.mod"-error.

**Comment by GWRon** [comment]
might it be related to the MSSE issue? My CPU is newer and should support these simd extensions

**Comment by GWRon** [comment]
Ok, replacing "msse4" in make.bmk fixes this too:

So it is related to: bmx-ng/bmk/issues/29

**Comment by GWRon** [comment]
Undo-ed all changes, hit compile (non-quick) again and it still worked.

So:
- it did not work
- I replaced "msse4" with "msse3" and hit compile: worked
- I replaced "msse3" with "msse4" (undo) as I built for 32bit and this should never be triggered then: still worked

Cannot explain why this happens ?!

**Comment by woollybah** [comment]
Perhaps just a clean/rebuild fixed something.

**Comment by GWRon** [comment]
I did clean builds for every try - but maybe it is a similar issue to what I have with certain filenames "crashing" every second build (which is related to the AMD GPU drivers on my linux box).

I meanwhile mailed you another issue - an issue I am not able to condense into a small example.

**Comment by woollybah** [comment]
Can I close this? 🐹

**Comment by GWRon** [comment]
Yes. You could.
