### ISSUE TITLE
{} not allowed as meta data

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#253]
Extremely minor annoyance, but came up in one of my projects:
```
Type T {}
End Type
```
brings up the slightly amusing message "Compile Error: Expecting '}' but encountered }"

**Comment by GWRon** [comment]
I created a PR to fix that "annoyance". Current code ate at least one character until it had a look for the closing curly bracket.. Bringing the check from bottom to top fixes that issue. Its the typical "Repeat until" vs "While Wend" thing.

**Comment by woollybah** [comment]
Fixed.
