### ISSUE TITLE
Confusion between method overriding/overloading.

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#254]
This code should be valid as the two methods have different parameters and are thus overloads of each other, but it produces a compile error:
```
SuperStrict
Framework BRL.StandardIO

Type T1
	Method M:Int Ptr(i:Int)
		Print "T1.M"
	End Method
End Type

Type T2 Extends T1
	Method M:String(f:Float)
		Print "T2.M"
	End Method
End Type
```
NG seems to mistake the overload for an override, because moving both of the methods into the same class works as expected.

On the other hand, the following code compiles but shouldn't:
```
Type T1
	Method M:Int(i:Int)
		Print "T1.M"
	End Method
End Type
Type T2 Extends T1
	Method M:Float(i:Int)
		Print "T2.M"
	End Method
End Type
```
The parameter lists of both methods here are identical, so this is not an overload. In vanilla, declaring an overriding method/function with a different return type than the "original" is only ever allowed if it is a more derived type; since there is no inheritance between numeric primitives, the above shouldn't be allowed.

**Comment by GWRon** [comment]
Your second ("on the other hand") example does not work on vanilla while this does:
```BlitzMax
SuperStrict

Type T1
	Method M:T1(i:Int)
		Print "T1.M"
	End Method
End Type
Type T2 Extends T1
	Method M:T2(i:Int)
		Print "T2.M"
	End Method
End Type
```
So you could override and adjust the return type as long as the overridden one is a descendant of the original return type. So In my case "T2 extends T1" which is why you could use T2 as overridden return type.

So as Ints could get casted to Floats without "loss"  - maybe this is why NG allows it ("auto-castability") ?

**Comment by HurryStarfish** [comment]
Yes, as I said in my last sentence above - it is indeed allowed in vanilla if, _but only if_, you specify a decencant type. But primitives don't inherit from each other; allowing this for them would require actual type conversion which would lead to all kinds of potential problems.
Ints can _not_ be cast to Floats without loss, for example. Take this example code:
```
SuperStrict
Framework BRL.StandardIO

Local i1:Int = 2111111111
Local f:Float = i1
Local i2:Int = f
Print i1
Print i2
```
If the conversion was lossless, you would expect to see the same number twice. Instead, the output I am getting is
> 2111111111
> 2111111168

**Comment by GWRon** [comment]
Oh I see, Just wondered why range of numbers listed on wikiboooks was higher for floats while also being 32bit (and somewhere has to be a "loss of accuracy").

And Sorry for the double-explanation of the "descending return types" I somehow missed your last paragraph.


In type.bmx TFloatType is set to return true on `ExtendsType()` when comparison is of Type `TNumericType` (which is true for `TIntegralType` - and then also for `TIntType`).
So this sounds as if the check validates the override as "Float extends Int" for BCC-NG. At least if I did not get this wrong too.

**Comment by GWRon** [comment]
I do not know for what `ExtendsType()` is used all over the code. But maybe it is also used as a kind of `CompatibleToType()`-like thing. So BCC checks if things could work together (int -> float, float -> int, int->string ...). But in a strict sense they are not "Extending" from each other. If so, it might be better to introduce a new helper method (like the suggested `CompatibleToType()`) and only return true for `ExtendsType()` when really extending from the given type.
