### ISSUE TITLE
"Redefinition" error with nested functions

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#255]
```
SuperStrict
Framework BRL.StandardIO

Type T
	Function F1()
		Function G()
		End Function
	End Function
	
	Function F2()
		Function G()
		End Function
	End Function
End Type
```
This fails with an "error: redefinition of '_m_untitled35_T_F1_v_G_v'" from GCC.

**Comment by GWRon** [comment]
You seem to have a bug-finder-run today ;-)

Parser.bmx contains this lines:
```BlitzMax
			' nested function - needs to get added to the "module"
			Case "function"
				_block.InsertDecl ParseFuncDecl( _toke,FUNC_NESTED)
```
Without having a further look now I assume they do not "prepend" the class-function-... chain to their name and this creates the redefinition.

**Comment by HurryStarfish** [comment]
> You seem to have a bug-finder-run today ;-)

Yes, I plugged a larger project I had lying around into NG, now that the function pointer issues that prevented me from doing so are out of the way, and all of these came up as a result :>

Except #248, which I found from [this](http://www.blitzbasic.com/Community/posts.php?topic=107727). You were asking about the auxillary data of array objects, and the answer is that it is stored "in front of" the actual contents. For instance, you can do `Local l:Int = (Int Ptr [99,99,99])[-1]` as an equivalent to `Local l:Int = [99,99,99].Length`, or at least you could if it wasn't currently broken ;)

**Comment by GWRon** [comment]
Yes this is surely a "nifty trick" but as "nifty" sounds already suspicious it is something which just "works out of luck".

So I am not sure if this stills works with NG on a 64bit system (with int-arrays longer than the 32bit-limit). It is imho the same as relying on the "32bit nature" of numbers in BlitzMax... which is not the case for NG.

**Comment by HurryStarfish** [comment]
blitz_array.h defines BBArray like this in vanilla:
```
struct BBArray{
	//extends BBObject
	BBClass*	clas;
	int			refs;

	const char* type;			//8
	int			dims;			//12
	int			size;			//16 : total size minus this header
	int			scales[1];		//20 : [dims]
								//sizeof=20+dims*sizeof(int)
};
```
and like this in NG:
```
struct BBArray{
	//extends BBObject
	BBClass*        clas;

	const char*     type;       //
	unsigned int    dims;       //
	unsigned int    size;       // total size minus this header
	unsigned short  data_size;  // size of data element
	unsigned short  data_start; // start offset of data
	int    scales[1];  // [dims]
};
```
, so it *should* work ... as long as your arrays are one-dimensional and a C int is 32bits on your particular system. Needless to say, this is not a clean way of doing things ;)

**Comment by woollybah** [comment]
Well, data starts 16-byte aligned, so YMMV.
