### ISSUE TITLE
Cannot create "new self"-instance (Regression)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#257]
f3e6c3dea9f806ad873f8ea542fe73557f4aa9a7 (_Improved handling of Self_) introduced a new bug:

The following code is no longer possible (while valid in vanilla):
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Type TTest
	Method Copy:TTest()
		Return New Self
	End Method
End Type

Local c:TTest = New TTest.Copy()
```

```
Compile Error: Unable to convert from Type to TTest.
```

It should actually return a new instance of the type "self" corresponds to.

**Comment by HurryStarfish** [comment]
I realize this is not possible in vanilla, but actually, why not allow Self to be used as a type in general? Being able to write `Method Copy:Self()` or `Local n:Self` could make code independent from the name of the class that contains it (and maybe save a bit of typing) ... or is there a certain reason why this should not be allowed?
