### ISSUE TITLE
Function pointer call convention...

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#259]
Hiya,
 I just updated bcc, bmk, brl.mod and pub.mod, tried rebuilding all of the modules on a windows unit and it seems that function calling conventions aren't being ~~parsed~~ handled correctly. I'm getting errors with Global and Field function pointers that have a call convention specified - ie "Win32" in the modules.

**Comment by woollybah** [comment]
Should be fixed now, but if you have any more issues with it, let me know!
