### ISSUE TITLE
Interface issue: "Attempt to call abstract method"

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#265]
```
SuperStrict
Framework BRL.StandardIO

Interface I
	Method M()
End Interface

Interface I2 Extends I
End Interface

Type T Implements I
	Method M()
		Print "M"
	End Method
End Type

Type T2 Extends T Implements I2
End Type

Local x:I2 = New T2
x.M
```
I am also getting an error equivalent to `Identifier 'm' not found` from a larger piece of code, which I haven't yet managed to replicate using a short example; I assume it's caused by the same bug.

**Comment by woollybah** [comment]
Looks like the vtables for T2 are incorrectly referencing the interface method stub, rather than T's implementation of it.
