### ISSUE TITLE
Implementing interface method fails with derived return type

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#269]
Since methods from a base class can be overridden with a more derived return type, the same thing should be allowed when implementing methods from an interface:
```
Interface I
	Method M:Object()
End Interface

Type T Implements I
	Method M:String()
	End Method
End Type
```
Additionally, it would be helpful if NG were to verify the compatibility of the methods in an interface hierarchy, to make sure that there are no two methods with same same name and parameter list but with unrelated return types. For example, the interface I3 in this code can never be fully implemented, so it should not be allowed in the first place:
```
Interface I1
	Method m:String()
End Interface

Interface I2
	Method m:Int()
End Interface

Interface I3 Extends I1, I2
End Interface
```

This, however, being analoguous to the first code example, should still be allowed:
```
Interface I1
	Method m:String()
End Interface

Interface I2
	Method m:Object()
End Interface

Interface I3 Extends I1, I2
End Interface
```
and so should this:
```
Interface I1
	Method m:I1()
End Interface

Interface I2
	Method m:I2()
End Interface

Interface I3 Extends I1, I2
	Method m:I3()
End Interface

Type T Implements I1, I2
	Method m:T()
	End Method
End Type
```

**Comment by HurryStarfish** [comment]
It's not perfect yet; the last code example in my initial post isn't working.
Neither is this:

```
Interface I
	Method M:Object()
End Interface

Interface J
	Method M:String()
End Interface

Type T Implements I, J
	Method M:Object()
	End Method
End Type
```

**Comment by woollybah** [comment]
I've tweaked the testing order, which now seems to handle those cases too.

**Comment by HurryStarfish** [comment]
Nice :)
