### ISSUE TITLE
Interface method vs. super class method signature

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#274]
Related to and #265 and #269:
Method signatures from implemented interfaces need to take priority over those from super classes if the one in the interface has a more derived return type. The following should not compile, unless T overrides M with a return type of T (or more derived):

```
SuperStrict
Framework BRL.Blitz

New T

Type B
	Method M:B()
	End Method
End Type

Interface I
	Method M:T()
End Interface

Type T Extends B Implements I
	
End Type
```

**Comment by woollybah** [comment]
This currently raises the following error : ```Method I.M:T() must be implemented by type T```

**Comment by woollybah** [comment]
Fixed.
