### ISSUE TITLE
Generated C misses reference to Self object when calling function pointer Field from inside a Method

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#279]
Slightly unwieldly title, but simple example:
```
SuperStrict
Framework brl.standardio

Local x:T = New T
x.CallF

Type T
	Field F() = Func
	
	Method CallF()
		F
	End Method
End Type

Function Func()
	Print "test"
End Function
```
The generated C code for the call to F is `__m_untitled166_t_f();` (or similar), leading to linker errors, it should be `o->__m_untitled166_t_f();`.

**Comment by HurryStarfish** [comment]
The problem is that TCTranslator.TransFunc doesn't distinguish between funcdecls belonging to Fields and those belonging to Globals; there is no information in the funcdecl about this.
I'm not sure about the best way to fix this, Brucey will have to decide that, but my suggestion is:
- Change [this line](https://github.com/bmx-ng/bcc/blob/689239c7bb38c849263f208752f65698dcdbc1d9) to `If decl.IsMethod() Or decl.IsField() Then`
- Add `Const FUNC_FIELD:Int =   $1000` to [the list of constants](https://github.com/bmx-ng/bcc/blob/689239c7bb38c849263f208752f65698dcdbc1d9/decl.bmx#L1550-L1558) above TFuncDecl, and add this method to TFuncDecl:
```
	Method IsField:Int()
		Return (attrs & FUNC_FIELD)<>0
	End Method
```
- Somewhere in TParser.ParseDecl, maybe [here](https://github.com/bmx-ng/bcc/blob/689239c7bb38c849263f208752f65698dcdbc1d9/parser.bmx#L2412), add `If toke = "field" And TFunctionPtrType(ty) Then TFunctionPtrType(ty).func.attrs :| FUNC_FIELD`

**Comment by GWRon** [comment]
Why is all of this needed at all?
There is the need to call a field-functionpointer as "method"?

I assumed it is just what it is ...a pointer to a function. Isnt that directly translateable to "C"?


If really needed I would prefer additional flags too but this requires a proper look into the sources to not miss a then outdated condition.
So every declaration could also store its depth (Type = 1. Field = 2. Type in a type = 3...) .. dunno exactly for what this is useful but might help on splitting apart things.

**Comment by GWRon** [comment]
Something to add (octodroid does not offer edits...).

Of course every "Field" should be marked as such (not sure if it is done already)

**Comment by HurryStarfish** [comment]
> Why is all of this needed at all?
> There is the need to call a field-functionpointer as "method"?
> I assumed it is just what it is ...a pointer to a function. Isnt that directly translateable to "C"?

You don't call it _as_ a method, but if your function pointer is a field, then you still need an object to call it on. If you call `F` from inside a method, then that's short for `Self.F`, and the "Self" part is currently missing in the generated C.

**Comment by GWRon** [comment]
Ahh ok. Sorry for bringing up confusion again. Should not multitask while working :-)
