### ISSUE TITLE
bcc crashes when importing Pub.DirectX

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#280]
Since https://github.com/bmx-ng/bcc/commit/4c786f593592044cb060cd59abd8d56857924186, there seems to be a crash when trying to import the Pub.DirectX module. It happens due to the fact that IsField() on [this line](https://github.com/bmx-ng/bcc/blob/4c786f593592044cb060cd59abd8d56857924186/ctranslator.bmx#L1211) returns true for Direct3DCreate9, which is [actually a function](https://github.com/bmx-ng/pub.mod/blob/92a5532ee435cb8169dfafe5dd98c12891dc807b/directx.mod/d3d9.bmx#L732). The .i file for the module lists this function as `Direct3DCreate9??IDirect3D9(SDKVersion%)="pub_directx_d3d9_Direct3DCreate9"` and [the corresponding code in iparser.bmx](https://github.com/bmx-ng/bcc/blob/4c786f593592044cb060cd59abd8d56857924186/iparser.bmx#L1396-L1416) does `attrs :| CLASS_INTERFACE`. I wasn't aware that the CLASS_[...] constants would be used for functions, so CLASS_INTERFACE collides with the newly added FUNC_FIELD (they're both $1000). I guess the latter will need to get a different value.

That reminds me, the iparser might need some adjustments too to match recent changes in the parser, such as adding FUNC_FIELD to Fields... I'll try and look into that when I have the time.

**Comment by woollybah** [comment]
Should be working now.
