### ISSUE TITLE
Method/Function with Object Parameter doesnt accept Primitives

### ISSUE THREAD

**Issue by Furan86** [bmx-ng/bcc#283]
If you want to make a "generic" method/function you got a problem when using basic primtives (int, float).

I tried to compile my old "stack.bmx" file from the original blitzmax, i know it worked with object and int in blitzmax.

```
Function FuncObj(value:Object)
' do something - not relevant
EndFunction 

local i:int = 1
local f:float = 1.25
local s:string = "hello"

FuncObj(i) ' dont work
FuncObj(f) ' dont work
FuncObj(s) ' works
```

**Comment by GWRon** [comment]
NG is "superstrict/strict". Vanilla BMX does not compile in "superstrict/strict" too:

```Blitzmax
Strict

Function FuncObj(value:Object)
' do something - not relevant
EndFunction 

Local i:Int = 1
Local f:Float = 1.25
Local s:String = "hello"

FuncObj(i) ' dont work
'FuncObj(f) ' dont work
FuncObj(s) ' works
```

```
Building untitled1
[ 97%] Processing:untitled1.bmx
Compile Error: Unable to convert from 'Int' to 'Object'
[/BlitzMax/tmp/untitled1.bmx;11;1]
```

So it's not a "bug" but maybe more a "missing feature" (which cannot be added because of said "strictness" which NG enforces).

**Comment by Furan86** [comment]
Ah ok, would that explains it. How about a void pointer typ then or generics in general ?

**Comment by woollybah** [comment]
Have a look at the new [brl.collections](https://github.com/bmx-ng/brl.mod/blob/master/collections.mod/examples/arraydeque.bmx). It implements the new generics functionality in the latest bcc.

**Comment by Furan86** [comment]
Oh wow thats nice, I see blitzmax-ng is more into monkey/c++-translating then i thought.

**Comment by woollybah** [comment]
Well, it's C, not C++, and NG generics supports primitives, like Int and Float without boxing.

**Comment by HurryStarfish** [comment]
BlitzMax has never allowed primitives to be assigned to Object variables (not even in non-strict mode), generics are currently in the works (NG already has function/method overloading, so you might want to look at that as an alternative in certain situations) and if you need an equivalent to C/C++ "void*", the convention is to use "Byte Ptr" instead.
