### ISSUE TITLE
Attempt to check equality of objects of incompatible generic types crashes bcc

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#290]
```
SuperStrict
Framework BRL.StandardIO

Local o:TTest<String> = New TTest<String>("hi")

Type TTest<T>
	Method New(p:T)
		Print p = Self
	End Method
End Type
```
This causes bcc to crash from a null object exception.
Expected output (taken from the error message displayed when `<String>` above is changed to `<Int>`):

> Compile Error: Unable to convert from TTest<String> to String.

**Comment by woollybah** [comment]
It's not specifically a generics issue.

**Comment by woollybah** [comment]
Should be fixed now.
