### ISSUE TITLE
Feature request: Module-wide member access modifier

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#292]
While trying to make a generic version of TList that could be included in BRL.Collections, I noticed that there is currently no access modifier for type members that makes them visible within the current module without making them completely public.
TList is a good example where this would be useful: it holds a chain of objects wrapped in TLink objects. These TLink objects have fields that contain their respective value, successor link and predecessor link. TList, defined in the same module as TLink, needs to have write access to these fields, but the user of the list who imports the module should not. Currently there is no way to achieve this.
Thus my suggestion: either change Protected to act like Java's `protected`, or (preferrably imo) add two additional modifiers equivalent to VB.NET's `Friend` and `Protected Friend` (aka C#'s `internal` and `protected internal`).

**Comment by GWRon** [comment]
I thought Bruce already added that some commits ago. Maybe it just is not working as expected or I am mixing up things.

**Comment by HurryStarfish** [comment]
He added `Public` (visible everywhere, the default), `Private` (visible only in the same class) and `Protected` (visible in the same class and subclasses) modifiers.
They do indeed work as intended, but none of them covers the use case described above - if I make TLink's fields private or protected, then TList can't modify them; if I make them public, then _everyone_ can.

**Comment by davecamp** [comment]
Is this not why you have 'friend' classes in c++ etc? So that one class can
access the protected members of another.

Maybe that or something similar would need to be implemented too to allow
such a feature?

**Comment by GWRon** [comment]
Dunno if "friend" should be added or not. I prefer to have as little as possible but as few as needed.
So if "protected" would handle that already than I would be fine.

Regardless of this it adds some spice to the language while not being strictly needed for a "app dev". Means it should be of lower priority until the reported bugs are squashed.

**Comment by HurryStarfish** [comment]
> Is this not why you have 'friend' classes in c++ etc? So that one class can access the protected members of another.

Oh, this would be another great alternative, yeah. Instead of making the access modifiers more complicated, it would be a separate "advanced" feature, and even more flexible yet.

**Comment by woollybah** [comment]
I always felt "Friend"s were some kind of cheat, even in C++ :-p

What about making TLink internal to TList, and keep people away from them? (like the internal iterators)

I have a partial implementation of a linked list for brl.collections - just been a bit busy to complete it til now.

**Comment by davecamp** [comment]
Well yeah I agree with you about it feeling like a bit of a cheat but it
would work. How do other OO languages deal with it? or dont they?

**Comment by HurryStarfish** [comment]
@woollybah: But links are supposed to be visible. You get them from methods like `FirstLink` or `FindLink` and they allow you to traverse the list freely (go back and forward forth between elements), insert new elements next to them etc. You're just not supposed to have write access to its field's - only TList should have that.

@davecamp: Well as I said in my initial post, C# has `internal` and `protected internal`, which act like `private` and `protected` respectively except the member can also be accessed by everything in the same assembly it's in. Java has [no modifier] and `protected` respectively which do the same (what I don't like about that is that Java has no modifier that means "visible only here and in subclasses").

I am not sure what "cheat" means in this context, but now that I think about it, friend classes actually kinda seem like a cleaner solution to me. You cannot specify a class from outside the current module as a friend, so it's always at least as restrictive as `internal` (or Java's `protected`). And when you explicitly specify the class that has access to your private/protected members, you're also automatically make the relationship between them clearer than just allowing the entire module to access them, which, if ever needed, could still be allowed by specifying "Friend Module" instead of a "Friend [Classname]" or something.

**Comment by GWRon** [comment]
Couldn't that "friend [classname]" thing - I understood that as something to allow friends in external modules - couldn't that be done with the meta-data-syntax. This would also keep it backwards compatible. And it allows wildcard handling.

{Friend="bah.*.mod"}

Or is this "too much" already?

**Comment by HurryStarfish** [comment]
No, that can't be possible. Friends only make sense if they're within the same module. You can't have circular imports in BlitzMax, which means that two classes in different modules cannot both see each other, but that would be required for friend access. You need to see a class to grant friend access to it, and that class needs to see you to access your members.

**Comment by GWRon** [comment]
I do not get why they are only making sense when within the same module?

For me that `{Friend="bah.*.mod"}` would define whether a calling class/type is allowed to access interna of the "friendly class". I do not understand why it is important to be located in one source file / module.

Also a class/type should not need to know that it is a friend of another class. All in all it is similar to whitelists.

**Comment by HurryStarfish** [comment]
Your class can't just decide that it wants to access the private members of some other class somewhere (that would defeat the whole purpose of having access modifiers to begin with). It's the other way round: that other class has to specify who is allowed to access its private members.
In hypothetical BlitzMax:
```
Type A
	Friend B
	
	Private
	Field F:Int
End Type
```
```
Type B
	Method M(param:A)
		Print param.F
	End Method
End Type
```
- A needs to see B, otherwise you can't write the `Friend B` statement.
- B needs to see A, otherwise you can't write `param:A`.

If A and B aren't in the same module, you can't have both of the above at the same time. Two modules can't import each other.

**Comment by GWRon** [comment]
No I did not want to say that a class defines whose classes fields it wants to read. A class defines what scope/module is allowed to access its private data.

So the {friend="TLinkedList"} would allow the class TLinkedList to access the properties of the class/type having this meta data definition. Meta data uses strings so this would allow for wildcards. But it is less strict then a "keyword".

This shouldn't have something to do with cyclic imports at all as the "allowed to access" class is not required to use it at all...and the allowing class does not need to know the actual implementation as it just defines itself as "friendly to XYZ".

**Comment by HurryStarfish** [comment]
> So the {friend="TLinkedList"} would allow the class TLinkedList to access the properties of the class/type having this meta data definition.

So let's call that class "A".
Then how do you want the compiler to check this metadata that you added to A? Doesn't matter whether you write it as `Friend TLinkedList` or as `{friend="TLinkedList"}`, the compiler still needs to understand what this means. It needs to know that `TLinkedList` class that you're referring to to make anything about this work. That means an import of the module that contains `TLinkedList` no matter how you look at it, even if you do it with a different syntax.
And if you want TLinkedList to actually access those members of A you just gave it permission to (because what would be the point of the feature if you can't ever use it??), then the list module needs to import the module that contains A. Cause you can't compile code that accesses members of A without the compiler knowing about A. And there's your cyclic import.

Besides, something like this definitely doesn't belong in meta data. This is stuff handled by the compiler as you compile your code. Metadata is something to work with via reflection at runtime.

**Comment by GWRon** [comment]
I know what metadata is intented for but it would have allowed to add something without breaking backwards compatibility.


The compiler would need to check nothing:

Class a defines class b as a friend.

Case 1: b never accesses a (and therefore never imports the b-sources). No dependency, no trouble.

Case 2: b wants to write to a. b imports a-code and compiler is able to check if b is friend of a. Dependency solved as the meta data thing (a defines friends in a string so no hardcoded dependency from a to b)

Case 3: a wants to write to b too... First you solve the cyclic dependency (interfaces or base classes) and then it is similar to case 2. Both define the other as friend and the compiler does the checks on compilation (is a able to see b, is b able to see a).


All the things would be done like with the #conditionals or header files in c/c++ or maybe even as #defines in said languages.



But of course I understand that it is way "hackier" or "dirty" than introducing a new keyword in a proper way. So if we want to cut connection to vanilla (growing up :-)) then adding new keywords is surely the better approach.

**Comment by GWRon** [comment]
The cyclic dependency problem you describe...has to be solved regardless of how "friend" is implemented. And once this is solved you can go on as usual.

As soon as something is accessing another class the compiler knows where to check for "friendlyness" and if you do not access another class, there is no friend information needed.


So i somehow doubt I fully understood what you tried to explain to me. So excuse me in advance.

**Comment by davecamp** [comment]
That sounds like a separation of concerns to me, in respect of relating a
Type access to a Module. Keeping Type access related to Type access would
be more consistent.

The 'friend' thing feels like a cheat because it fixes a problem that it
created in the first place. This all goes to show that the OO ( particular
inheritance ) paradigm isn't all it's cracked up to be eh ;-) and you don't
have these issues with composition with inheritance through interfaces
only. Maybe use approach that to solve the TList issue?

 If 'friend' access isn't favorable then fleshing out the 'protected'
access would be a resolution with maybe, as suggested by Ronny, using the
metadata tag but using Type as opposed to Module access, for reasons in the
first paragraph..

**Comment by HurryStarfish** [comment]
Okay... after giving this a little more thought, I think we're seriously overcomplicating this.
Actually, why don't we just avoid all that confusion and instead go with the simplest possible solution of all:

- Amend the meaning of the current existing `Private` and `Protected` modifiers so that members are also visible to the rest of the file they're defined in.

In other words: `Private` members would be visible to the rest of their source file* - which means it'll basically mean the same as the toplevel `Private` modifier that already existed in vanilla BlitzMax. `Protected` would be similar, except that the members are also visible to subclasses (regardless of where they are).
This should be easy to implement, easy to understand and easy to use. No new keywords needed, no special features and no problems with imports. The consistency between toplevel and type-member `Private` is a nice bonus. Two classes can then see each other's members whenever they are within the same file. It doesn't really undermine the security of the modifiers very much imo, since source files are quite self-contained and two classes being in the same file already indicates some sort of coupling.
(* `Include`d files still count as part of the same file, of course)

Of course, instead of changing `Private` and `Protected`, two new modifiers could also be introduced. In that case, they might be called `FilePrivate` and `FileProtected` (very literal), or maybe `PrivateFriend` and `ProtectedFriend` (bearing some similarity to the VB meaning of "Friend", _not_ the C++ one). It wouldn't quite have the same beautiful simplicity though. :]

**Comment by GWRon** [comment]
I do not like the idea of "only when in the same file". I try to decouple things as much as possible, so "import" rather than "include". Import allows for precompiled files (faster compilation times, maybe even "non-source"-distribution?).

This means I would need to have "base classes" in one file which then expose certain functionality to ancestors ("myclass extends baseclass") which then could be located in their own sourcecode files. Functionality exposure could be skipped if an extending class inherits allowance to access fields the base class is allowed to access from a foreign/other class.

But I understand the "simplicity"-thought you described regarding `Private` and `Protected`. Regarding "imports" I would tend to prefer new keywords (ignoring loosing backwards compatiblity - which could be overcome with `?bmxng`-conditionals) or said meta data (which allows for even more flexibility because of "parseable" strings - by really hitting "simplicity" with its "spelling error"-chances, language grammar tinting ...).

**Comment by HurryStarfish** [comment]
> I try to decouple things as much as possible, so "import" rather than "include".

That's exactly why I like the idea though. If a class needs to access another's non-public members, then those classes _are_ logically coupled. Having to put them both in the same file helps to make that clear. Keep in mind that this wouldn't restrict your current use of Import in any way. It would merely allow you to do something you currently can't do at all. It's a relatively uncommon case ito begin with.

> This means I would need to have "base classes" in one file which then expose certain functionality to ancestors ("myclass extends baseclass") which then could be located in their own sourcecode files. Functionality exposure could be skipped if an extending class inherits allowance to access fields the base class is allowed to access from a foreign/other class.

I am not sure if I understand this correctly: if you have some class A, and an unrelated class B that is allowed to access non-public members of A, then you want any subclasses of B to be allowed to access these members too?
Neither Java nor C# nor C++ have any kind of feature to directly allow that, as far as I know. You can, however, achieve it indirectly in certain ways, even with my "simple" proposal above. For example, you could add Protected Getter- and Setter methods for those members to B, and you'd then be able to call them from any subclass of B.

**Comment by GWRon** [comment]
Yes I meant what you described (class a and class b). And the getters/setters would be the "exposed functionality" I was talking about. But this then also means, that other classes might access GetX, SetX ... too. To avoid that, allowance/access should be inheritable (optional?).

**Comment by HurryStarfish** [comment]
> But this then also means, that other classes might access GetX, SetX ... too.

If you make them Protected, then no, only subclasses of B would. Well, other classes in the same file as B too, but that's the same thing that happens with protected in Java (where the whole package can actually see them, not just the file).

**Comment by GWRon** [comment]
> If you make them Protected, then no, only subclasses of B would see them. 
Oh, totally missed that. You're right.
So "field x:int" becomes `private` and "GetX:int()" becomes `protected`.

Seems it is obvious I never really used that features (only did some prototyping in java and libgdx).

So there is just my "edit" in the previous response left.

**Comment by HurryStarfish** [comment]
regarding the edit:

> Imagine one wrote a module and another one is "piggybacking" it. How would the other one write its module to allow access to private members of the first one's module?

Then you're doing something you probably shouldn't, because it'd defeat the point of modules as a decoupling mechanism. If one of your two modules is that dependent on the other's internals, then they have no business being separate modules; they should be combined into one module. Either that, or the first module is some kind of utility module that _everyone_ (not just a specific second module) should be able to "piggyback" off of, in which case you just make the members public.

> But what if the first module contains some "rules" which allow others to modify interna?

Well, the existing access modifiers already are these rules. For example the rule for `Protected` is currently "must be a subclass (which actually _can_ be anywhere, even in another module)", and the rule for `Private` at toplevel is "must be in the same file". And by doing the Getter/Setter thing mentioned above, you are even able to "combine" them in clever ways. But seeing as both Java and C# (extremely popular languages, used to build way more complex applications than BlitzMax ever will) don't have specialized language features for access rules any more complex than that, I'd say that's a good indicator that we won't need them either.

**Comment by GWRon** [comment]
> Either that, or the first module is some kind of utility module that everyone (not just a specific second module) should be able to "piggyback" off of, in which case you just make the members public.

I just thought about the "rules" being some kind of "conduct" between the user (2nd module) and the provider (1st module).
Something in the likes of "if you implement interface X to gain access to my fields you surely know what might happen if you manipulate my data". Like a "enter code" or a "key".


Regarding C#/Java/... I think you are right and I am surely overcomplicating things which at the end nobody ever would even consider using.
