### ISSUE TITLE
Byte array to byte ptr

### ISSUE THREAD

**Issue by HenriVi** [bmx-ng/bcc#295]
Hi,

this line of code results an internal error, but works in regular Bmax:

Local myt:t = New t
myt.b = New Byte[5]

Type t
	Field b:Byte Ptr
EndType

If byte array is created first in a separate variable, then it would work.

-Henri

**Comment by HurryStarfish** [comment]
Applies to New-expressions of any kind of array, not just Byte arrays. Array literals seem to work fine though.
