### ISSUE TITLE
Cannot access Struct's field on result of New

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#296]
```
SuperStrict
Framework BRL.StandardIO

Print New S.F

Struct S
	Field F:Int = 3
End Struct
```
```
error: invalid type argument of '->' (have 'struct _m_untitled7_S')
   brl_standardio_Print(bbStringFromInt(bbt_->__m_untitled7_s_f ));
                                            ^
```

**Comment by woollybah** [comment]
Is this the latest build?

In my build, it generates ```.``` instead of ```->```.

Or do you have a different example?

**Comment by HurryStarfish** [comment]
Thats strange, it _should_ be the latest bcc from the master branch, I pulled and built it about a week ago; BRL.mod as well.
I can doublecheck at a later time, maybe I did something wrong; but the last time I updated my NG before that was before generics and BRL.Collections existed, and I have both of those now, so that's a bit odd.

**Comment by HurryStarfish** [comment]
This still happens for me with the latest bcc and brl.mod.
