### ISSUE TITLE
Multiple constraints on a type parameter

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#303]
It does not currently seem to be possible to have multiple contraints on the same type parameter.
Take this example:
```
SuperStrict
Framework BRL.Basic

Local x:TTest<TImpl>

Type TTest<T Extends I1, I2>   ' <- problem here
End Type



Interface I1
End Interface

Interface I2
End Interface

Type TImpl Implements I1, I2
End Type
```
The problem here is that while `Type TTest<T Extends I1, I2>` looks similar to Type `TImpl Implements I1, I2`, it actually declares two type parameters instead of one type parameter with two bounds.
A possible solution would be to introduce a syntax such as `Type TTest<T Extends (I1, I2)>` or `Type TTest<T Extends I1 And I2>`.
However, while this would allow multiple bounds, the afromentioned similarity (`Implements I1, I2` vs. `Extends I1, I2` ... or, since an interface can "extend" multiple interfaces, even `Extends I1, I2` vs. `Extends I1, I2`) makes this feel inconsistent and confusing.

**Comment by GWRon** [comment]
Couldnt the "implements" be used as concatenator/and-connector?

Implements T1 implements T2
But it looks a bit noisy/verbose.


As blitzmax allows
MyFunc param1, param2
an 
implements T1, T2
looks similar...but if you think of above as a "declaration" then it should need brackets even with only one parameter.
This allows consistency and avoids ambiguity (no brackets needed with one param and brackets needed with more than one).  Function declarations also need brackets so it would fit somehow.

Implements T1 and T2
would fit well too as "and" is already known as keyword and the whole interface thing is a new feature (with the <> being introduced as well) which could allow such an and-introduction



How do other languages tackle that "problem"?
