### ISSUE TITLE
Modification of local variables in a Try-block

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#312]
I think it would be quite useful to have Finally blocks in BlitzMax-NG. I've been looking into how those could be implemented, but while doing so I noticed this:
Try-Catch is implemented in NG via setjmp and longjmp. Upon entering a Try block, setjmp is called; if an exception is thrown, a longjmp causes the program to jump back to the setjmp and execute the respective Catch code.
For example, the following BlitzMax code:
```BlitzMax
Function F()
	Local i:Int = 1
	Try
		'! // try block
		i = 2
		Throw "ex"
	Catch ex:Object
		'! // catch block
		Print i
	End Try
End Function
```
generates C code like this:
```C
void _m_untitled9_F(){
	BBINT bbt_i=1;
	do {
		jmp_buf * buf = bbExEnter();
		switch(setjmp(*buf)) {
			case 0: {
				 // try block
				bbt_i=2;
				bbExThrow((BBObject *)&_s0);
				bbExLeave();
			}
			break;
			case 1: {
				BBOBJECT ex = bbExObject();
				if (bbObjectDowncast((BBOBJECT)ex,(BBClass*)&bbObjectClass) != &bbNullObject) {
					BBOBJECT bbt_ex=(BBOBJECT)ex;
					 // catch block
					brl_standardio_Print(bbStringFromInt(bbt_i));
				} else {
					bbExThrow(ex);
				}
			}
			break;
		}
	} while(0);
}
```

However, as I was [reading up](http://en.cppreference.com/w/c/program/setjmp) on setjmp and longjmp, this caught my attention:

> Upon return to the scope of setjmp, all accessible objects, floating-point status flags, and other components of the abstract machine have the same values as they had when longjmp was executed, except for the non-volatile local variables in setjmp's scope, whose values are indeterminate if they have been changed since the setjmp invocation.

From my understanding (and from [info](https://stackoverflow.com/questions/1393443/setjmp-longjmp-and-local-variables) I found [elsewhere](https://www.gnu.org/software/libc/manual/html_node/Non_002dLocal-Details.html)), it seems to be that `i` in the above example is such a variable. The assignment `bbt_i=2;` occurs between the call to setjmp and that to longjmp (the latter being bbExThrow), yet bcc does not declare `bbt_t` as volatile; meaning that this assignment may be lost after the exception is thrown.
Am I misunderstanding/missing some information here or is this indeed a potential bug?

**Comment by woollybah** [comment]
Yes, the semanting probably needs to understand if a local variable needs to have volatile applied to it.

**Comment by HurryStarfish** [comment]
I think that would be any variable declared in the same function as the Try-block that might be modified within the Try- or within any of the Catch-blocks. Seems difficult, since this could happen in all kinds of ways: being assigned to, being used with operators (`:+`, `:*` and any other ":"-operator, as well as any user-overloaded operator on struct types), being called methods on, passed to functions/methods as a Var parameter, or even indirectly via pointers...

I did try to implement Finally-blocks anyway after I had opened this issue. I got them mostly working, but then got stuck once I realized that since I was generating jump labels in the C code, there would need to be some sort of "munge" system for loop labels, similar to other identifiers, to make sure that they're unique within the C function they end up in. I wasn't sure how to do that, and then personal things got in the way, so I haven't managed to do it since then.

**Comment by woollybah** [comment]
I think I've covered most of the cases. There are probably some edge cases (like indirect modification via pointers) that, without just making everything volatile, it's almost impossible to determine at compile time.

**Comment by HurryStarfish** [comment]
I cannot reopen issues, so I hope a comment will do, but it seems that the special case of nested Try-blocks isn't handled correctly yet:
```
SuperStrict
Framework BRL.Blitz

Function F()
	Local v1:Int
	Try
		v1 = 1
		Local v2:Int
		Try
			v2 = 2
		End Try
	End Try
End Function
```
In this program, v1 gets declared as volatile, but v2 does not.

Variables of a struct type do not seem to get volatile qualifiers at all. Is this intentional? If not, then they'd probably have to be declared volatile if any of their members gets modified as well.

As for pointers: making a variable volatile if `Varptr` is used on it anywhere in or above the Try-block (given that the function actually _contains_ a Try block) might help. That way, if someone directly creates a pointer to the variable, it would be safe to use. This would not cover the case of someone getting a pointer to the variable via pointer arithmetic. But that doesn't seem to like like a reasonable thing to do in the first place. With class members or array elements, it is quite straightforward to jump from one member to another via adding an offset, but not so with local variables, so imo undefined behaviour would be acceptable in this case.
This would cover most "reasonable" uses of pointers. It wouldn't cover the case of someone using pointer arithmetic to get the pointer, but  like you could with array elements or class members)
