### ISSUE TITLE
New Self doesn't work in Abstract type

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#313]
The following works in legacy BlitzMax:
```blitzmax
SuperStrict

Framework BRL.Standardio

Type TType
    Method ab() Abstract

    Method test:TType()
        Return New Self
    End Method

End Type
```
but in NG it complains that TType is Abstract and you can't create an instance of it - however, Self would not be an instance of it, but a subclass...

**Comment by GWRon** [comment]
Yeah, `new self` is pretty handy when creating the same type and you want to avoid overriding a `CreateNew:TMyBaseClass()` method in each extended type.
