### ISSUE TITLE
Constant expression that involves division by zero crashes bcc

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#320]
```
SuperStrict
Framework BRL.Blitz

Local a:Int = 1 / 0
```

**Comment by GWRon** [comment]
Think Brucey should run some SimpleCodeTester tries to catch such "simple" failures.

**Comment by HurryStarfish** [comment]
That's probably be a good idea in general: adding a test everytime an easily reproducible bug like this is fixed (and then run the tests after every major change) to make sure it doesn't come back.
Maybe I could go through the closed ticket list and add a few tests based on those if that helps?

**Comment by HurryStarfish** [comment]
How would one actually test something like this with SimpleCodeTester though? The expected result is for compilation to fail, after all, just not to crash the compiler...

**Comment by GWRon** [comment]
Hmm. So "SCT" needs to check the error-outputstream for compilation files?

For now "SCT" just compares results - if a<>b it counts as "failed"
