### ISSUE TITLE
Is where a reserved word?

### ISSUE THREAD

**Issue by braxtonrivers** [bmx-ng/bcc#321]
Any occurrences of 'where' need to be renamed eg 'where_' otherwise it produces the following error message.

Thanks

Compile Error
syntax error - expecting identifier

**Comment by woollybah** [comment]
Hi, yes, where has become a keyword with the latest bcc - it is used in new generics stuff.

Apologies for any inconveniences you have with that...

**Comment by braxtonrivers** [comment]
Thank you, all good nice to know, and no apologies necessary I use it in quite a few places, and there are a few occurrences in various modules which also need to be renamed.
