### ISSUE TITLE
Add Finally for Try/Catch

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#325]
It would be a nice language feature to support Finally with Try blocks.
Statements within the Finally section of a Try are always executed whenever a Try block exits. The Finally block is executed after a Catch.

Catch becomes optional, if a Finally is included.

Here's a simple example :
```blitzmax
Superstrict

Framework brl.standardio

Try
	Print "Try"
	
	Throw "ex"

Catch e:Object
	Print "Catch"
Finally
	Print "Finally"
End Try
```
would produce the following output :
```
Try
Catch
Finally
```
The Finally block should always execute, regardless of exit points :
```blitzmax
Superstrict

Framework brl.standardio

test()

Function test()
	Try
		Print "Try"
		
		Return
	Finally
		Print "Finally"
	End Try
End Function
```
should output :
```
Try
Finally
```

Nesting is also possible,
```blitzmax
Superstrict

Framework brl.standardio

test()

Function test()
	Try
		Print "Try"
		
		Try
		
			Print "Inner Try"
			
			Throw "ex"
			
		Finally
		
			Print "Inner Finally"
		End Try

	Catch ex:Object
	
		Print "Catch"
	
		Return ' exit function
	Finally
		Print "Finally"
	End Try
End Function
```
which would output
```
Try
Inner Try
Inner Finally
Catch
Finally
```

**Comment by HurryStarfish** [comment]
As mentioned in #312, I've been working on that sometime ago. I hadn't quite managed to iron out all the special cases (Exit and Continue labels in particular), but I could upload my work-in-progress code if you want to take a look at it.

**Comment by woollybah** [comment]
Cool. It might save a bit of work. Thanks.

**Comment by woollybah** [comment]
@ labels
Maybe things could be simplified by using computed gotos/jump table? gcc and llvm both support them, and it may make things much easier to implement...

**Comment by woollybah** [comment]
We should consider enforcing a compile error for "exiting" a Finally block - via Continue, Exit or Return.
C# does this, and although Java allows it, it's recommend you don't.

**Comment by HurryStarfish** [comment]
I've rewritten the feature to use computed gotos, and seem to have managed to fix the previous issues too. I'm now testing for special cases; if I don't find any new problems, I can clean up the code and put up a pull request soon.

**Comment by HurryStarfish** [comment]
[Pull request is up.](https://github.com/bmx-ng/bcc/pull/330)
