### ISSUE TITLE
compile error: undefined reference to `bbExObject'

### ISSUE THREAD

**Issue by xlsior75** [bmx-ng/bcc#332]
error compiling with GCC 7.2.0:

[ 87%] Compiling:toker.bmx.release.win32.x86.c
[ 88%] Compiling:parser.bmx.release.win32.x86.c
[ 88%] Compiling:ctranslator.bmx.release.win32.x86.c
[ 89%] Compiling:bcc.bmx.console.release.win32.x86.c
[100%] Linking:bcc.exe
c:/code/BlitzMaxNG720/bcc-ng/.bmx/bcc.bmx.console.release.win32.x86.o:bcc.bmx.console.release.win32.x86.c:(.text+0x3ef): undefined reference to `bbExObject'
c:/code/BlitzMaxNG720/bcc-ng/.bmx/parser.bmx.release.win32.x86.o:parser.bmx.release.win32.x86.c:(.text+0x175dc): undefined reference to `bbExObject'
c:/code/BlitzMaxNG720/bcc-ng/.bmx/parser.bmx.release.win32.x86.o:parser.bmx.release.win32.x86.c:(.text+0x17c4e): undefined reference to `bbExObject'
c:/code/BlitzMaxNG720/bcc-ng/.bmx/type.bmx.release.win32.x86.o:type.bmx.release.win32.x86.c:(.text+0x14ae1): undefined reference to `bbExObject'
c:/code/BlitzMaxNG720/bcc-ng/.bmx/type.bmx.release.win32.x86.o:type.bmx.release.win32.x86.c:(.text+0x14d42): undefined reference to `bbExObject'
c:/code/BlitzMaxNG720/bcc-ng/.bmx/type.bmx.release.win32.x86.o:type.bmx.release.win32.x86.c:(.text+0x154e3): more undefined references to `bbExObject' follow
collect2.exe: error: ld returned 1 exit status
Build Error: Failed to link c:/code/blitzmaxng720/bin/bcc.exe[ 14%] Processing:bmk_cores_win32.bmx
[ 14%] Processing:stringbuffer_common.bmx
[ 15%] Processing:stringbuffer_core.bmx
[ 15%] Processing:bmk_ng_utils.bmx
[ 16%] Processing:bmk_config.bmx

**Comment by woollybah** [comment]
Do you have all the latest bcc & brl sources?
The latest development adds Finally blocks for Try statements which makes changes to both the generated code and the very low-level stuff in BRL.Blitz.

**Comment by xlsior75** [comment]
I just purged my bmk-ng, bcc-ng and brl.mod folder and tried again.

brl.mod recompiled fine, when I try to either recompile bmk.exe or bcc.exe, they both give me the  same "undefined reference to `bbExObject'" error...

my existing executable versions: 
bmk 3.25 mt-win32-x86 / gcc 070200 (cpu x12)
bcc[ng] Release Version 0.94

Unless my current version needs to be newer in order to compile the bcc/bmk sources, but that would be a bit of a chicken-or-the-egg scenario...

**Comment by woollybah** [comment]
In this particular case, if you are using the latest brl.mod to create bcc in order to use it with the latest brl.mod... then, yes, that won't work - due to the low-level changes in brl.mod.

You'd need to compile bcc with the previous brl.mod and then get the latest brl.mod and start using that with the new bcc.

If you get this version of brl.mod ( https://github.com/bmx-ng/brl.mod/tree/028fc1296b0916f09dc46c8f0b59d2487ff3fe5d ) and compile the new bcc, you should then be able to update to the latest brl.mod and use the new bcc...

**Comment by woollybah** [comment]
Once you are up-to-date, you will also need to full rebuild anything you are working on once you start using the new bcc/brl - so that's any other modules/source.

**Comment by GWRon** [comment]
Maybe it is a good idea then to provide new complete packages of bmxng. So there is a working base for all of us.

**Comment by woollybah** [comment]
Indeed. There are releases in the releases area for the bmx-ng project.

If you want to live on the bleeding edge, and accept that occasionally things may change that might break something, you can use the code straight from the repos.

To be fair, low-level breaking changes are quite infrequent. The next one is likely to be the reflection upgrade, for which there is no ETA.

**Comment by xlsior75** [comment]
OK, looks like the previous brl.mod let me compile bcc/bmk.
Dropped in the current brl.mod and compiled that.

Now recompiling all the other modules. Will take some time, but so far looking promising.

Thanks!

**Comment by GWRon** [comment]
So you say you want remove backwards compatibility or are you planning to have two modules...a basic one (compatible to vanilla) and an extending one which enables usage of the new features?

**Comment by HurryStarfish** [comment]
I'd want to make a new, somewhat different reflection module that would make the old one obsolete.
The old module would still work, but not get updated anymore for newer language features and hopefully only be use to compile old code that was written before the new module existed.

Whether `BRL.Reflection` would then get replaced by the new module (and the old one renamed to BRL.ReflectionOld or something) or whether the new module gets a new name is something that could be decided later.
