### ISSUE TITLE
BCC does not ignore new line when assigning variables

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#336]
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Local obj:object = new object
Local s:string =
obj
```
(or obj.MyMethod() returning an object ...)

The result is, it highlights the line with `obj` and errors out with: `Compile Error: Unable to convert from Object to String.`.
BlitzMax normally needs ".." to concatenate stuff. BCC NG seems to ignore that.

Vanilla Blitzmax would first of all blame "new Object" (`Expecting '[' but encountered end-of-line`) - which NG currently does not blame.
Replacing it with a Testtype:
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Type TTest
End Type

Local obj:TTest = new TTest
Local s:string =
obj
```
Leads to a highlighted `Local s:string =` line and the error `Compile Error: Expecting expression but encountered end-of-line`

**Comment by HurryStarfish** [comment]
I don't really see a problem with `New Object`. Vanilla BlitzMax doesn't allow it, but Object isn't abstract and imo NG's behaviour is simpler and more logical by not giving it special treatment. It's not really useful to create "raw" objects, but it does no harm either.

The issue you're really reporting here is definitely a problem though. It could make errors harder to find, and even turn compile time errors into runtime ones:
```
SuperStrict
Framework BRL.StandardIO

Function Test:Int()
	Print "asdf"
	Return 99
End Function

Local a:Int = 1
Local b:Int = ' <- assume I wanted to copy a here, but forgot to write "a"
Test() ' just want it to print "asdf", don't care about the return value

Print b ' expected to get 1 here, instead I get 99 - in vanilla I'd get a compile time error
```

This seems to be a problem with how expressions are parsed. It also happens in other places, for example this should be an error too:
```
SuperStrict
Framework Brl.StandardIO

For Local i:Int = 1 To
2
	Print i
Next
```

**Comment by GWRon** [comment]
Yes...the new object thing was just a side annotation.

The real bug is exactly how you understood my hint about methods ...that it evaluates the returned value as if it was a line before.
