### ISSUE TITLE
NG allows assignment to .length field of arrays and strings

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#338]
This compiles.
It shouldn't. :) 
```
SuperStrict
Framework BRL.StandardIO

Local a:Int[] = [1, 2, 3]

a.length = 10
For Local i:Int = EachIn a
	Print i
Next
Print

Local s:String = "hello"
s.length = 20
Print s
Input
```

In vanilla, the `length` field of the String and array types is actually a read-only field. This topic came up recently in #333. If we implement user-defined `Final`/`ReadOnly`/`SomeOtherKeyword` fields, then the `.length` field could be treated the same as them; i.e. bcc would do the same checks and output the same error message as for any read-only field in a user-defined type.

**Comment by woollybah** [comment]
This will be fixed with the next release - needs an update to the blitz classes .i files to define the length fields as readonly.

**Comment by woollybah** [comment]
Missed the release.. but fixed now...
