### ISSUE TITLE
New and Delete declarations should not have return types

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#339]
```
SuperStrict
Framework BRL.Blitz

Type TTest
	Method New:String()
	End Method
	
	Method Delete:String()
	End Method
End Type

New TTest
```
This leads to bcc generating broken C code. Ideally, it should not be allowed to attach return types to New and Delete methods at all since doing that makes no sense, but unfortunately it's allowed in vanilla. I don't know if breaking backwards compatibility would be acceptable here, but if not, maybe a warning could be generated instead?

**Comment by GWRon** [comment]
Never knew this is even possible with vanilla - but isn't it just not evaluated?

so behaviour could become the same as with vanilla.

**Comment by HurryStarfish** [comment]
> Never knew this is even possible with vanilla

Neither did I. I only noticed because I was looking for a different error in a New method I had written by copy-pasting a Create function and had apparently forgotten to remove the return type.


> so behaviour could become the same as with vanilla

Yeah, it's just kinda weird. Declaring a return type implies that it's possible to return something from these methods, but of course that doesn't work.
