### ISSUE TITLE
Comparing void function with null leads to "internal error".

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#341]
I am using "bah.libxml" and called something like this:

```BlitzMax
  if xmlNode.setContent(newValue) <> null then adjusted = true
```
this resulted in an `Internal Error` on compilation - as `setContent()` is defined as void. In vanilla this works as "void" is `int` there.

**Comment by woollybah** [comment]
Yes, it should be a compile error, since setContent() does not return a value.
