### ISSUE TITLE
"New {variable}" vs. constructor access modifiers

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#342]
BlitzMax allows the creation of new object by writing the `New` keyword followed by a variable instead of a type. This is perhaps the weirdest feature of the language, and it doesn't mix well with access modifiers. For example, it is currently possible to call a private constructor like this:
```
Type TTest
	Field i:Int
	
	Private
	Method New()
	End Method
	
	Public
	Method New(i:Int)
		Self.i = i
	End Method
End Type

Local a:Object = New TTest(1)
Local b:Object = New a
```
The following, on the other hand, is not possible because Object does not have a constructor accepting an Int:
```
Local b:Object = New a(3)
```
The `New {variable}` expression checks the runtime type of the object it is given and creates a new object of that type. The compiler, however, can of course not know what is going to be created and runs checks against the compile time type instead, resulting in odd behaviour.
The `New {variable}` feature has to be supported for backwards compatibility with legacy BlitzMax, but the fact that it can silently bypass access restrictions seems quite dangerous. Is there anything that can be done about this? Imo even a runtime error might be better than this, as it would likely be much easier to find and fix than the strange bugs that could potentially be caused by the current behaviour...

**Comment by woollybah** [comment]
The only thing that comes to mind is to add an extra "instance" ctor for each class, which by default will call the standard ctor. But if the ctor is not public, we could throw from there instead.

The current generated code just calls bbObjectNew(), passing in the class of the object. At compile time we know this is an instance, so we could call a bbObjectNewInst() instead, which would call the new instance new method on the class.

Otherwise, there's nothing we can do at runtime to do these kind of checks.

**Comment by HurryStarfish** [comment]
> The only thing that comes to mind is to add an extra "instance" ctor for each class, which by default will call the standard ctor. But if the ctor is not public, we could throw from there instead.

Even though it is kinda weird for a `New` expression to implicitly throw an exception, this is probably the best possible solution.
As the feature is quite obscure to begin with - personally I've seen it used very rarely - maybe NG should output an unconditional warning when it's used, to make it clear that it should be considered deprecated and is only supported for backwards compatibility?

**Comment by GWRon** [comment]
Only use of `new variable` I planned to use was `new self`. Until now I preferred the traditional mentioning of the explicit typename.
Nonetheless there might be cases which need a overly lengthy replacement code if you break backwards compatibility. But hmm... If it is painful to keep this compatibility in the compiler then I would prefer cutting some loose ends.

**Comment by HurryStarfish** [comment]
`Nonetheless there might be cases which need a overly lengthy replacement code if you break backwards compatibility.`
With the approach Brucey described, any vanilla code would still work as before, so it wouldn't break backwards compatibility.
If the feature was completely removed, the easiest way to fix broken code would be with BRL.Reflection: `New a` is equivalent to `X(TTypeId.ForObject(a).NewObject())` where `X` is the compile time type of a.
My suggestion of a deprecation warning would sort of be a compromise between both, I suppose.

**Comment by woollybah** [comment]
I'm going with the deprecation, as it doesn't require a rewrite of the internals :-)
New Self is still supported because the compiler can determine access of Self.

**Comment by HurryStarfish** [comment]
> New Self is still supported because the compiler can determine access of Self.

Can you clarify what you mean by that? Since it is still possible to call a private constructor like this:

```
SuperStrict
Framework BRL.StandardIO


Type TTest
	
	Method M:TTest()
		Return New Self
	End Method
	
	Method New()
		Print "TTest.New"
	End Method
	
End Type

Type TTest2 Extends TTest
	
	Method New(i:Int)
		Print "TTest.New(Int)"
	End Method
	
	Private
	
	Method New()
		Print "TTest2.New"
	End Method
	
End Type


Local a:TTest = New TTest2(4)
Local b:TTest = a.M()
DebugStop
```
