### ISSUE TITLE
SetRotation = 0

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#344]
Using 0.93 from the public release this:

    SetRotation = 0

slips through the compiler and creates a function declaration in the c file:

    brl_max2d_SetRotation;

**Comment by GWRon** [comment]
And in wxmax it gets ignored at all... maybe I can get your attention (as my current blitzmax-graphics-expert contact :-)l at this issue meanwhile.


Without testing now..might it be the "0"? If so it possibly affects other stuff too.

**Comment by davecamp** [comment]
When you use the function properly ( with or without parenthesis ) it gets called properly.
When you **assign** it with a value, any valid value for the parameter, then the same 'error' occurs.

**Comment by HurryStarfish** [comment]
This happens when a module with a function named SetRotation, such as Max2D, is imported, but it appears to have nothing to do with the specific function or the assigned `0` specifically.
For example, this also compiles
```
SuperStrict
Framework BRL.StandardIO

Print = 123
```
and turns into `brl_standardio_Print;` in the generated C. This is not a declaration, it just refers to the existing function name as a statement. Its like writing `42;` or `7 + 8;` in C code, it does nothing.
Nevertheless this should be a compile error; it seems bcc doesn't specifically check for "trying to assign to function" (or at least not correctly?), ends up [here](https://github.com/bmx-ng/bcc/blob/52ae279197b93244498247f33adf1840d120d729/expr.bmx#L2678), and generates a reference to the function instead.

**Comment by GWRon** [comment]
Ahh sorry for bringing in my totally differing issue. I absolutely ignored the "=" character and assumed an issue with calling functions and a null/0 param.

**Comment by HurryStarfish** [comment]
Oh, I assumed you were suggesting that `= 0` specifically might have a special meaning, [kinda like this](https://en.wikibooks.org/wiki/C%2B%2B_Programming/Classes/Abstract_Classes) (which isn't the case).

**Comment by davecamp** [comment]
I would have thought that the compiler should emit an error saying that a parameter is missing, I agree with what you're saying about with things like? SetRotation doesn't have any default arguments in the same way that Print does.

Actually I remember I was messing with gcc some time ago and I had a not too dissimilar scenario.

https://stackoverflow.com/questions/43441714/gcc-linking-externs-incorrectly

**Comment by HurryStarfish** [comment]
> I would have thought that the compiler should emit an error saying that a parameter is missing

Ideally, it should report the assignment as illegal, like when you're trying to reassign a constant. The statement is already correctly parsed as an assignment, not as a function call.
What I'm suspecting is that the check that is supposed to catch this is [this line](https://github.com/bmx-ng/bcc/blob/52ae279197b93244498247f33adf1840d120d729/expr.bmx#L2669), which it actually does if you write the "broken" assignment in Strict code ("Identifier 'Print' cannot be used in this way."). In SuperStrict code however `_env.ModuleScope().IsStrict()` returns False, bypassing the error. But I don't know for what reason that `_env.ModuleScope().IsStrict()` exists there in the first place, so I suppose we'll have to wait for Brucey to comment on that.

**Comment by davecamp** [comment]
I'm not sure on how bcc code flows to semant an assignment but I would expect something along the lines of:

Semant the identifier which identifies and assigns the declared identifier a valid Type, drops it into a symbol table/cache of some kind.
Semant the expression which also gives it its valid Type.
Cast the expression type to the identifier type. In the cast is where an error would be generated.

But as I say I'm not familiar with how bcc does it low level work.
