### ISSUE TITLE
Introduce new metadata tag for exporting functions

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#348]
Currently, functions generated by bcc have some prefix stuff added to them to make them unique across modules.
For DLL exported functions, it would be preferable not to have the extra fluff and expose the function name as-is.

Here's an example of the exported function name for an app called dll_test : 
```blitzmax
Function HelloWorld()
    Print "Hello World!"
End Function
```

Exported as ```_m_dll_test_HelloWorld```

Ideally this would be exported as ```HelloWorld```

Some kind of metadata tag would be the simplest way to implement the functionality...

```blitzmax
Function HelloWorld() { export }
...
```

Where ```export``` is the tag that the compiler understands not to add the prefix stuff.

I'll go with ```export``` unless someone can provide a suitable alternative :-)

**Comment by Kerntrick** [comment]
Sounds good.  
Does NG still consider the  "WIN32" or "C" postfix on function declarations?

**Comment by woollybah** [comment]
You mean for cdecl/stdcall?
Yes, it should generate the appropriate code for stdcall functions.

**Comment by HurryStarfish** [comment]
Should it really be a metadata tag though? Until now, these are purely for other BlitzMax code to evaluate via reflection at runtime; you can write arbitrary strings in there. Making specific values in them influence how the compiler acts would be a pretty big change. (It also brings a few problems: What if someone uses "export" as a tag without knowing about the extra effect? It's not obvious and might go unnoticed.)
I think having actual syntax for it would be better, for example an `Export` keyword. When combined with a calling convention (`Function HelloWorld() Export "C"`), it would be reminiscent of how functions are imported (`Extern "C"`).

**Comment by woollybah** [comment]
Yes that may well be the way to go.
