### ISSUE TITLE
Auto-generate .def for function exports

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#349]
It would be nice if bcc could auto generate a .def when detecting exported functions, and apply any appropriate decorations as required (eg. for x86 stdcall functions that require @ args size suffix).

No additional decorations are required for x64 stdcall.

bmk could then use this when building the dll.

**Comment by Kerntrick** [comment]
What would the easiest (and least hacky) way to do this?  
Auto generating '@bmk statements in the source? 
collecting and then dumping the exports to the console after compilation and manually putting them in a def file?
