### ISSUE TITLE
Can't define infinity as a constant.

### ISSUE THREAD

**Issue by Kerntrick** [bmx-ng/bcc#350]
I'm building a module that defines:  **Const PositiveInfinityF:Float = 1.0 / 0.0**
In the generated ".i" file has the definition as: **PositiveInfinityF#=1.#INF0000#** and bcc doesn't like that.
Classic bmax used the term **inf#** 
I've tried the c constants of INFINITY, HUGE_VAL etc, in the ".i" file but that doesn't work.

Is this a bug or is there a way to rewrite this expression to bypass this error?

**Comment by HurryStarfish** [comment]
Sounds like a regression (#226).
