### ISSUE TITLE
.def-file generation misses non-decorated functions (stdcall, win32)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#352]
When creating a .dll with "Win32" exported functions, BCC exports functions according to the _stdcall_-scheme. Means it decorates functions so `function MyFunc() "Win32" exports" becomes `MyFunc@0`.

Results look like this:
```
LIBRARY mydll

EXPORTS
	Func@0
	OtherFunc@4
```
Using them in a programm requires to reference exactly these names ("Func@0")
As you are allowed to do "definition linking" you could also do this:

```
LIBRARY mydll

EXPORTS
	Func
	OtherFunc

	Func@0 = Func
	OtherFunc@4 = OtherFunc
```
Allowing you to reference to "Func" instead of "Func@0".

I patched BCC to emit such blocks too - but I am quite sure that may way of doing differs a bit to Bruceys.

**Comment by GWRon** [comment]
So I replaced two functions in "ctranslator.bmx":

```BlitzMax
	Method TransExportDef:String(decl:TFuncDecl, withApi:Int = True, linkNonDecorated:Int = True)
		Local t:String = decl.munged
		
		If withApi And decl.attrs & DECL_API_STDCALL Then
			t :+ "@"
			Local size:Int
			For Local arg:TArgDecl = EachIn decl.argDecls
				size :+ arg.ty.GetSize()
			Next
			t :+ size
			
			If linkNonDecorated
				t :+ " = " + decl.munged
			EndIf
		End If
		
		Return t
	End Method

...

	Method TransDef(app:TAppDecl)

		SetOutput("def")

		Emit "LIBRARY " + StripExt(StripDir(opt_filepath))
		Emit "EXPORTS"


		'non-decorated for STDCALL definitions
		If opt_arch = "x86"
			For Local decl:TFuncDecl=EachIn app.exportDefs
				If decl.attrs & DECL_API_STDCALL	
					Emit "~t" + TransExportDef(decl, False)
				EndIf
			Next
		EndIf


		For Local decl:TFuncDecl=EachIn app.exportDefs
			'link decorated function definition to non-decorated one?
			If opt_arch = "x86" And decl.attrs & DECL_API_STDCALL
				Emit "~t" + TransExportDef(decl, opt_arch = "x86", True)
			Else
				Emit "~t" + TransExportDef(decl, opt_arch = "x86", False)
			EndIf			
		Next
		

		Emit "~n"
	End Method
```
to emit a block of non-decorated functions first (if it is a stdcall thingy).

**Comment by woollybah** [comment]
I did have this in originally, but didn't think it was actually required.
Seems it is :-p

My implementation is slightly different. I'll commit it later.

Thanks!

**Comment by GWRon** [comment]
.def-format wise the code can be a lot cleaner (devorated line after nondecorated line) but I wanted both variants to be emitted as "block".

Will see how your commit looks like.
