### ISSUE TITLE
macOS Mojave setjmp/longjmp may be broken

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#355]
There appears to be an issue raising exceptions on Mojave.
From initial experimentation, it doesn't appear to "catch" the exception, and falls through to after the End Try.

I'll need to come up with some definitive examples, but currently MaxIDE in a new installation of BlitzMax segfaults because it can't find a file and doesn't handle the raised exception as it normally would....

I've been digging around for any cases of setjmp/longjmp issues on macOS, but haven't found much yet.

**Comment by woollybah** [comment]
Here's a small example for testing:
```blitzmax
SuperStrict

Framework brl.standardio

Print "Expected :"
Print "In Test"
Print "Before"
Print "In GetSomething"
Print "Caught"

Print "~nActual:"

Test()

Function Test()
	Print "In Test"
	
	Local s:String
	Try
		Print "Before"
		s = GetSomething()
		Print "After"
	Catch e:Object
		Print "Caught"
		Return
	End Try

	Print "End of Test"

End Function

Function GetSomething:String()

	Print "In GetSomething"
	
	Throw New TStreamReadException

	Print "End of GetSomething"
	
End Function
```

**Comment by GWRon** [comment]
Did you check with a "raw" C-example if the way of doing is still correct for the XCode you use?

And from there you can try to "unwind" back to NG/BlitzMax.

**Comment by woollybah** [comment]
Not yet. I want to replicate it first before I attempt to build an equivalent C version.
We are also using our own exception stack which adds another level of interestingness.

**Comment by woollybah** [comment]
As part of this, it may be worth using _setjmp/_longjmp instead, on macOS, which are versions which do not affect the signal mask. They are also apparently twice as fast as  setjmp, presumably because they aren't saving/restoring signal states.

**Comment by GWRon** [comment]
I was aware of the "own exception stack". So I wasn't strictly asking for a raw C-version of above's sample code, but something utilizing the custom exception solution directly (to see if it already fails there).

If you test without comitting: feel free to mail me the changes so I can try them out on "Yosemite" - to avoid breaking "[OS] backwards compatibility".

**Comment by woollybah** [comment]
It turns out the issue is caused by an "implicit int" declaration, from code introduced for the Finally support, which was only a problem under certain circumstances on 64-bit while catching an exception with a variable whose pointer was > 32-bit address space.
