### ISSUE TITLE
Illegal Type Expression - misleading

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#365]
If you place non-strict code in your file:
```BlitzMax
Local i = 0
```
Then the resulting error is "illegal type expression". It might be better to write in addition, that the type cannot be recognized and needs to get stated explicitely. 
Maybe it is that English is not my mother tongue but the current error is not that helpful for beginners and a bit too "ambiguous" (at least in my opinion).
So excuse if I cannot come up with a proper text for this kind of language error. 

"variable type not given"
"variable needs to be of a certain type"
"Strict requires explicit int definition"
...

**Comment by HurryStarfish** [comment]
Legacy BlitzMax says `Missing type specifier` in this case, which I feel is easier to understand, and also more accurate. When the compiler encounters a declaration without a parse-able type, then the type most likely wasn't "illegal", but simply forgotten. Other mistakes like `Local i:SomeTypeNameThatDoesntExist` or `Function F:Int` are already covered by other messages.
