### ISSUE TITLE
Local variable name within local scope of a same named variable allowed

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#374]
this is not strictly a "bug" but something vanilla does not allow. Behaviour is correct so it only should be threated as a bug if "compatibility" is desired.

```BlitzMax
SuperStrict
Framework Brl.StandardIO

For Local i:Int = 0 To 5
	For Local i:Int = 6 To 10
		Print i
	Next
Next
```
NG: compiled and executed correctly
Vanilla: `Compile Error: Duplicate identifier 'i'`

**Comment by HurryStarfish** [comment]
This is a feature called name "hiding" (or "masking" or "shadowing"). It exists in many forms in BlitzMax, and imo it is desirable. When you declare a variable (or function, or type, ...) name that already exists in an outer scope, the outer name is "hidden" by the inner one. This way you can, for example, declare and use a local variable in a function without having to care whether a global variable with the same name exists already.

I cannot confirm the compile error. My vanilla BlitzMax installation (at least the one on this laptop, which is 1.41) compiles that code without issue. It is a feature in vanilla too. What version of vanilla are you using? Maybe it happened to be broken in that particular one.

**Comment by woollybah** [comment]
It looks fine here (in both versions) too :-)

**Comment by GWRon** [comment]
Uhm ... it compiles here too.  Pretty odd - especially with the "explicit" error message I just copied.

@ feature
Yes, I know (and use it) and just posted as I got this error and thought it might be of interest regarding "vanilla compatibility".


Will close - and just give me a laugh by imagine how I look with a pretty puzzled face now.

**Comment by HurryStarfish** [comment]
Oh, maybe you forgot the `SuperStrict` at the top? When you use neither `Strict` nor `SuperStrict`, variables work quite differently due to the fact that you're not required to declare them. In that case, you'd indeed get the error you quoted.
But non-strict mode isn't supported in NG anyway, so it's nothing to worry about. :)

Maybe NG should force the declaration of either `Strict` or `SuperStrict` at the top of the file...
