### ISSUE TITLE
Accessing globals before created leads to exception instead of compile error

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#378]
```BlitzMax
SuperStrict
Framework Brl.StandardIO


'NG: not catched until execution:
'    "Attempt to access field or method of Null object" 
'Vanilla: Compile Error: Identifier 'Test' not found
Print Test.i

Global Test:TTest = New TTest

Type TTest
	Field i:Int = 10
	
	Method New()
		i = 20
	End Method
End Type
```

**Comment by HurryStarfish** [comment]
Before execution reaches the `Global` line, `Test` has its default value, which is `Null`.
In vanilla, the variable is inaccessible above that point, just like a `Local`.

This is part of #252.

**Comment by GWRon** [comment]
Seems you are right. Might close it now - but think it is kind of a "bumper" now - aka "increases awareness"
