### ISSUE TITLE
Sar causes internal error

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#386]
```
SuperStrict
Framework BRL.StandardIO

Print -2 Sar 1
```

**Comment by GWRon** [comment]
Just a small tutorial to narrow down the issue:
- In MaxIDE select the "verbose" option
- Try to compile your code
- see the params given to "bcc" eg. `path/to/bcc -g x64 -v -h -d -s -w -f brl.standardio -t console -p linux -o /path/BlitzMaxNG/tmp/.bmx/untitled1.bmx.console.debug.linux.x64.s /path/BlitzMaxNG/tmp/untitled1.bmx`
- use the part from "-g..." on and copy it into MaxIDE->Program->"Command Line"
- copy your bcc sources into "BlitzMaxNG/bin/bcc-source" and do a debug build+execute of "bcc.bmx" (there it should be able to find the BlitzMax path)

But ... dunno why it does not work for now - I just receive an internal error too, debugger does not catch it. When running "bcc.debug" via GDB it segfaults without leaving an backtrace.

**Comment by HurryStarfish** [comment]
> I just receive an internal error too, debugger does not catch it.

They're easy to locate with a debug build of bcc [as long as you remove the `Try` block in bcc.bmx](#337). I'll look into this one later.
It would make things easier if `InternalErr` had an additional "location" parameter though. Then bcc could add that to the printed message and it would be possible to find the location of the error in release builds too.

**Comment by GWRon** [comment]
Couldn't the internal error just "throw".. as "throw" should be able to get caught?

**Comment by HurryStarfish** [comment]
[It does](https://github.com/bmx-ng/bcc/blob/ebdf17914fcb46687ffe3d46b421024324051382/config.bmx#L85), but bcc.bmx catches it and turns it into a `WriteStderr`.

**Comment by GWRon** [comment]
There are some debugger constants to change... Maybe wrap the enabled ones into "?debug" to auto disable this stuff in debug builds...

**Comment by woollybah** [comment]
`Sar` appears to be completely absent from the binary math expression code :-)

**Comment by GWRon** [comment]
Seems to be one of the uhmmm "less used" functionalities among the NG users :-)


Aside of that @Hurrystarfish is right with the "internal error" being a bit too non-verbose.
