### ISSUE TITLE
Add Override property

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#390]
It has been decided (see https://github.com/bmx-ng/bmx-ng/issues/56) that it would be beneficial for BlitzMax to be able to declare a method as one which overrides another.

With the addition of method overloading in BlitzMax, it's now possible to change the signature of a base method without necessarily changing a previously overridden method in child type. In legacy BlitzMax this would raise an error, but with current BlitzMax the child method would become an overload, with the potential of subtle errors in user code.

By adding an `Override` property to methods (and functions), we can enforce the connection between the base and child methods, and raise an error should a change be made to the signature of the base method.

Here's a small example :
```blitzmax
Type T1
	Method M(s:Object)
	End Method
End Type

Type T2 Extends T1
	Method M(o:Object) Override ' <- Okay. T2.M overrides T1.M
	End Method
End Type

Type T3 Extends T1
	Method M(o:String) Override ' <- compile error. T3.M overloads T1.M
	End Method
End Type
```

Two new compiler flags are to be introduced to bmk/bcc, `override` and `overerr`, to compliment the new functionality.
* `override` will cause bcc to generate warnings for any overriden methods/functions but which **do not** the `Override` property.
 * `overerr` will cause bcc to fail compilation, rather than produce a warning.

For example, with `override` option enabled:
```blitzmax
Type T1
	Method M(s:Object)
	End Method
End Type

Type T2 Extends T1
	Method M(o:Object)
	End Method
End Type
```
will generate a warning for T2.M, because it was not declared with `Override`.
With the addition of `overerr`, this would result in a compiler error instead.

By default, bcc will build without warnings.
Use of `Override` on non-overridden methods will always generate errors.

**Comment by GWRon** [comment]
Sounds good to me.


During the last months NG developed by a huge bit. Thanks to your efforts and the hugely appreciated input of @HurryStarfish.

Just wanted to say that... To acknowledge the time you spend on the project.
