### ISSUE TITLE
Code order of Abstract, Final and Override

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#394]
```
SuperStrict
Framework BRL.StandardIO

New T2.M

Type T1
	Method M()
		Print "T1"
	End Method
End Type

Type T2 Extends T1
	Method M() Override Final
		Print "T2"
	End Method
End Type
```
This code results in the confusing error message `Compile Error: Identifier 'final' not found.`, because bcc expects `Override` to appear after `Final`, not before. I am not opposed to enforcing this order (imo "Final Override" sounds more natural than "Override Final"), but bcc should still check for both cases and display a specific error message if the order is wrong. This is especially important [if `Final` is allowed as an identifier](https://github.com/bmx-ng/bmx-ng/issues/56#issuecomment-462483564) (which, currently, [it actually is](https://github.com/bmx-ng/bcc/issues/383)), because if a function or method named `Final` is added to the code above, it will actually compile and call that function/method, which is most likely not intended by the programmer.
The same applies to `Abstract`.

**Comment by GWRon** [comment]
> it will actually compile and call that function/method, which is most likely not intended by the programmer.
If it compiles ... then this is a bug itself.
Multiple commands in one line are not allowed - except they are concatenated by a semicolon


```blitzmax
'not allowed
myfunction() myfunction()
'allowed
myfunction(); myfunction()
```

**Comment by HurryStarfish** [comment]
> If it compiles ... then this is a bug itself.
> Multiple commands in one line are not allowed - except they are concatenated by a semicolon

Not true. In vanilla BlitzMax (which is, after all, our reference implementation), semicolons and  even whitespace are completely optional in almost all contexts.
For example, try running this in vanilla, it's a perfectly valid program:
`SuperStrict Framework BRL.StandardIO Function F:Int()Print"F"Return 5End Function F()F()Input`

While it is of course not nomally a good idea to write code in this style, I consider the fact that NG doesn't conform to this a bug.

**Comment by GWRon** [comment]
So "if then" is the only exception? I only use the ";" when debugging some stuff and pasting in some "print":
`if x = 0 then print "fail";return False`

So ... ignore my post above if it is valid without semicolons (in many cases). Never really tried to write such "unreadable code" :-)

**Comment by HurryStarfish** [comment]
I think so - `Then` has the weird property of including everything until the end of the line (I wrote my own BlitzMax parser/compiler once and I remember `If` being kind of a headache for that reason).

> Never really tried to write such "unreadable code" :-)

It comes in handy when doing code golf challenges on Stack Exchange ;)
But sometimes also in "reasonable" code. For example, a lot of `Select` statements I write look somewhat like this (this is actual code from the afromentioned compiler):
```BlitzMax
Select Rose(signature.Arg[0]).Get("Keyword").Key
	Case "byte"   Return TType.ByteType
	Case "short"  Return TType.ShortType
	Case "int"    Return TType.IntType
	Case "long"   Return TType.LongType
	Case "float"  Return TType.FloatType
	Case "double" Return TType.DoubleType
	Case "string" Return TType.StringType
	Case "object" Return TType.ObjectType
	Default RuntimeError "unknown type"
End Select
```
And a lot of issues I report here on github have test code [like this](372).

**Comment by GWRon** [comment]
BlitzMax Extended ?
Bismuth (was my first hope for an "open blitzmax" some years ago - until dev stopped)?


You are right - select is one of the cases in which I skip adding a new line too ... never "recognized" that it does not need a ";" and thought it just behaves similar to the "one line if-then".

**Comment by HurryStarfish** [comment]
Bismuth was a project of [blitzforum.de](http://www.blitzforum.de) members to make a BlitzMax successor, but not mine.
Mine was sort of a pre-compiler, turning an "extended" version of BlitzMax into regular BlitzMax to be processed by bcc afterwards. The goal was to add features I always wanted but BlitzMax never got - such as interfaces, method/constructor overloading, lambda expressions, generics...
I dropped the project when I discovered the existence of NG and decided that it was the better way to improve the language.

**Comment by GWRon** [comment]
Yes was lurking around there (blitzforum.de) too (only reading) but preferred blitzmax.com at that time.

> Imo some for better, some for worse

Feel free to talk about thing you would like to improve/see improved. Maybe Brucey thinks the same about it - or never thought about it before.

NG improved a lot over the last years - I can remember Brucey's first tests and how "yay" we were that some stuff worked - with hundreds of bugs yet to come :-)

I am glad that the project has found an experienced coder with you - think it encourages Brucey to see someone who is capable of Pull Requesting some new features. Or one who files a bug report and fixes it at the same time. Thanks for your efforts.

**Comment by HurryStarfish** [comment]
Thank you :)

> Feel free to talk about thing you would like to improve/see improved. Maybe Brucey thinks the same about it - or never thought about it before.

An example of something to improve would be the type system, represented by issues #335 and #376.

Some things were just fundamentally different though. For example, I took a more declarative-style approach to parsing and transforming the code using [this library](https://github.com/Leushenko/TMeta-Parser), as opposed to the rather imperative NG bcc. The nice thing about this was that I ended up with a formal grammar for BlitzMax; changing the syntax (like to add new features) only required editing that file. The disadvantage was that it made it very hard to output helpful error messages for specific circumstances, which is easy in NG.
It also resulted in some *very* funky-looking code, like for example [this transformation to turn lambda expressions into regular functions](https://pastebin.com/4T0F1Sjx) :slightly_smiling_face:

**Comment by GWRon** [comment]
Shouldn't your knowledge of lexer/grammar generation ease the pain to create a language plugin for intellij or an other IDE?

Utilizing a 3rd party IDE would help a lot when it comes to android/ios/..targets (deployment) and might even be good for blitzmax newbies to not get frightened by the simplicity of maxIDE (you know...if the tools look cheap your assumptions of the language might get lowered too).

Do you have experiences there...or tried already to write a language plugin for one of these IDEs?


That funky code...looked not as funky as the NG generated C-Code :-)

**Comment by HurryStarfish** [comment]
> Shouldn't your knowledge of lexer/grammar generation ease the pain to create a language plugin for intellij or an other IDE?

Possibly, but so far I've never looked into that sort of thing... so no experience there.
