### ISSUE TITLE
Terminology: "Property"

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#395]
The warning/error message bcc now outputs for a forgotten `Override` says 
> Overriding method 'M' should specify 'Override' property.

I think the use of "property" is somewhat confusing here, since the term is normally used to refer to [a set of getter and/or setter functions presented as a variable/field](https://en.wikipedia.org/wiki/Property_(programming)). (Might also be worth considering as a feature someday?) Keywords such as `Abstract`, `Override`, `ReadOnly` are usually called "modifiers" instead. Imo we should adhere to this to be consistent with other languages.

**Comment by GWRon** [comment]
Maybe call it "declaration modifier" or "method|function declaration modifier"?

function declaration - name, signature, return value and modifiers/flags
function signature - name + param types to make overloading "distinctable" (so maybe namespace too)

**Comment by woollybah** [comment]
Yeah... I know property wasn't the terminology I wanted to use. But I'm old, and have trouble remembering my name... so... :hamster:

**Comment by HurryStarfish** [comment]
@GWRon 
"Modifiers" always refer to declarations, I believe, so"declaration modifier" might be redundant.
A (function) "signature" technically includes its whole type, which includes the return type as well.

**Comment by GWRon** [comment]
@HurryStarfish 
Thought return type is only of interest if overloading is interested in it ("strict programming"). Vanilla already allowed to alter the return types in overridden functions/methods of extended types - so return type seems to not be taken into account.

@ modifier
if the whole message is `Overriding method 'M' should specify 'Override' property.` and "property" is to replace, I think that "modifier" is not redundant. If the message was `Overriding method 'M' should specify 'Override' in its declaration` then yes. Am not "happy" with all the proposals as we still talk about a "beginner oriented" language - and overriding is something people have surely read about somewhen - even if they do not know what it is exactly. The error message above is not self-explaining and if the IDE does not "hint" them into the right direction they will only be able to solve that issue by using a search engine for this error.
Sometimes the BCC errors should "guide" the users on what it expects or how to solve an issue.

**Comment by HurryStarfish** [comment]
> if the whole message is `Overriding method 'M' should specify 'Override' property.` and "property" is to replace, I think that "modifier" is not redundant.

I didn't say that though, I just said that prefixing "modifier" with "declaration" would be redundant. In any case though, I think the new message (which doesn't mention "modifier" at all) is pretty clear in what the problem is and how it can be fixed.
