### ISSUE TITLE
local variable scope of for-loop-limits broken

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#401]
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Local i:Int = 5
For Local i:Int = 0 Until i
	Print i
Next
```

Vanilla:
```
Executing:untitled1.debug
0
1
2
3
4

Process complete
```

NG:
```
Executing:untitled1.debug

Process complete
```

**Comment by woollybah** [comment]
I really hope you are not writing code like that.

**Comment by GWRon** [comment]
I was almost tempted to write an excuse response already - that I do not write such code ;-)

Still it can happen if you have multiple for loops - and often use eg. "i" as temporary variable (similar to "j").

Nonetheless: as you see it works in vanilla - so there might be code hidden on some hard discs which does a similar thing.

**Comment by woollybah** [comment]
Hopefully I haven't broken anything else with this fix :-)
I'm sure you'll let me know otherwise...
