### ISSUE TITLE
Self.variablename accesses global if not defined

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#404]
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Global unknownfield:Int

Type TTest
	Method M(i:Int)
		Self.unknownfield = i
	End Method
End Type

New TTest.M(1)
```

without the global variable it correctly fails - but with its definition NG mistakingly accesses the global when utilizing `self`.

**Comment by woollybah** [comment]
The change is quite fundamental, although it's only two words... :-p
Testing hasn't appeared to have broken anything else though, but I'm sure you'll let me know otherwise!
