### ISSUE TITLE
Enforce Strict or SuperStrict?

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#405]
Is there a particular reason why NG doesn't mandate that files begin with either `Strict` or `SuperStrict`?
If neither is written, legacy BlitzMax defaults to non-strict mode, but non-strict mode does not exist in NG. So it doesn't help with porting non-strict legacy code, and it can lead to confusion if the keyword is forgotten, [like it probably did in this case](https://github.com/bmx-ng/bcc/issues/374).
An explicit error stating that either `Strict` or `SuperStrict` is required and that non-strict isnt supported anymore would imo be helpful.

**Comment by GWRon** [comment]
I second that (especially as my code files always contain `superstrict` already :-)).

Of course it might require changes to some "non-superstrict" module files - and some project files of the users. But maybe they use the chance to overhaul their code to make it even `superstrict`.
