### ISSUE TITLE
Hot Code / Live-editing

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#408]
Had the idea some days ago - and now on the syntaxbomb forums one linked to a AGK video exposing something similar (but with a ide syntax I do not really like).

Of course it is easier for an interpreted language approach to add such features - but couldn't we have some kind of "live editing" for BlitzMax?

Idea:
- you mark configurable pieces with special commands / comments
- bcc handles this content by adding two functions to set/get this variable
- bcc exposes that functionality (how?) so that external clients (the calling process - eg. the IDE or a special tool you have to "call" from within the IDE) could call the setters/getters of this variable
- IDE (or tools) can fetch a list of adjustable properties
- IDE would be able to adjust these variables the way they like (color pickers, file requesters, ...)

Edit: it does not help to write complete blocks of code "live" (this would be doable via exposure of everything to  scripting languages like LUA - and a re-evaluation after changing code) but it would allow to "fine tune" certain values - sprite positions, text values, ... stuff you might like to do when rapid prototyping.

Is that even possible or what do you think?

**Comment by woollybah** [comment]
No, this isn't very likely to work. You'd basically need every "module" to be a shared object. You could then load/unload those as required - but obviously you might have issues with global variables in a particular module. (globals are bad, btw).

Where "module" is the particular scope of something you'd consider suitably small to have in its own shared object.

**Comment by GWRon** [comment]
Hmm most people would not alter module code.. 
It is more for user code ... Simply said to alter positions of sprites and so on.

**Comment by HurryStarfish** [comment]
Well, the debugger could possibly be able to alter the contents of locals when halted at a `DebugStop`. Global variables and the fields of objects reachable through them, too - but that kind of falls apart in multithreaded programs. Furthermore, "hot swapping" of code like, say, in Java is impossible, since BlitzMax isn't interpreted or JIT-compiled.
But "altering positions of sprites" (for a game?) at runtime doesn't sound like something that should be done with debugging tools anyway. Seems more like something you'd want to write a map editor or use a scripting language for. Or maybe, if you're just quickly prototyping something very small, add a few lines of code to bind the sprite position to the mouse position and print the coordinates to the console or so...

**Comment by GWRon** [comment]
Yes I've read about the debuggers being capable of such things.

I was not talking about replacing complete code blocks or expressions - for this I would - as said before - prefer to export it to LUA and access it via a getter instead of the straight variable. That way one could eg. update the AI during playing the game.

So yes - of course most probably it would be used for games - which was the initial target group for BlitzMax. And I think it should still target them - those dudes who want to tinker a bit here and there, doing not-that-funky-looking little games (or unfinished prototypes). They like stuff allowing them to move things around while the game is "running" (or paused in that moment).
Of course you could bind to mouseX()/mouseY() - but what happens if you want to move the second entity during the same application run? Yes, handle a keyDown() - but now we want to adjust the third, fourth, ... seems we need mode to do a mouse select and then a shortcut to bind to mouseX()/mouseY(). Think you got it: stuff can get complex especially if they interact.

Of course stuff can get way easier if the language is interpreted (Lua - or gdScript in Godot) but I just hoped there is a way to allow some "simple" stuff bringing in convenience for some users.

More advanced projects won't have that much benefits of it as they layout stuff in 3rd party programs or have functionality in their engines allowing to reload configuration files etc.
It's as said - just to ease the pain for all these tinkers who want to play a bit with BlitzMax (and MaxIDE).
