### ISSUE TITLE
Abstract base type in different file with Field does not keep Field's value in concrete subclass from other file

### ISSUE THREAD

**Issue by DivineDominion** [bmx-ng/bcc#417]
Yeah this is weird :)

When you concatenate the 2 type definitions and the main file into one, everything works fine.

When you split the abstract type definition into its own file, its Field value is not retained. In this example, the integer Field `x%` always is `0`.

I would expect it to work the same, of course, no matter the location. :)

---

Abstract type:

```bmax
SuperStrict

Type TAbstr Abstract
    Field x%

    Method New(x%)
        Print "New(x%)"
        Self.x = x
    End Method

    Method Foo%() Abstract
End Type
```

Main Program:

```bmax
SuperStrict

Import "abstract.bmx" ' Paste contents here to fix it

Type TConc Extends TAbstr
    Method Foo%()
        Return Self.x
    End Method
End Type


Local obj:TAbstr = New TConc(4567)
Assert obj.Foo() = 4567 Else "Expected 4567 but got " + String(obj.Foo())
```

**Download project files:** [bmax-broken-abstract.zip](https://github.com/bmx-ng/bcc/files/3030173/bmax-broken-abstract.zip)

--- 

Platform: macOS 10.14.3  
bcc[ng] Release Version 0.99

**Comment by woollybah** [comment]
I guess the issue is that the New() of the abstract type doesn't appear to be executed.

**Comment by woollybah** [comment]
Hopefully this doesn't break anything else.

**Comment by DivineDominion** [comment]
Couldn't we write regression tests for the compiler?

**Comment by GWRon** [comment]
There is https://github.com/GWRon/SimpleCodeTester to allow writing samples which could get test-compiled in an automated manner.
Unit tests won't help as it is a module/translation issue not the raw functionality of BCC.

Am not sure but think Brucey have had some issues with SCT eating input/output (which is based on pub.mod/freeprocess.mod issues)

**Comment by HurryStarfish** [comment]
I was the one having problems with that. (Or maybe we both did.)
But yes... we probably should get into the habit of maintaining the tests, adding new ones when bugfixes are made and running them regularly when changes are committed...

**Comment by DivineDominion** [comment]
If isolated testing won't work, what about automating at least some end-to-end tests? I'm thinking along the lines of writing code for this pseudo-code:

```
Test abstract type constructors are called when the abstract type is in another file
    Given file1.bmx with "..."
    Given file2.bmx with "..."
    When bcc is run
        Its exits with a success code
    When I run the executable
        It exits with exit code 0
```

**Comment by GWRon** [comment]
As said you can write sample projects (so multiple files - imports, includes, assets, ...) and auto-test all of these projects with SCT / SimpleCodeTester.
If output differs from the desired one then this is printed.

We used that tool in the past to get the basics "bug free". But now we reach a stage in which most bugs become ... hard to find (rare usage).
Maybe we should really get SCT to work properly (it did for me in the past but somehow there might be issues here and there :-)) and spend some time adding samples for the bugs reported lately.
Some bug samples  might be "joined" to save on test time.
