### ISSUE TITLE
Native commands and access to blitzmax variables

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#421]
Let's assume I define something in BlitzMax and want to use that in a native command - how would I do that as I do not know the "munged" name after the C code is generated?

```BlitzMax
SuperStrict
Framework Brl.StandardIO

global myNumber:int 

'!printf("hi %i", myNumber);
```
This does not work now, as "myNumber" is not known in the C code (it is _m_filename_myNumber or so).
Maybe add some "Helper" in which you wrap "myNumber" so it gets replaced then with the munged variable name?

```BlitzMax
SuperStrict
Framework Brl.StandardIO

global myNumber:int 

'!printf("hi %i", $$myNumber$$);
```
or whatever isn't allowed in C (avoids mistakingly replaced stuff).

Or is there an even simpler way of achieving that?

**Comment by HurryStarfish** [comment]
If that's an option for you, you could declare `myNumber` in a C file and import it with an `Extern` block on the BlitzMax side.
Alternatively, you could just use the munged name `_m_filename_myNumber`. Of course, that's pretty dirty and fragile to future change, but so is "native" code in general, so...

**Comment by GWRon** [comment]
I am not using the "native" functionality. Just tried that out when someone in the syntaxbomb.com forums asked for help when his comments began with an exclamation mark ;-)

Having an option to pass a blitzmax variable (at least pointers, numbers, strings ..) could come handy if you eg want to utilize existing c functions (printf and the likes).

**Comment by HurryStarfish** [comment]
Since the "native code" feature is inherently compiler-specific (it relies on NG compiling to C), I wouldn't recommend using it in regular code. I do however find it useful for experimenting and debugging purposes. In that case, I normally use `Local`s, which are pretty easy to share with "native" code because they're munged by simply adding a `bbt_` prefix to the name (unless there are name collisions, in which case a number is added at the end too):
```
Function F()
	Local i:Int = 5
	'! printf("%d\n", bbt_i);
	'! fflush(stdout);
End Function
```
```
Function F()
	Local i:Int = 5
	If True Then
		Local i:Int = 7
		'! printf("%d\n", bbt_i);
		'! printf("%d\n", bbt_i2);
		'! fflush(stdout);
	End If
End Function
```

**Comment by GWRon** [comment]
duplicate of #358
