### ISSUE TITLE
Concatenating String + object = non-self-explanating error message

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#424]
```BlitzMax
SuperStrict
Framework brl.Standardio
Import Brl.AudioSample

Local o:Object = New TAudioSample
Print "o is: " + o 'thought it uses the "ToString()" result
```

Vanilla: `Compile Error: Operator ''+'' can only be used with numeric types`
NG: `Compile Error: Illegal expression type.`

Of cource the vanilla message is also misleading but it hinds in the right direction:
`Compile Error: Operator ''+'' can only be used with numeric types or strings`.

Yet I have to remember that somewhen later operator overloading etc could render this kind of message invalid/incorrect too.

**Comment by GWRon** [comment]
BTW: double single-quotation marks.

**Comment by HurryStarfish** [comment]
Yeah, the error should be `Operator + is not defined between types 'String' and 'Object'` to be consistent with the error message for UDTs on the left hand side since a17945d27866a123969ba76ff483839d9f45f043.
(You should get a message like this if you swap the operands.)
