### ISSUE TITLE
Method call on delegate object invokes the wrong method

### ISSUE THREAD

**Issue by DivineDominion** [bmx-ng/bcc#428]
I found my program to be caught in an infinite loop of method calls until program crashes. The weird thing is that neither of the 3 methods involved according to the stack trace call one another. They are completely unrelated. My best wild guess is that a pointer has gone haywire.

I'm not working in a multi-threaded environment. The problem I experience looks very much like a race condition, but isn't, apparently.

Both objects caught in this loop have strong references to each other. One owns the other, and registers itself as a callback delegate, creating a cycle that is broken when the interaction completes.

I'm not sure how to narrow this down because it's so awkward. Will try to reproduce with a test project. But any tips about how I can debug this and help pin-point the issue are much appreciated!

---

Here's the debug stack view after a couple of continues:

![Screenshot 2019-04-09 at 15 27 47](https://user-images.githubusercontent.com/59080/55804159-100b6d00-5adc-11e9-86c5-c28f1d7aca55.png)

# Call Details

I do have an event listener:

```bmax
AddHook EmitEventHook, HandleKeyboardInput

Function HandleKeyboardInput:Object(id:Int, data:Object, context:Object)
    Local responder:CTResponder = FirstResponder()
    If responder <> Null
        Local event:TEvent = TEvent(data)
        Select event.ID
            Case EVENT_KEYUP responder.KeyUp(event.Data)
        End Select
    End If

    Return data
End Function
```

That's about the only declarative part. "View" objects put themselves on the `_responderStack:TList` and then the topmost one gets all the global events.

The `CTResponder` interface offers `keyUp` and is implemented in a base class `CTControl` that provides a couple of methods as callbacks. Child classes can override these empty callbacks to implement functionality. When a confirm key (e.g. Enter) is pressed, a concrete type overrides and implements `ConfirmSelection()`:

```bmax
    Method ConfirmSelection()
        If Not Self.delegate Then Return
        Local item:CTMenuItem = GetSelectedMenuItem()
        ' DebugStop()
        Self.delegate.MenuDidSelectMenuItem(Self, item)
    End Method
```

This is a menu with a cursor that sends an associated object (`delegate`) a callback message.

This works fine until I get to 3 layers of objects or so for some reason. When I `DebugStop` there, step over to the delegate callback, and then step into it, `MenuDidSelectMenuItem` never gets called on the delegate.

Instead, its `Draw` method is called. I have no clue why. There is no default implementation of `KeyUp` or `ConfirmSelection` that calls the `Draw` method. If I don't stop and let this run, I end up with an infinite loop of:

    menu#ConfirmSelection -> delegate#Draw (-> parent class #Draw) -> menu#ConfirmSelection -> ...

Note that 

- the `delegate` owns the `menu`
- the delegate/owner would be forwarding drawing commands to the menu, but isn't, so it aborts earlier
- during the `Draw` call, `ConfirmSelection` is called again before the menu would be drawn

```bmax
    Method Draw(dirtyRect:CTRect)
        Print("Draw SplitListView")
        Super.Draw(dirtyRect)        '''' This line is marked by the debugger, so it doesn't seem to get beyond this point

        ' ... call menu.Draw() ...
    End Method
```

The base view class implements drawing as such:

```bmax
    Method Draw(dirtyRect:CTRect)
        If Not Self.isOpaque Then Return
        If Not Self.backgroundColor Then Return

        backgroundColor.Set()
        dirtyRect.Fill()       ''' This line is marked by the debugger, so it reaches the end of the method?
    End Method
```

There is no apparent connection from `ConfirmSelection` to `Draw`. Neither one calls the other. Since I'm operating on a single thread, drawing on the game loop doesn't get in the way, either. And if it did, it wouldn't call the `ConfirmSelection` method.

I wonder if the method dispatching went wrong here. Maybe the pointer to the delegate method is for some reason set to the draw method.

The call at the end of `__m_CTMenu_CTMenu_ConfirmSelection(struct _m_CTMenu_CTMenu_obj* o)` looks innocent enough:

```c
	(((struct _m_CTMenu_CTMenuDelegate_obj*)((struct _m_CTMenu_CTMenuDelegate_obj*)bbNullObjectTest((bbt_ = ((struct _m_CTMenu_CTMenu_obj*)bbNullObjectTest(o))->__m_ctmenu_ctmenu_delegate ))))->clas)->m_MenuDidSelectMenuItem_TCTMenuTCTMenuItem((struct _m_CTMenu_CTMenuDelegate_obj*)bbt_,(struct _m_CTMenu_CTMenu_obj*)o,(struct _m_CTMenuItem_CTMenuItem_obj*)bbt_item);
```

And other occurences of the pointer in the C code of that file seem to be related to offset calculations and setting it to Null.

**Comment by woollybah** [comment]
It could be an issue with the interface vtable where the wrong entry is called?

But it's hard to tell from here ;-)

Chucking some `Print` statements can often help get an idea of the call hierarchy.

There is a `PROFILER` config flag (bcc/config.bmx) that can be enabled to dump out every function call - but you need to be very careful about building everything with that option enabled. I maybe should make it a command-line opt instead.. then you can do something more fine-grained with it...

**Comment by DivineDominion** [comment]
I tried caveman debugging with log entries :)

Yeah, that's the weird thing: It starts at `ConfirmSelection`, then jumps to `Draw`, then starts at `ConfirmSelection` again -- but no code that is supposed to call `ConfirmSelection` is called. (There's only `KeyUp` which is invoked as I showed above.)

`ConfirmSelection` is (1) fetching an item from an internal array, with success, and then calls the delegate method. But that one is never called. The very call of the delegate method is highlighted in the debugger, but the `Draw` method is put on the call stack _instead._

Will try the profiler. Is there a way to use LLDB on the Mac with this with some success?

**Comment by HurryStarfish** [comment]
I vaguely remember encountering something like this before. It occurred in connection with [this](https://github.com/bmx-ng/brl.mod/issues/85), so I believed that that bug was the cause. But maybe it wasn't and it's related to this.
If I remember correctly, in my case, I had a call to one of methods (Draw, Update or something similar) inexplicably jump into some event handling code in the standard library. It might be a coincidence, but since the use of `BRL.PolledInput` is something mine and @DivineDominion's code have in common, maybe there's something wrong with that module or one of its dependencies.

**Comment by DivineDominion** [comment]
I managed to isolate the components and the setup to some extent.

Navigate with arrow keys. Select with Enter/Space.

Heres version 1 where when you hit Enter/Space, the DebugStop puts you right before the delegate method call. When you step into that call, though, you end up at `CTSplitView#Draw` instead.

[v1-jumps-to-draw.zip](https://github.com/bmx-ng/bcc/files/3062231/v1-jumps-to-draw.zip)

Then I thought: what if I remove the CTView base class and don't delegate to `Super.Draw`? Turns out you will _then_ end up in a call to `CTControl#KeyUp` instead.

[v2-jumps-to-keyup.zip](https://github.com/bmx-ng/bcc/files/3062232/v2-jumps-to-keyup.zip)

No matter what, the delegate method is not called.

Hope this helps to narrow it down already!

**Comment by woollybah** [comment]
Thanks for the examples.

**Comment by DivineDominion** [comment]
I tried to use `KeyHit` instead of event hooks, but that produces the same problem as v2.

[v3-polled-input.zip](https://github.com/bmx-ng/bcc/files/3062264/v3-polled-input.zip)

**Comment by GWRon** [comment]
Remove the "self" in this MenuDidSelectMenuItem() line:
```BlitzMax
    Method ConfirmSelection()
        If IsEmpty() Then Return
        If Not Self.delegate Then Return
        Local item:String = GetSelectedMenuItem()
        DebugStop()
        self.delegate.MenuDidSelectMenuItem(Self, item) '<---
    End Method
```

```Blitzmax
    Method ConfirmSelection()
        If IsEmpty() Then Return
        If Not Self.delegate Then Return
        Local item:String = GetSelectedMenuItem()
        DebugStop()
        delegate.MenuDidSelectMenuItem(Self, item)
    End Method
```
And then debugger lands right in the right method call when "stepping in". Maybe that helps Brucey to find the bug.

**Comment by GWRon** [comment]
Also important: your debuglog already shows that `MenuDidSelectMenuItem` is called even with `self`. So it seems to be a problem with the debugger-code.

**Comment by DivineDominion** [comment]
Interesting! On my machine, the DebugLog in the delegate method is not executed (at least I don't see anything in the MaxIDE console apart from the "Draw" outputs)

**Comment by GWRon** [comment]
Yes it is not called if I do the actual "step in". It is printed when I just click the green continue button to continue processing.
So the actual "broken debugger thing" leads to a different execution it seems.

**Comment by DivineDominion** [comment]
1. Yes, removing the `Self` from `Self.delegate` does the trick!
2. Stepping into the call with the debugger, it never produces the DebugLog output -- in none of the 3 versions I uploaded here. I wonder why it does on your device.

**Comment by GWRon** [comment]
As said, it does only output if I do not step into but just continue. So the "step into" borks up the whole thing and reroutes functionality (you can check this by replacing debugLog with a print - just in case something controls if a debuglog can happen there or not).

**Comment by DivineDominion** [comment]
Oh, mis-read that sentence. Tried again: Neither stepping-in nor continuing from the IDE print anything, no matter if I DebugLog or Print. 🤷‍♂️
