### ISSUE TITLE
Bad overload generation depends on order

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#431]
# Bug Report

Depending on the order of the overloaded methods, the bcc may generate duplicate entries.
```blitzmax
SuperStrict

Framework brl.standardio

Type TMyTypeBad

	Method test(ty:TMyTypeBad)
	End Method

	Method test(obj:Object)
	End Method
	
End Type

Type TMyTypeGood

	Method test(obj:Object)
	End Method

	Method test(ty:TMyTypeGood)
	End Method
	
End Type
```

Please provide the steps to reproduce and if possible a minimal demo of the problem, for example by attaching a zip file to this issue.

## Expected Behavior 

The code compiles.

## Actual Behavior

The first type is generated incorrectly, apparently due to the order of the methods.
It may be because of the type hierarchy.

**Comment by HurryStarfish** [comment]
Related to #372?
