### ISSUE TITLE
Consider support for hex escape sequences in strings

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#432]
C/CPP supports the concept of escaped characters in strings using the notation `\xNN`, in which `NN` is a sequence of hex digits representing a character code. For example `\x1b` is ascii 27 - escape.
In BlitzMax, to add an escape character to a String, you need to do something like this 
```
"Some text " + Chr(27) + " here."
```

If we had a similar option for providing escape sequences, the code could be written as
```
"Some text ~x1b here."
```

The escape parser would accept every hex character `(0-9 a-f)` after `~x` as a sequence for encoding into the string.

**Comment by GWRon** [comment]
For the sake of simplicity an option for integer char codes instead of hex...would be cool too.

**Comment by HurryStarfish** [comment]
In that case, the same prefixes for specifying the base as regular integer literals would be convenient. 
 `~27` for a decimal integer code, `~$1b` for hex, `~%11011` for binary. Except... then it wouldn't know where that number ends and where the string literal continues, so some sort of termination char would also be needed. Maybe parentheses?  `Print "~(27), ~($1b) and ~(%11011) are all the same character!"`

**Comment by GWRon** [comment]
That is the benefit of the hex values - if you only allow limit it to "\xNN" (0-255). You could now define that integer "~iNNN" is the only type recognized,  so "~i001" would be 1 (needs leading zeros).

If you wanted to allow a multitude of numbers you could make it pretty complex:
"~i{n(nnn)}" so as you are saying opening a bracket containing the value.

Can imagine how @woollybah already sighs for us overcomplicating a simple "do you want to have support for escaped hex numbers from 0-255" question :)

**Comment by HurryStarfish** [comment]
> That is the benefit of the hex values - if you only allow limit it to "\xNN" (0-255)

Yeah. Although they also have  the disadvantage of needing a leading zero for codes < 16 though, which might in theory lead to accidents.

But to widen the scope a bit: how about the ability to directly insert variables and expressions in to a string, aka [string interpolation](https://www.c-sharpcorner.com/article/understanding-string-interpolation-in-c-sharp/)?
If this were to be implemented, maybe it would be a better use for the parentheses i suggested in the previous post:
```
Local name:String = Input("What is your name? ")
Print "Hello ~(name)!"
```
```
Type TTest
	Method ToString:String()
		Return "TTest"
	End Method
End Type
Local a:Int = 2
Local b:Int = 3
Local o:Object = New TTest
Print "a + b is ~(a + b) and o is ~(o)"
' outputs "a + b is 5 and o is Test"
```
Do you think this would be useful, or too much effort?

**Comment by GWRon** [comment]
I thought about that too ... but then I assumed the reply will be something containing "immutuable string", "constants" or just "unnecessary complexity" :-)

Yet I would not say no to such a feature.

**Comment by woollybah** [comment]
`NN` was just an example. As stated in the last paragraph, it would accept a sequence of N number of valid characters as the value. An invalid character would terminate the sequence, so `1bx` would only count the first two hex characters.

Okay... I thiink `~27`, `~$1b` and `~%11011` are acceptable values.

Yes, I think `~()` might be useful too, but for simple characters, I'd prefer not to have to also add `()`.

**Comment by GWRon** [comment]
If you add a support for "dynamically wide" numbers (so read in a number/code until an invalid character is found) then you need to tackle "numbercode[nospace]number".

The following example is a bit ...artificial ... but assume you want to write "10d" in hex. It would become "~x0fd" which could... get converted to 253 if done wrong. If it was "85dd" (a lovely value? ;-)) then the string would be "~x55dd" - still a valid hex number.

To avoid that I suggest to have some kind of "no width"-escape char "~s" or so. This is something we could add between an "escape char consisting of more than one character" and the continued string.

**Comment by HurryStarfish** [comment]
> but then I assumed the reply will be something containing "immutuable string", "constants" or just "unnecessary complexity" :-)

It wouldn't change anything about immutability.
As for const-ness, you're right, I didn't think about that. A string literal containing expressions like that would only be constant if these expessions are constant as well. This wouldn't be a problem for the compiler to figure out, might be (slightly) counter-intuitive to the user though.

> Yes, I think ~() might be useful too, but for simple characters I'd prefer not to have to also add ().

The reason I suggested that is so the compiler can tell where the sequence ends. Otherwise `~27` could be either `Chr(27)` or `Chr(2) + "7"`. Leading zeros wouldn't be practical for decimal and binary values.

**Comment by GWRon** [comment]
> The reason I suggested that is so the compiler can tell where the sequence ends. Otherwise `~27` could translate to either `Chr(27)` or `Chr(2) + "7"`. Leading zeros to pad the number to a fixed length wouldn't be practical for decimal and binary.

This is why Brucey suggested to add characters until an invalid character was found - which is not working in your `chr(2) + 7` example - except with a "non space" character or your suggested brackets.

PS: it is cool to watch you editing your post ;-)

**Comment by HurryStarfish** [comment]
> This is why Brucey suggested to add characters until an invalid character was found

Not sure how big of a deal it is, but technically this would break backwards compatibility. This is currently valid code and would behave differently after the change:
```
Local str:String = "0~01~02~03"
For Local s:String = EachIn str.Split("~0")
	Print s
Next
```

**Comment by GWRon** [comment]
If ~0 was valid before then any numeric addition needed a prefix..like ~i10 or ~b01.

**Comment by woollybah** [comment]
Nevermind... BlitzMax already supports embedding of unicode characters...
```blitzmax
SuperStrict

Framework brl.standardio

Print "~65~"
```
Which is fine for my purpose.

**Comment by HurryStarfish** [comment]
That's... a feature I never saw before. And I guess that settles it. Good to know :slightly_smiling_face: 

In that case, might as well add the bin and hex variants like this too, I guess?
```
Print "~65~"
Print "~$41~"
Print "~%1000001~"
```

**Comment by woollybah** [comment]
Well, you can never have too many undocumented features!

**Comment by GWRon** [comment]
Your chance to extend the documentation ;-)

**Comment by woollybah** [comment]
Indeed :-)
