### ISSUE TITLE
release current version on blitzmax.org

### ISSUE THREAD

**Issue by DivineDominion** [bmx-ng/bcc#433]
With the rectnt fixes that definitely improved the usefulness of bmax-ng for my project, I think it'd be great to have a public release for all platforms to use the new bcc myself make it easier for other developers to obtain a working package.

---

For future releases:

- Is this cumbersome to do? Could this be automated via Travis CI or anything similar?
- To automate, version tags on the repo would be useful: then you can checkout the repo at tag X.Y.Z and bundle things up. That's more human readable than commit references. (E.g. release v0.123 consists of `bcc@0.123.456` and `bmk@0.5656` etc.)

If somebody could walk me through the process on every platform once, I'd volunteer to help set this up as an automated process with e.g. a Travis CI build script if that's possible.

**Comment by GWRon** [comment]
Think @woollybah  could move this issue to [bmx-ng/bmx-ng](https://www.github.com/bmx-ng/bmx-ng).

The linked repo contains some script to auto-download latest version of bcc, bmk etc - yet it is outdated as "sdl.mod" and other stuff now belong to the official packages.

Regarding Travis (and other services) there was an issue started by @woollybah  concerning AppVeyor bmx-ng/bmx-ng#28

For Mac builds you always need at least a Virtual Machine running an OS X or better real hardware. Cross compilations for Windows and Linux should be doable from there. Else you would need to have these installed too.

Thought Brucey has had laying around an old mac mini - should do as build bot / build slave.

**Comment by DivineDominion** [comment]
Makes sense to move the issue!

If you e.g. use Travis CI, you can start up a job in a macOS machine. No need to set up and run a VM manually. You basically just add a config file with the OS version you need, run pre-install scripts (like installing build tools) and then compile and package up the result on success.

**Comment by DivineDominion** [comment]
The scripts that exist don't look like they can create a complete release from scratch. The `setup_install.script` file is more promising, but wasn't touched in ages and is set to raspberrypi by default :)

@woollybah What can we do to help you prepare a release now and in the future? 

I'm asking now because the German BlitzForum is running a code competition and bcc v0.99 still has some annoying bugs.

**Comment by GWRon** [comment]
You could extend the script :-)

Basically all you need to do (with a working bcc/bmk) is to update the bcc and bmk sources and the modules..and to compile bcc and bmk then.

Problems arise when you run into the hen-egg problem (bcc depends on module changes... modules depend on newer bcc).

**Comment by DivineDominion** [comment]
@woollybah I tried to fetch and build a new version using `./setup_install.script` with the latest stable v0.99 from the website, using `PLATFORM=macos` and `CPU=x64` -- but compilation fails because the `Override` keyword isn't supported by that compiler version.

Could you please either provide a new and working build to the website, or tag compatible versions of bcc/bmk/pub.mod/brl.mod with the same tag so I can checkout that tag first, then progressively update to the next release of HEAD?

**Comment by GWRon** [comment]
For now you could build the new BCC with your old setup. The new BCC then understands `override` (and `enum`). Then update bmk brl pub sdl... and it should work.

You are right about tagging "releases" on all contained modules. Or at least to link revisions in the release details

**Comment by DivineDominion** [comment]
Compiling BCC fails already: `./bmk makeapp -a -r -standalone -l $PLATFORM -g $CPU -o ../src/bcc/bcc ../src/bcc/bcc.bmx` so this process is kind of broken. I'd love to help with the tooling and support this project. But if getting the tools doesn't work out of the box, all of this gets cumbersome. That's why I thought @woollybah might upload a new release since he's in the fortunate position of being able to do this rather quickly.

**Comment by GWRon** [comment]
So what error do you get?

If for now your only intention was to have the "bleeding edge version" (aka most current):
For now you can avoid this build-thing if you installed the latest release for your OS (and on Mac you will have to build MaxIDE via the provided script in the release).
- install latest release
- download latest BCC
- compile BCC with your release (in console mode)
- replace releaseBCC with compiledBCC
- download latest BMK, brl.mod, pub.mod, sdl.mod, ... (all the mod-folders within NG/mod you are using)
- compile latest BMK
- override the *.bmk files in "NG/bin" with the ones of "bmk.git" (there is a .bmk file which is not existing in the release NG ... do not copy it except you know what you are doing)
- override releaseBMK with compiledBMK
- rename the modules in "/mod" to "modulename.mod.bak" (or delete them)
- copy over the extracted modules you just downloaded (make sure to not have "brl.mod-master/brl.mod-master/brl.blitz" but just "brl.mod/brl.blitz" - so check subfolders, depends on your unzipping and downloading process)
- optional: download newest maxide and build that too (+ overriding the existing MaxIDE.app then)

You should now have the latest "bleeding edge version".
