### ISSUE TITLE
Struct initialisation probably does too much work

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#436]
When a struct is created, all the fields are individually set to their type-specific null value.
This is probably overkill, as we should be able to set all fields to zero where the struct is created initially. Then only the non-primitive and user-defined inits need to be set.

Example.
```blitzmax
SuperStrict

Framework brl.standardio

Local s:STest = New STest


Struct STest

	Field x:Int
	Field y:Float
	Field z:ULong

End Struct
```
Generated
```c
void __m_STest_New(struct _m_STest* o) {
	o->__m_stest_x = 0;
	o->__m_stest_y = .00000000f;
	o->__m_stest_z = 0ULL;
}
struct _m_STest _m_STest_New_ObjectNew() {
	struct _m_STest o;
	__m_STest_New(&o);
	return o;
}
```

Proposed
```c
void __m_STest_New(struct _m_STest* o) {
}
struct _m_STest _m_STest_New_ObjectNew() {
	struct _m_STest o = {0};
	__m_STest_New(&o);
	return o;
}
```

**Comment by HurryStarfish** [comment]
Hmm, I've taken a look at struct initialization, and it appears to currently be bugged in multiple ways. Firstly, initialization does not occur properly for structs without any fields whose type is a class. For example, this
```
Struct STest
	Field i:Int = 5
	Field s:String = "hi"
	Method New() Print "new" End Method
End Struct

Local x:STest
```
prints "new" and produces an instance containing with `x.i = 5` and `x.s = "hi"` like you'd expect, but this
```
Struct STest
	Field i:Int = 5
	Method New() Print "new" End Method
End Struct

Local x:STest
```
does not print anything and produces an instance with `x.i = 0`.

Secondly, the element instances of arrays of structs aren't initialized at all, no matter what the struct contains. `Local x:STest[3]` leads to an array with three instances whose i = 0 and whose s is a null pointer (which crashes the debugger when trying to examine it using a `DebugStop`).

So the `= {0}` optimization can only be done if all of the struct's fields are of primitive types and without any field initializers (by which I mean `= xyz` written after the declaration) that assign something else than 0. But even with initializers present, initialization could still be translated to a `{}` list in C. For example, the struct from my first example could be initialized with `= {5, &_s0}` before running the constructor.
For arrays, this would have to be done for all elements on array creation, or when changing their size via slicing.

**Comment by woollybah** [comment]
You'll probably want to build bcc before applying the changes to brl.
