### ISSUE TITLE
Private New w\o parameters favored over public New with paramets with default values

### ISSUE THREAD

**Issue by DivineDominion** [bmx-ng/bcc#439]
# Bug Report

Public `New` initializers/cosntructors with all parameters sporting default values will not be executed if there is an empty`New` available.

My attempt at hiding the default constructor, boiled down:

```blitzmax
Type Foo
    Private
    Method New()
        Print "private new"
    End Method 

    Public
    Method New(parameter% = 0)
        Print "public new with " + String(parameter)
    End Method
End Type

New Foo()
```

## Expected Behavior 

- Public `New` with the parameters is called

## Actual Behavior

- Private `New` with empty parameter list is called

## Environment

- Operating System: macOS 10.14
- Output of `bcc -v`: v0.104

**Comment by HurryStarfish** [comment]
Just like `Private` at top-level, using `Private` inside a class does not hide its members from other code in the same source file.
So if you declare `Foo` and call `New Foo()` in the same file as in your example, it doesn't make a difference whether the constructor is private, protected or public. However, if you call `New Foo()` from a different file which `Import`s the file declaring `Foo`, then it does.*
So the specific behaviour you're describing is not actually a bug, but working as intended.

***...However**, I just realized that what I just described isn't actually functioning: if `Foo` is extracted to a separate file and imported, the private constructor _still_ gets called. This is definitely a bug. Only happens with constructors, not with regular methods or functions.
Also, in the one-file version of the code, swapping the two constructors around (`New(parameter% = 0)` before `New()`) produces an "Unable to determine overload to use" error, while the original code (`New()` before `New(parameter% = 0)`) does not. That's another bug. Also happens with regular methods and functions. Reminiscent of #291, #393.

**Comment by woollybah** [comment]
The commit doesn't fix the specific issue as reported, but should cover the issues noted in the comment by @HurryStarfish.

**Comment by DivineDominion** [comment]
If the main issue isn't fixed, would it make sense to reopen the issue?

**Comment by GWRon** [comment]
Either reopen...or create a new issue if you feel the need for a more concentrated discussion about it.

Bruce likes it when issues pop up like daisies in spring :-p

**Comment by woollybah** [comment]
The main issue, as you described, is not an issue, it is the way BlitzMax works with regards its use of `Private`/`Protected` accessors. `Private` does not hide a method from access within the same file.
With the latest code, however, the call to `New Foo()` should now fail because the compiler cannot determine which of the two `New()` methods to call.

**Comment by DivineDominion** [comment]
Oh my problem wasn't with single-file access. I spread my code with 1 file per type, usually. But if the underlying problem of compiler confusion is now bubbling up as a compile  time error, I'm fine with that 👍
