### ISSUE TITLE
error: expected expression before '{' token

### ISSUE THREAD

**Issue by braxtonrivers** [bmx-ng/bcc#449]
When rebuilding these graphics modules brl, sdl, gfx etc it results in the following error.

# Bug Report

G:/BlitzMax/mod/brl.mod/dxgraphics.mod/.bmx/d3d9graphics.bmx.debug.win32.x64.c: In function '_bb_brl_dxgraphics_d3d9graphics':
G:/BlitzMax/mod/brl.mod/dxgraphics.mod/.bmx/d3d9graphics.bmx.debug.win32.x64.c:2562:40: error: expected expression before '{' token
   brl_dxgraphics_d3d9graphics__d3dCaps={};

G:/BlitzMax/mod/brl.mod/dxgraphics.mod/.bmx/d3d9graphics.bmx.debug.win32.x64.c:2566:46: error: expected expression before '{' token
   brl_dxgraphics_d3d9graphics__presentParams={};

## Environment

windows 10 x64
bcc 0.106
bmk 3.37

**Comment by woollybah** [comment]
There was an issue with bcc generating incorrect global initialisation code.
The latest version should resolve this.

If you use the same installation of BlitzMax to build updates to bcc/bmk you may find yourself unable to do this now. In which case, the best option is to get the latest release, and rebuild bcc using that. Once you have the new bcc in place, you should be able to rebuild the modules.
Apologies for any inconvenience.
