### ISSUE TITLE
Implement Cast to Enum

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#452]
Currently there's no way to cast a number to an Enum...

Casting should be handled in the following way:
* Casting a constant value to enum will have compile time check.
* Casting a dynamic value will have a runtime check in debug mode. In release mode casting to an invalid value will give an undefined result.

**Comment by HurryStarfish** [comment]
Sounds good :slightly_smiling_face: 
The runtime check would be throwing a new subtype of `TBlitzException` I suppose.

**Comment by HurryStarfish** [comment]
An additional thought: it would still be useful to have a conversion that can fail in release mode too. For example, when reading enum values as numbers from a previously saved file, you might want to be able to verify whether you're actually reading valid values.
I believe this is better off as a separate feature though (as opposed to, say, throwing the afromentioned exception in release mode too).

As for the implementation: There could be a member function generated by the compiler for every enum, with a signature like `TryConvert:Int(ordinalValue:U, result:E Var)`, where `E` is the enum, `U` its underlying number type and the return value indicating whether the conversion succeeded (`True` or `False`). `result` would then contain the result of the conversion in the case of success, or stay unmodified in the case of failure.
There could be an analogous `TryParse:Int(stringValue:String, result:E Var)` function to parse an enum value from a `String`, too.

**Comment by woollybah** [comment]
I've implemented the casting. (update bcc before brl.mod)
Parsing is somewhat more involved, so I'll leave that for another day.

**Comment by woollybah** [comment]
Except of course I missed compile-time const cast checking... :-p
