### ISSUE TITLE
Struct cyclic declaration

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#453]
Referencing `Self` in a Struct `New` method results in a cyclic declaration error.

```blitzmax
SuperStrict

Framework brl.standardio

Struct SToke
	Field toke:Int
	
	Method New(toke:Int)
		Self.toke = toke
	End Method
End Struct
```

**Comment by HurryStarfish** [comment]
Seems to be caused by one of the last dozen commits; it works fine with my NG build based on 5bccdb70f89742c8adf7b823b425a961fdcf8a22.
