### ISSUE TITLE
Compile Error: Internal Error in TScopeDecl.InsertDecl.

### ISSUE THREAD

**Issue by braxtonrivers** [bmx-ng/bcc#454]
The new error code generation just pinpointed this for me to submit.

# Bug Report

Compile Error: Internal Error in TScopeDecl.InsertDecl.
BlitzMax/mod/brl.mod/base64.mod/base64.bmx;272;0

## Environment

- Operating System: Windows 10 x64
- Output of `bcc -v`: 0.108
- bmk 3.38

**Comment by woollybah** [comment]
Do you have the latest brl.mod too?

**Comment by braxtonrivers** [comment]
Yes I have the latest brl.mod it seems to be failing on the enum line for
me at the moment,

I also used a freshly rebuilt bcc and bmk from the latest commit with all
modules updated before submitting,

apologies if this is an isolated issue, I will check out brl.mod again and
report back
