### ISSUE TITLE
Bcc Crashing

### ISSUE THREAD

**Issue by Kerntrick** [bmx-ng/bcc#457]
Latest bcc 0.109 Win7 64
I don't know where to go with this error.  In debug build of bcc, bcc will throw a 'attempt to access field or method of null object' during compilation of my project.  
It's first caught by the exception in bcc.bmx at line 54, after disabling that try/catch,  it's caught at expr.bmx at line 2828.  
Because it's in a try block used for logic all the information about the error is lost.  
This is a large project and it's not possible to step through the entire compilation process. 
Any ideas about how to pin down the location of this error?

**Comment by GWRon** [comment]
When it crashes during getting executed as debug build...can't you go up in the maxide debug tree to see where it comes from?

You know you could run the compilation in verbose mode ..so it outputs the BCC command line it uses? Copy that and then you could execute bcc.bmx in MaxIDE with the params in the command line menu entry.

Or build bcc with gdb debug options and then run it (with the command line params) via GDB.

That way you could debug BCC code (or BMK code).

**Comment by Kerntrick** [comment]
I pinned down one location where bcc fails, but in my project it also fails in a critical piece that hasen't been edited in months.  Not sure what's going on. 
Here is one test I can generate.
`SuperStrict 
Framework brl.basic

Type tTest
	Field arr1#[8]
End Type 

Local arr2#[8]

Local t:tTest = New tTest

If Not t.arr1 = arr2 Then 
	Print  "!"
EndIf `  

This kind of error is really scary, because it has a chance to completely throw a large project in the trash.
