### ISSUE TITLE
SuperStrict required: incompatible to "legacy"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#462]
freeprocess.mod eg has this code:

```BlitzMax
Rem
bbdoc: System/Execute Processes
End Rem
Module PUB.FreeProcess

ModuleInfo "Version: 1.04"
ModuleInfo "Framework: FreeProcess multi platform external process control"
ModuleInfo "License: zlib/libpng"
ModuleInfo "Copyright: Blitz Research Ltd"
ModuleInfo "Author: Simon Armstrong"
ModuleInfo "Modserver: BRL"

ModuleInfo "History: 1.04 Release"
ModuleInfo "History: Added Documentation, Added Detach and Attach Process Functions"
ModuleInfo "History: 1.03 Release"
ModuleInfo "History: Changed fork() to vfork() and exit() to _exit() to fix more hangs."
ModuleInfo "History: 1.02 Release"
ModuleInfo "History: Fixed a Linux hang when fork() is called."
ModuleInfo "History: Added SIGCHLD handling and fdReapZombies function."
ModuleInfo "History: 1.01 Release"
ModuleInfo "History: Inserts /Contents/MacOS/ into process path for Apple app packages"

SuperStrict

' createproc - to launch external executable
' TPipeStream - nonblocking readlines with fd file handles

Import brl.stream
Import brl.linkedlist
Import brl.filesystem
```
Which compiles with legacy BlitzMax but fails on NG. NG somehow expects `strict` or `superstrict` to be right at the top.
While I myself put it at the top too it seems that for comatibility reaons we might think of allowing the module info on top of `(super)strict` too.

**Comment by woollybah** [comment]
`Pub.FreeProcess` has SuperStrict at the top : https://github.com/bmx-ng/pub.mod/blob/d2089626489be4f8c229d434eecc7301009bbc85/freeprocess.mod/freeprocess.bmx#L1

> NG somehow expects

It was decided ( https://github.com/bmx-ng/bcc/issues/405 ) that Strict/SuperStrict should now be the first statement of a source file (excluding comments). This has now been implemented. The standard modules should be clean building against that requirement.

`Pub.FreeProcess` is a standard module, and has its own NG specific implementation. ( see https://github.com/bmx-ng/pub.mod/tree/master/freeprocess.mod )

Source files building against NG will need to conform to the new "feature" - which is not a big change, and is entirely compatible with legacy compilers.

**Comment by GWRon** [comment]
Seems my pub.mod is a bit outdated then.

Still I thought it was decided that either `strict` or `superstrict` is required. Before this error appeared just now I wasn't even aware that this ("module info"  before "strict declaration") was even possible.

I am fine with just fixing pub.mod/freeprocess.mod (or better: with having it fixed already) yet I wanted to make you aware that this is kind of an incompatibility - or let's better name it "small annoyancy" :-)


Closing now - as you are aware now :blush:

**Comment by HurryStarfish** [comment]
> It was decided ( #405 ) that Strict/SuperStrict should now be the first statement of a source file (excluding comments). This has now been implemented. The standard modules should be clean building against that requirement.

#405 was about requiring a `SuperStrict`/`Strict` declaraction (since NG does not support non-strict code), but wasn't intended to dictate where exactly that declaration must be placed. If vanilla allows `Module` and `ModuleInfo` declarations above it, then imo it would make sense for NG to allow that too.
And since `Module` introduces the name of the module itself and `ModuleInfo` mostly serves as documentation, imo it does make sense to put them at the top, before the "implementation part" of the module (which includes the strictness declaration).
It's not a big deal though.
