### ISSUE TITLE
Using local variables when defining global variables does not work

### ISSUE THREAD

**Issue by noroads2015** [bmx-ng/bcc#463]
# Bug Report

Anytime you try and use a predefined local variable when declaring a global variable, you get an error
```
Strict
Local x:Int = 10
Global y:Int = x + 20
Print y
```
## Expected Behavior 

This will run fine in vanilla BMax, assigning 30 to y
## Actual Behavior

This produces the error "Identifier 'x' not found" on BMX-NG.  A workaround is to declare the variable first, then assign it a value
```
Global y:int
y = x + 20
```

## Environment

- Operating System:
Windows 10 64 bit
- Output of `bcc -v`: 
bcc[ng] Release Version 0.105

**Comment by GWRon** [comment]
Reported in #440 already... And is ought to be fixed.

**Comment by noroads2015** [comment]
Thought I had the latest version already.  I will try it out when I get home. I did search to see if this had been reported before, somehow still missed it. Thanks.
