### ISSUE TITLE
bcc 0.123 undeclared, and identifier 'objectisstring' not found

### ISSUE THREAD

**Issue by braxtonrivers** [bmx-ng/bcc#493]
# Bug Report

with bcc 0.123 it displays these errors when attempting to build the reflection module

```
mod/brl.mod/reflection.mod/.bmx/reflection.bmx.debug.win32.x64.c:11209:10:
error: 'bbt_5' undeclared (first use in this function); did you mean 'bbt_4'?

mod/brl.mod/reflection.mod/.bmx/reflection.bmx.debug.win32.x64.c:30947:5:
error: 'bbt_7' undeclared (first use in this function); did you mean 'bbt_s'?
```

also with bcc 0.123 when attempting to compile latest maxide it displays this error

```
Compile Error: Identifier 'objectisstring' not found.
[D:/maxide/maxide.bmx;2269;0]

	For Local m$=EachIn EnumModules()

```

## Environment

- Operating System: Win10
- Output of `bcc -v`: 0.123
- Optional additional info, download, project links, etc

**Comment by GWRon** [comment]
Updated brl.mod too... As written in the commit of bcc?

**Comment by braxtonrivers** [comment]
yes that is with the latest brl.mod commit, I will re-checkout again and report back

**Comment by braxtonrivers** [comment]
this issue is still present on windows sadly after re-checkout, reverting back to 0.120.3.41 allows both reflection.mod and maxide to build again correctly
