### ISSUE TITLE
bcc 0.123 List index out of range

### ISSUE THREAD

**Issue by braxtonrivers** [bmx-ng/bcc#496]
# Bug Report

after updating bcc to latest when doing a rebuild of mods or a compile results in this error on windows,

however when bcc 1fcaee8 is used everything compiles and builds as expected.

Building maxide
[ 93%] Processing:maxide.bmx
List index out of rangeBuild Error: failed to compile (-1) D:/BlitzMaxNG/maxide/maxide.bmx

## Environment

- Operating System: Win 10
- Output of `bcc -v`:  0.123

**Comment by woollybah** [comment]
Well, I'm having trouble replicating this.

You could try a non-debug build of bcc?

**Comment by braxtonrivers** [comment]
apologies, very strange indeed, I am now also unable to reproduce this, and the only change I made was turning off memory integrity in core isolation, as it would not update with it on ( as there was a critical intel management engine update for my z370-e motherboard that asus recommends )
