### ISSUE TITLE
Consider incbin lib for construction of incbin data

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#507]
The current incbin method is to convert the binary into a long array of hexes, which can take a considerable time to compile in gcc.

This project ( https://github.com/graphitemaster/incbin ) does incbin'ing using the inline assembler that comes with the compiler.
It also aligns the data, which may be useful in some cases.

We should see whether this method is faster than the one we are using now.

**Comment by davecamp** [comment]
In the MS compiler you can write this to add data to your own section:

    #pragma section(".incbin")
    __declspec(allocate(".incbin")) const char data[32] = "Value of mydata is: ";
    __declspec(allocate(".incbin")) const int mydata = 90;

Is there something similar for gcc that could work?
maybe "__attribute__(allocate(".incbin")) ..." ?

**Comment by davecamp** [comment]
Oops I didnt look at the code. Looks like its doing this anyway *face palm*

**Comment by woollybah** [comment]
Done
