### ISSUE TITLE
[Enum] Null as enum default in function definition leads to error

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#523]
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Enum ETest Flags
    a
    b
End Enum

Function Pass(e:ETest = Null)
    Print e.ToString()
End Function
```

output:
```
Compile Error: TCastExpr(Enum ETest ,<TExpr>) cannot be statically evaluated.
[/home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/blitz.mod/blitz.release.linux.x64.i;181;0]
```

If this (passing Null as default) is not allowed:
- maybe output a better error message?
- how to pass a "default" (which defaults to None) then ? only via having a "none" flag in the enum?

**Comment by HurryStarfish** [comment]
> If this (passing Null as default) is not allowed

Nah, it should definitely be allowed. Like with other types, `Null` should represent the default value. That'd be "no flag" (0) for flags enums, and the first element for regular enums.
There just seems to be a bug in how bcc is trying to treat that `Null` as a constant.
