### ISSUE TITLE
[Struct] New() ambiguity not detected ?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#526]
```Blitzmax
SuperStrict
Framework Brl.StandardIO

Type TTest
    Private
    Field data:STest
End Type

Struct STest
    Field number:Int

    Method New(defaultNumber:Int = 1)
        number = defaultNumber
    End Method
End Struct


Local s:STest = New STest()
Print s.number 'prints 0, OK

Local s2:STest = New STest(10)
Print s2.number 'prints 10, OK
```

What is the expected output? Assuming that `New()` and `New(paramWithDefault)` are kind of ambiguous here.
Here the error is only thrown if providing a custom `New()`

In my "real" code the compiler spotted the ambiguity and errored out if I had a custom `New()` in the struct - it then highlighted the `Struct SStruct` line. Without the custom `New()` it threw the same error - but without an error line:

```
Compile Error: Unable to determine overload to use: Method STextParseInfo.New(estimatedLineCount:Short,estimatedNestedColorStyles:Int) or Method STextParseInfo.New().
```

But in above's simple example (tried to replicate it) it just ... compiles. - and outputs:
```
0
10
```
which can be correct ... but maybe 1 and 10 would also be correct ?

**Comment by GWRon** [comment]
So this here correctly fails (providing a custom `New()))
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Type TTest
	Private
	Field data:STest
End Type

Struct STest
	Field number:Int
	
	
	Method New()
		New(5)
	End Method

	Method New(defaultNumber:Int = 1)
		number = defaultNumber
	End Method
End Struct
```

```
Compile Error: Unable to determine overload to use: Method STest.New() or Method STest.New(defaultNumber:Int).
[/home/ronny/Arbeit/Tools/BlitzMaxNG/tmp/untitled1.bmx;9;0]
Build Error: failed to compile (65280) /home/ronny/Arbeit/Tools/BlitzMaxNG/tmp/untitled1.bmx
```

**Comment by HurryStarfish** [comment]
Strangely, this is enough to cause an error:
```
Struct S
	Method New()
	End Method
	
	Method New(i:Int = 1)
	End Method
End Struct
```
It results in "Unable to determine overload to use: Method S.New() or Method S.New(i:Int)", even if `S` is never used anywhere.


The following code has inconsistent behaviour between structs and classes:
```
Struct S
	Method New(i:Int = 1)
		Print "New S(" + i + ")"
	End Method
End Struct

Type T
	Method New(i:Int = 1)
		Print "New T(" + i + ")"
	End Method
End Type

New S
New T
```
It only prints
> New T(1)

despite the fact that adding a constructor with a parameter does not remove the default constructor from classes in BlitzMax. If the default value (`= 1`) is removed, the default constructor of `T` is called instead, if a `New()` is added explicitly, it produces an "Unable to determine overload" error.

Imo there should be no difference between classes and structs here, and no difference between the implicitly existing parameterless `New()` and a handwritten one.

**Comment by HurryStarfish** [comment]
That said, should `New()` vs. `New(i:Int = 1)` produce an "Unable to determine overload" error at all?
For comparison: C# always prefers the overload with less parameters in such cases, so `New T` would always call `New()`. This has the advantage that the code still compiles and both constructors are usable - of course it has the disadvantage that someone might confuse the two and expect `New T` to call `New(i:Int = 1)`.
Although the example here is about constructors, the same applies to methods and functions.
