### ISSUE TITLE
Overriding "no return value"-methods within modules

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#55]
I just tried to compile maxmod again:

```console
./bmk makemods -r -a maxmod2
Compiling:maxmod2.bmx
Compile Error: Overriding method does not match any overridden method.
[/BlitzMaxNG/mod/maxmod2.mod/maxmod2.mod/maxmod2.bmx;340;0]
```

The line is the following "Stop()" method:
```blitzmax
Type TMaxModChannel Extends TChannel
...
	Method Stop()
		_channel.Stop()
	End Method
```

interestingly "TChannel" defines that method exactly the same (no explicit return value).

Changing it to "Stop:int()" in TChannel AND TMaxModChannel removes the error message (and goes on to the next :p).

So this means, bcc-ng currently seem to have problems with "void" methods in modules.
Doing the same in a single file works as expected, same for normal "file imports" (import "bla.bmx").

**Comment by woollybah** [comment]
If you are interfacing with modules defined as Strict, your extending types will also need to be Strict, and not SuperStrict. Strict assumes undefined return types as Int.

**Comment by GWRon** [comment]
Maybe modules should get SuperStrict as much as possible - as this sounds as "superstrict + strict" is possible, while "strict + superstrict" isnt.

Thanks anyways

**Comment by GWRon** [comment]
Shouldnt this be possible:

Base: Strict
Extended: SuperStrict

Base: 
Method Stop()

Extended
Method Stop:int()

Why? Because you said in "strict" void returns default to ":int". If you blindly assume that for void returns, then the superstrict "Stop:int()" should be perfectly well defined in that case.

When doing this that way, we should get rid of many "overrridden method does not match" codes regarding old code flying around.

Are there disadvantages of this approach?

**Comment by GWRon** [comment]
## Suggestion
What do you think about adding some kind of "strictmode"-property to function declaration?

All __original__ classes get the property "strict:int = 0 | 1 | 2" based on the strictmode of their source file. If they extend a class, they do set the strict-property to the value of their parent (or just return the value of the original one).

## Example
If the base file is "non"-strict, all declared classes there (if initial, not extending) get the property "strict:int = 0".
Now, if you extend the classes in another file (this time strict), the validity checks use the property given in the initial class.

This gets rid of things like "Strict baseclass: Func()" and "SuperStrict extendedClass: Func:Int()".

**Comment by woollybah** [comment]
I don't think it is a good idea to "downgrade" a superstrict method to match the return type of its strict overridden parent.

However, I am not against "updgrading" a strict method to match the void return type of its superstrict overridden parent...

**Comment by GWRon** [comment]
#### upgrading
Isn't this the normal expected behaviour? I mean: parent is superstrict and expects ":void".
As I am not sure if I got you correct: If a superstrict parent defines ":void" and a child defines ":int" you "upgrade" that child-definition to be ":void" ? How do you handle "return True" and "return False" then (which should be able for valid "nothing = :int"-constructions).

**Comment by woollybah** [comment]
Why on earth would you override a SuperStrict Void method with a Strict method and expect to be able to return an Int from it?

**Comment by GWRon** [comment]
The superstrict base module/source might not care for the result of a specific function and therefore do not return anything (aka "void").

Now I extend from this type and now I am interested in the result of the overridden function - so I rely on "nothing becomes :int" and do a return "myInterestedValue".

In short: from a "fire and forget" function call the extended variant checks for specific result values.

I know that this could get overcome with "GetLastResultID()" or similar approaches.
Also do not get me wrong - I personally would adjust the base type to return ":int" in that case but I just thought about potential usage forms.

**Comment by GWRon** [comment]
Again: I think I did not understand your 
> However, I am not against "updgrading" a strict method to match the void return type of its superstrict overridden parent...

So did you mean:
base: `function bla()`
extended: `function bla:int()`
And the extended function now becomes `bla()` automatically? If so, how do you then inform about "return True" not being possible in the extended `bla:int()`-function. For the average-joe-user this isn't self-explanatory then (he is reading ":int" but is not alllowed to return an int...)

If you meant something different, please explain it to me in other words.

**Comment by GWRon** [comment]
in "vanilla" I would expect this to work, yes.

```BlitzMax
SuperStrict
Framework brl.standardio

Type TBase
    Method getNothing()
    End Method
End Type

Type TImpl Extends TBase
    Method getNothing:Int()
		return True
    End Method
End Type


global t:TImpl = new TImpl
if t.getNothing() then print "returned True"
```
output
```
returned True
```

**Comment by woollybah** [comment]
Right, because TBase getNothing() is really getNothing:Int() - since SuperStrict isn't really super-strict.

But now we are, so the rules are tightened up. If you were coding in Java, for example, the above example would not compile either, because the return type of the overridden method should match.

**Comment by GWRon** [comment]
I understood this part already: in a perfect scenario the extended function return type should be the same (or extending from the previous return type).

BUT ... I tried to suggest something which enables some "automagic" for strict source files extending superstrict-classes.

So:

superstrict.bmx
```BlitzMax
Superstrict
Type TSuperStrict
   Method a()
     return
   End Method
End Type
```

strict.bmx
```BlitzMax
Strict
Import "superstrict.bmx"

Type TStrict extends TSuperStrict
   Method a:int()
     return True
   End Method
End Type

local mySuperstrict:TSuperStrict = new TSuperStrict
local myStrict:TStrict = new TStrict
```

For the compiler "TSuperstrict.a" could be still a "void" thing... but once the user does a comparison (`if mySuperstrict.a() then print "I run that method successfully"`) the compiler should allow that. So implicitely it converts that void to "0" then. So why should one call `if mySuperStrict.a() then` ? Because sometimes you do not know the exact type of an instance (there might be multiple types extending from `TSuperStrict` but you only store them in an array `TSuperStrict[]`).

It is more than just "hacky" because for other types the user expectations differ: `:string` in base class versus `:int` in extended class. The only difference here is, that vanilla does indeed ignore "void" and implicitely assumes "int = 0" then.

**Comment by woollybah** [comment]
Your logic makes no sense to me :-)

**Comment by GWRon** [comment]
Seems we both have something in common then :-)

Dunno how to explain it understandable:
- vanilla assumes "0" for "void" functions in superstrict
- NG uses "void" for "void" functions in superstrict

To allow this:
```BlitzMax
SuperStrict
Framework brl.standardio

Type TBase
    Method getNothing()
    End Method
End Type

Type TImpl Extends TBase
    Method getNothing:Int()
		return True
    End Method
End Type


global b:TBase = new TBase
global i:TImpl = new TImpl
print "b.getNothing() = " + b.getNothing()
print "i.getNothing() = " + i.getNothing()
```
outputting
```
b.getNothing() = 0
i.getNothing() = 1
```

NG needs to implicitely convert "void" to "0".

__Question:__ Why does NG not allow overriding "void" with "int", isn't "int" some kind of child of "void" (which allows more than "0" as value)? Overriding `Method get:TBaseClass()` with `Method get:TExtendedFromBaseClass()` is possible too?
Is it forbidden because of some C-code-interaction (when playing with external c-code from BlitzMax) ?

**Comment by woollybah** [comment]
Yes. And because Void should actually be void.
Therefore, if you want a less strict programming style, use Strict. If you want to use SuperStrict, you need to live within its rules.

**Comment by GWRon** [comment]
You are right, but I was thinking of all those "beginners" who use a superstrict module / 3rd party code within their own strict-code.


BTW: feel free to close this issue (as __I__ agree with having "void<>int")
