### ISSUE TITLE
Abs(x <  y) leads to misleading error message (overload) 

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#551]
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Print Abs(10 < 5)
```

leads to
```
Compile Error: Unable to determine overload to use: Function Abs:Int(a:Int) or Function Abs:Float(a:Float).
```
Internally `10 < 5` is resulting in a boolean ... 
`Print Abs(True)` works as `True` is not treated as a boolean but "1".

**Comment by Kerntrick** [comment]
Since when did Bmax get boolean?

**Comment by GWRon** [comment]
Internally. Internally BCC understands "bools". But not the blitzmax language itself.

**Comment by Kerntrick** [comment]
I see. That's  probably the problem, any conditional expression should always cast to Int.
