### ISSUE TITLE
StaticArray size incorrectly allows a non compile time constant resulting in an EAV

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#554]
Windows10 x64 - 129.3.45 x64

I understand that StaticArray, by definition, will require a compile time constant for it's size however the following compiles and runs consequently throwing up an EAV when accessing the data.

`
Extern
Function GetDataSize:Size_T()
EndExtern

Struct Test
	Field StaticArray data:Byte[GetDataSize()]
EndStruct
`

**Comment by GWRon** [comment]
This here compiles too:

```
SuperStrict
Framework Brl.Standardio

Function GetSize:Size_T()
	Return 10:Size_T
End Function


Struct Test
Field StaticArray data:Byte[GetSize()]
EndStruct
```

**Comment by davecamp** [comment]
In the c code you end up with a zero length static array.
