### ISSUE TITLE
operator[] doesn't work with Structs

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#556]
Struct test
    	Field data:Float[10]
	
    	Method operator[]:Float(i:Int)
    		Return data[i]
    	EndMethod
    EndStruct

    Local t:test
    Local f:Float = t[0]

Compile error is 'Expression of type 'test' can not be indexed'

Other operators seem to work ok although I've not tried them all.

**Comment by GWRon** [comment]
This should work in more up to date BCCs (so not in v0.129 bmx ng release package )

**Comment by woollybah** [comment]
This works in the latest development version, and will be available in the next release.
