### ISSUE TITLE
Segfault on crypto.mod import

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#571]
@Scaremonger mentioned on discord, that the following code leads to a segfault.

```BlitzMax
SuperStrict
Import crypto.digest
```

indeed it makes BCC segfault ...
When debugging BCC and going down the rabbit hole a bit it leads to a null access after trying to find a class with "_env" being null...

![image](https://user-images.githubusercontent.com/2625226/143049911-120100a9-15d2-4322-a33f-8f12a3a23c03.png)
![image](https://user-images.githubusercontent.com/2625226/143050014-15e0fd58-8d78-406b-b845-1267310fdf2b.png)
![image](https://user-images.githubusercontent.com/2625226/143050934-e1129e1b-f61f-480e-9c35-c37e0393fd83.png)

**Comment by GWRon** [comment]
Dunno if this is distracting from the initial issue now - but I added a debug print for PopEnv() and PushEnv() to also inform if "_env" is now existing (1) or null (0).
Output during compilation was:
```
...
pop env ... 1
pop env ... 0
push env ... 1
push env ... 1
pop env ... 1
pop env ... 0
push env ... 1
push env ... 1
pop env ... 1
pop env ... 0
push env ... 1
push env ... 1
pop env ... 1
pop env ... 0
push env ... 1
push env ... 1
pop env ... 1
pop env ... 0
```
Means it calls push and pop 2 times each (2 in and 2 out)


Ok, so `PopEnv()` and `PushEnv()` are written this way:
```BlitzMax
Function PushEnv( env:TScopeDecl )
	If _env _envStack.AddLast( _env )
	_env=env
End Function

Function PopEnv()
	_env=TScopeDecl( _envStack.RemoveLast() )
End Function
```

When starting a new `_env` is empty. So this means:
- 1st call to `PushEnv(env)` will NOT add the passed "env" to the stack but only assigns it as current
- 2nd call to `PushEnv(env)` will add the passed "env" to the stack and also assigns it as current (stack contains of 1 backupped "env" now)
- 1st call to `PopEnv()` will retrieve the one and only backup (from the "2nd call")
- 2nd call to `PopEnv()`... fails to retrieve something now

This sounds... broken to me

**Comment by Scaremonger** [comment]
Adding framework above it stops the segment fault:
```
SuperStrict
Framework brl.retro
Import Crypto.MD5digest
```
So I concluded there was a conflict with an automatically imported module and I put the following code together to track it down. It seems to be brl.gnet!
```
SuperStrict

Framework brl.appstub
Import brl.eventqueue
Import brl.maxlua
Import brl.standardio
Import brl.audio
Import brl.filesystem
Import brl.maxunit
Import brl.stbimageloader
Import brl.audiosample
Import brl.font
Import brl.maxutil
Import brl.stream
Import brl.bank
Import brl.freeaudioaudio
Import brl.objectlist
Import brl.stringbuilder
Import brl.bankstream
Import brl.freetypefont
Import brl.oggloader
Import brl.systemdefault
Import brl.base64
Import brl.GLGraphics
Import brl.openalaudio
Import brl.system
Import brl.basic
Import brl.glmax2d
Import brl.pixmap
Import brl.textstream
Import brl.blitz
'Import brl.gnet
Import brl.platform
Import brl.tgaloader
Import brl.bmploader
Import brl.Graphics
Import brl.pngloader
Import brl.threadpool
Import brl.bytebuffer
Import brl.hook
Import brl.polledinput
Import brl.threads
Import brl.clipboard
Import brl.httpstream
Import brl.quaternion
Import brl.timerdefault
Import brl.collections
Import brl.io
Import brl.ramstream
Import brl.timer
Import brl.color
Import brl.jpgloader
Import brl.randomdefault
Import brl.uuid
Import brl.d3d7max2d
Import brl.keycodes
Import brl.random
Import brl.vector
Import brl.d3d9max2d
Import brl.linkedlist
Import brl.volumes
Import brl.directsoundaudio
Import brl.map
Import brl.reflection
Import brl.wavloader
Import brl.dxgraphics
Import brl.math
Import brl.retro
Import brl.endianstream
Import brl.matrix
Import brl.socket
Import brl.event
Import brl.max2d
Import brl.socketstream

Import Crypto.MD5digest
```

**Comment by GWRon** [comment]
In Brl.Gnet/gnet.bmx there is this line
```
Field _enetEvents:TArrayList<EnetEvent> = New TArrayList<EnetEvent>
```

I removed all occourencies of "_enetEvents" (ignoring that it breaks functionality) and then it compiles again.

**Comment by GWRon** [comment]
your fix makes the module "useable" now - but the underlaying bug (the broken generics array list usage) is still valid - or not?

In that case this issue should be reopened.
