### ISSUE TITLE
Use of generics can cause crash

### ISSUE THREAD

**Issue by thareh** [bmx-ng/bcc#593]
The following will cause a crash:

```
Framework BRL.Blitz

Type Foo<T>
EndType
```

However, adding anything after EndType even just a comment will prevent this.

## Environment

- Operating System: Windows 11 (64-bit)
- Output of `bcc -v`: 0.133

**Comment by GWRon** [comment]
As written in the commit commet:

"startLine" should never be "<= 0" ...else you will have an OOB again.
Also I would suggest to do the check (i < _lines.length) outside of the for loop ...

Something in the lines of this:
```BlitzMax
Method Join:String(startLine:Int, endLine:Int, s:String)
	Local sb:TStringBuffer = New TStringBuffer
	'limit range
	If startLine <= 0 Then startLine = 1
	If endLine >= _lines.Length Then endLine = _lines.Length - 1

	For Local i:Int = startLine - 1 To endLine
		sb.Append(_lines[i])
		sb.Append(s)
	Next
	Return sb.ToString()
End Method
```
