### ISSUE TITLE
Compiler directives not recognized resulting in identifier not found.

### ISSUE THREAD

**Issue by braxtonrivers** [bmx-ng/bcc#608]
# Bug Report

It would appear that compiler directives are not being recognized resulting in the following errors.

maxide.bmx
?MacOS
Const LABELOFFSET=2
?Win32
Const LABELOFFSET=4
?Linux
Const LABELOFFSET=0
?

Compile Error: Identifier 'LABELOFFSET' not found.

reflection.bmx
?Not ptr64
	Field _size=4
?ptr64
	Field _size=8
?

Compile Error: Identifier '_size' not found.

## Environment
- Operating System: Windows 11 x64
- Output of `bcc -v`: 0.136

**Comment by GWRon** [comment]
Does it happen in <0.136 too?

**Comment by braxtonrivers** [comment]
Thanks GWRon a complete clean rebuild using your windows script sorted it out, so strange as it was working fine until yesterday, will close this since it is an isolated issue.
