### ISSUE TITLE
BCC-Segfault when using Short/Byte/Double as For-Loop variable

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#62]
Each of the following loops makes BCC segfault during compilation.

```Blitzmax
		For local x:short = 0 to 5
		Next
		For local y:byte = 0 to 5
		Next
		For local z:double = 0 to 5
		Next
```

```gdb
Program received signal SIGSEGV, Segmentation fault.
0x08085eb7 in _bb_TForStmt_OnSemant ()
```

Int, Float and Long work as expected.

OnSemant() fails when trying to create the TBinaryExpr:
```Blitzmax
		Local assop:TAssignStmt=TAssignStmt( incr )
		Local addop:TBinaryExpr=TBinaryExpr( assop.rhs )
```

assop is this:
```
lhs: TVarExpr(Local x:Short)
op: =
rhs: TCastExpr(Short,(TCastExpr(Int,TVarExpr(Local x:Short)) + TConstExpr("1")))
```

Switching the expressions a bit (created an "int"-local and then manually used that varID):
```
lhs: TVarExpr(Local j:Int)
op: =
rhs: (TCastExpr(Int,TVarExpr(Local x:Short)) + TConstExpr("1"))
```
this does not segfault, so maybe this gives the right hint to solve the problem.

**Comment by GWRon** [comment]
I think the problematic part is this:

the "step" is defined as "int", and therefore it tries to cast the lhs value (which might be a "short" or "byte") to the int. BalanceTypes then of course leads to a "int cast" of the left hand side.

Normally I would assume the "for loop" will do this:
"lhs" defines the resulting type (and its limit), "rhs" gets cast to it.

But theoretically we have two options (eg. if "rhs" uses a "0.01" step and "lhs" is a int/short/byte):
it could repeat 100 steps until the lhs-value increases by 1 - OR - it could cast the step to the lhs-expressionType, which then leads to a "step 0" - and therefore should raise an error (step 0 not allowed). In all cases the compiler might emit a _"WARNING: inappropriate STEP value used. Accuracy loss from converting FLOAT to SHORT"_ or so.

Currently that is skipped by using the "convert left to right side" approach (ie. the step size defines the "lhs"-value). This might not be intended by the author of the code.

**Comment by woollybah** [comment]
I believe I have a fix for this.
