### ISSUE TITLE
Importing of generics not working

### ISSUE THREAD

**Issue by thareh** [bmx-ng/bcc#635]
Good day,

Importing of a generic type seems to crash BCC.

```
Framework BRL.Blitz

Import "Import.bmx"
```

Import.bmx
```
Framework BRL.Blitz
Import BRL.Collections

Global map:TTreeMap<String, String> = New TTreeMap<String, String>()
```

Thanks!

- Operating System: Windows 11
- Output of `bcc -v`:  bcc[ng] Release Version 0.139

**Comment by woollybah** [comment]
This may be working now with the latest changes.
Took a while to understand the underlying problem.

**Comment by thareh** [comment]
It does seem to fix the issue, awesome! Good job!! :)

If you're on a roll... there's this other issue with generics (#594) which prevents the proper use of generics in modules/imports, would be SOOOO swell if you could take a look at it.

Thank you and merry christmas!
