### ISSUE TITLE
Functionpointer as method argument is interpreted as Overriding method.

### ISSUE THREAD

**Issue by Octav14n** [bmx-ng/bcc#64]
Functionspointer as method arguments are interpreted as methods.
Easiest example to reproduce this error:
```
SuperStrict
Framework brl.blitz

Type Test
	Method t(compare:Int(obj1:Object, obj2:Object))
	End Method
End Type
```
What's expected:
compiling with bcc works.
What actually happens:
bcc thinks "compare" (the argument) shall override "Method Object.Compare:Int(Local otherObject:Object)"

More details:
I tried to compile wxWidgets with bcc and after fixing lots of bugs i stumbled upon this (wx.mod/wxlistctrl.mod/wxlistctrl.bmx line 819):
```	Rem
	bbdoc: 
	End Rem
	Method SortItems:Int(compare:Int(item1:Object, item2:Object, data:Object), data:Object)
		callback = compare
		callbackData = data
		Return bmx_wxlistctrl_sortitems(wxObjectPtr)
	End Method
```
I've extended bcc to show which alternative there is when the "Overriding method does not match any overridden method." error is thrown.

Last output of bcc (those two lines beginning with "Did" are the ones generated by my addition to bcc to debug this Problem):
```
Compiling:wxlistctrl.bmx
Did not find "Function compare:Int(Local item1:Object,Local item2:Object,Local data:Object)"
Did you possibly mean: "Method Object.Compare:Int(Local otherObject:Object)"?
Compile Error: Overriding method does not match any overridden method.
```

It seems like bcc thinks "compare" (the function pointer) shall be a method of wxListCtrl.

**Comment by GWRon** [comment]
decl.bmx contains this code:

```BlitzMax
'Fix! A func is NOT a block/scope!
'
Type TFuncDecl Extends TBlockDecl
...
	Method OnSemant()
...
		'check we exactly match an override
		If sclass 'And IsMethod()
```
removing the comment sign (add back "and IsMethod()") made your above code compile - but there must be a reason for the out-comment.

**Comment by woollybah** [comment]
It appears to be semanting too much of the function declaration, and should probably return after semanting the args.
I'll post a patch later.
