### ISSUE TITLE
Compilation failure on Apple Silicon M1 Max (clang 17)

### ISSUE THREAD

**Issue by sblank** [bmx-ng/bcc#659]
Sometime in the last month (or a bit earlier), I began receiving the following error:

/Users/sblank/Desktop/BlitzMax/dist/bootstrap/mod/brl.mod/hook.mod/.bmx/hook.bmx.release.macos.arm64.c:18:26: error: incompatible function pointer types assigning to 'BBOBJECT (*)(BBINT, BBOBJECT, BBOBJECT)' (aka 'struct BBObject *(*)(int, struct BBObject *, struct BBObject *)') from 'void (*)()' [-Wincompatible-function-pointer-types]

at several points in the compilation process, resulting in a build failure.  My assumption is that some update or other to clang has introduced a more strict compilation, but I've been unable to find a workaround or fix.

Has anyone else experienced this behavior?

**Comment by sblank** [comment]
Thanks Brucey!  I'll check it out later today... looking forward to it!

Cheers,

Stan

**Comment by GWRon** [comment]
> Thanks Brucey! I'll check it out later today... looking forward to it!
> 
> Cheers,
> 
> Stan

Hey Stan,
did you check it out ? And does it run flawless for you?

Asking as the commit fixing your issue leads to issues on other user's computers (at least Windows of others, and on my Linux box too -> #662).

**Comment by sblank** [comment]
Hi Brucey,

I did check it out, but had no luck with creating the bmk executable.  
The bcc file seems to be there, but that's all.  I'm still getting 
similar error messages and I thought I had posted a message showing the 
terminal output, but apparently not.

My apologies for not getting back to you... I'll keep a closer watch now 
that my teaching duties are over for the summer!

Thank you for responding!

Stan

On 2024-05-26 06:24, Ronny Otto wrote:

>> Thanks Brucey! I'll check it out later today... looking forward to it!
>> 
>> Cheers,
>> 
>> Stan
> 
> Hey Stan,
> did you check it out ? And does it run flawless for you?
> 
> Asking as the commit fixing your issue leads to issues on other user's 
> computers (at least Windows of others, and on my Linux box too -> #662 
> [1]).
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/bmx-ng/bcc/issues/662
[2] https://github.com/bmx-ng/bcc/issues/659#issuecomment-2132184116
[3]

**Comment by sblank** [comment]
My mistake... thanks for responding Ronny!

No luck getting bmk to compile and MaxIde has never worked on my MacBook 
Pro M1 Max, but I could at least use BlitzMax-ng through VSCode.

Kind regards,

Stan

On 2024-05-26 06:24, Ronny Otto wrote:

>> Thanks Brucey! I'll check it out later today... looking forward to it!
>> 
>> Cheers,
>> 
>> Stan
> 
> Hey Stan,
> did you check it out ? And does it run flawless for you?
> 
> Asking as the commit fixing your issue leads to issues on other user's 
> computers (at least Windows of others, and on my Linux box too -> #662 
> [1]).
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/bmx-ng/bcc/issues/662
[2] https://github.com/bmx-ng/bcc/issues/659#issuecomment-2132184116
[3]

**Comment by sblank** [comment]
Progress was made on the current release (May 26, 2024) in that both bcc 
and bmk compiled.  MaxIDE did not compile, but using VSCode I was able 
to at least begin to build some of the samples.  However, none of the 
samples could complete the build process and the errors were consistent:

[ 81%] Compiling:linux_source.bmx.release.macos.arm64.c
/Users/sblank/Desktop/BlitzMax/mod/sdl.mod/sdl.mod/SDL/src/thread/SDL_thread.c:294:41: 
error: incompatible integer to pointer conversion passing 'SDL_threadID' 
(aka 'unsigned long') to parameter of type 'void *' [-Wint-conversion]
BBThread * bbThread = bbThreadRegister(SDL_ThreadID());
^~~~~~~~~~~~~~
/Users/sblank/Desktop/BlitzMax/mod/brl.mod/blitz.mod/blitz_thread.h:140:36: 
note: passing argument to parameter 'thd' here
BBThread *bbThreadRegister( void * thd );
^
[ 82%] Compiling:common.bmx.release.macos.arm64.c
1 error generated.
[ 82%] Compiling:common.bmx.release.macos.arm64.c
[ 83%] Compiling:source.bmx.release.macos.arm64.c
Build Error: failed to compile (256) 
/Users/sblank/Desktop/BlitzMax/mod/sdl.mod/sdl.mod/SDL/src/thread/SDL_thread.c
[ 84%] Compiling:vector.bmx.release.macos.arm64.c

== ERROR ==

Execution time: 0s 584.222375ms

  *  The terminal process terminated with exit code: 255.

On 2024-05-26 06:24, Ronny Otto wrote:

>> Thanks Brucey! I'll check it out later today... looking forward to it!
>> 
>> Cheers,
>> 
>> Stan
> 
> Hey Stan,
> did you check it out ? And does it run flawless for you?
> 
> Asking as the commit fixing your issue leads to issues on other user's 
> computers (at least Windows of others, and on my Linux box too -> #662 
> [1]).
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/bmx-ng/bcc/issues/662
[2] https://github.com/bmx-ng/bcc/issues/659#issuecomment-2132184116
[3]
