### ISSUE TITLE
[emscripten] Too many setjmps in function

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#66]
A Try/Catch inside a loop can generate the following runtime error :

```
too many setjmps in a function call, build with a higher value for MAX_SETJMPS
```

Current code looks like this :

```
do {
    jmp_buf * buf = bbExEnter();
        switch(setjmp(*buf)) {
        case 0: {
```

Perhaps pushing `setjmp(*buf)` into a separate bbExXXXX() function and returning the result would fix this?

**Comment by GWRon** [comment]
Any news on this issue?

**Comment by GWRon** [comment]
Would this help on the issue:

https://github.com/kripken/emscripten/issues/2379

?

**Comment by GWRon** [comment]
Still valid?
