### ISSUE TITLE
UTF8? Char appears in MaxIDE but not other Texteditors -> compiler stops

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#69]
I have this piece of code in a UTF8-encoded source file:
(direct copy paste)
```BlitzMax
	Function Create:TElevatorSoundSource(_movable:Int)
		Local result:TElevatorSoundSource  = New TElevatorSoundSource
		result.Movable = ­_movable
```

When compiling in MaxIDE it opens up the file and the line containing the error has some odd char appended:
```BlitzMax
	Function Create:TElevatorSoundSource(_movable:Int)
		Local result:TElevatorSoundSource  = New TElevatorSoundSource
		result.Movable = Â­_movable
```
As GitHub allows other character displays, I added a screenshot to show up what is displayed there:
![oddchar](https://cloud.githubusercontent.com/assets/2625226/5876519/1f886f10-a318-11e4-8a55-4a1785140c32.png)

Maybe the parser should ignore "invalid" characters at all?

More interesting: The whole file compiles with vanilla BMX ... so this might skip such "utf8"-char thingies already.

**Comment by woollybah** [comment]
I think non ASCII characters in code should not be there, and the error seems correct in this instance.
Remove the bad characters, save, and build.
According to my hex editor, there are two bad characters in your example, $C2 and $AD. Only ASCII letters, underscore and numbers are valid in a variable name.
The fact that legacy bcc ignores it is probably a bug ;-)

**Comment by GWRon** [comment]
Interestingly "c2 ad" is the so called "soft hyphen". The code was written by a windows user using BLIde ...maybe some autoinputcorrection.

I will file a bug report in the blitzmax forum :smile:
