### ISSUE TITLE
"SizeOf"-implementation

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#78]
As Bruce suggested that sizeOf has to get restructured.

I checked the current implementation, and the approach there is to distinguish by "objectusage -> object". So it first checks if the object is a constant, a variable, a function call etc.
We could reorder it in the way it checks for the the object first, and afterwards checks the usage type.

so we go from
```
if var
  if objectType...
  elseif numericType 
     genericImplementationFittingForAll()
  elseif arrayType...
  ...
elseif const
  if numericType 
    genericImplementationFittingForAll()
  elsif arrayType
  ...
endif
```
to

```
if objectType
  if var ...
  elseif membervar ...
  ...
elseif numericType
  genericImplementationFittingForAll()
endif
```

Sorry for this a bit confused representation of the approaches, but the idea of the second one is to avoid writing things multiple times. So you might end up with a bit shorter code only writing specific portions once - but this costs something: structure and overview. I think the current approach fits best and the only idea I can come up regarding "optimization" is to remove unneeded casts (when accessing field-properties TExpr already implements).

Another Idea is to implement a "SizeOf" for each "ExprType" so we just call an anonymous function `GetSize()` and it takes care of everything needed within the extended expressions.

Means __TObjectType__ knows how to calculate its size, __TStringType__ too. But for this the  `GetSize()` needs to know about the parent to access that too. Dunno how a `TStringType.GetSize(expr:TExpr)` adds cyclic dependencies.

Ideas?

**Comment by woollybah** [comment]
It's not as complicated as you think. The whole thing can probably be done in less than a dozen If statements ;-)
The only thing that probably requires some extra work is SizeOf Type, as I don't think the generator is generating that yet. (i.e. directly outputing a type structure reference - struct some_type_obj).

I'll have a look at it later.

**Comment by GWRon** [comment]
Ahh, see... I do not know much about "c". So you are saying there is a sizeof-command available in C which already cares about the rudimentary things - and you just have to add the things you added for Blitzmax  (reference counter, reflection stuff ...) ?

In that case yes, then it is just a matter of some if's. The current implementation tries to traverse an object down to its basics so it can calculate things "I" knew.

Even if it should make me feel ashamed: I am used to get my codes truncated down to some simple lines as soon as you re-do them :smile: ... but hey, that's normal if the other one feels more home in the code than I do.
