### ISSUE TITLE
Function pointer assignment failing with params

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#82]
Current bcc/bmk fails to compile sdl.mod/sdlgraphics.mod because of this line:

sdlgraphics.bmx  line 133:
```BlitzMax
' set mouse warp function
_sdl_WarpMouse = bmx_SDL_WarpMouseInWindow
```
`bmx_SDL_WarpMouseInWindow` is defined in common.bmx:
```BlitzMax
Extern
	...
	Function bmx_SDL_WarpMouseInWindow(x:Int, y:Int)
	...
End Extern
```

output of compiler:
```
Compiling:sdlgraphics.bmx
Compile Error: Missing function argument 'x'.
[/BlitzMaxNG/mod/sdl.mod/sdlgraphics.mod/sdlgraphics.bmx;133;0]
```

Seems bcc somehow thinks you want to assign the result function.

Same error bmx-ng/brl.mod#8.

**Comment by GWRon** [comment]
I do not know how to handle that 100% properly.

There are multiple scenarios:
`local fPointer:int` and `function f:int(x:int)` defined somewhere. Additionally we have `function fPredefined:int(x:int = 1)`. Another line is `local fValue:int`.

- fPointer should contain pointer to function:
  - `fPointer = f` (OK, recognizeable because it misses params)
  - `fPointer = fPredefined` (FAILING, how should the compiler know whether we want the result of the function or the pointer)

- fValue should contain the result of a function clal
  - `fValue = f` (OK, might fail correctly because params are missing, but might also just get the function pointer assigned as value -> FAIL )
  - `fValue = fPredefined` (MIGHT FAIL, depends on whether it returns the function pointer or the result value (which will be more likely the case))


You could let the compiler analyze the whole code to see how the `fPointer` is used at the end - but with 3rd party modules you will not be able to do that properly.
For the moment I do not see how you could avoid that complete bugged scenario. I am even not sure how "vanilla" tackles it.

**Comment by woollybah** [comment]
It's a regression of the function pointer handling, specifically in this case where a function is on the right hand side of an assignment.
I have a fix for it.
