### ISSUE TITLE
Incorrect behaviour: Usage of a global before it was defined

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#86]
## What
Compilers (vanilla and NG) behave differently when using __globals__ before they got defined in the code.
So vanilla fails compilation with an error when the global was not defined. Exception is when it is some kind of deferred call (eg. a function definition __after__ the global).
NG instead compiles fine and allows accessing globals before they even got defined.

__But:__ it only works for single dimension variables. As soon as you have a global array things get different. NG compilates segfault when accessing them and vanilla blames access beyond array length during compilation.

## Example Codes 

The following code does not compile with vanilla but with NG
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Print Test
Global Test:String = "A"
```
Vanilla output: ``Compile Error: Identifier 'Test' not found``
NG output: ``A``

When using a function call it works as long as the global is defined BEFORE the function definition:

Failing with vanilla. Working with NG:
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Print TestFunc()

Function TestFunc:String()
	Return test
End Function

Global Test:String = "A"
```

Working in vanilla. Working with NG:
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Print TestFunc()

Global Test:String = "A"

Function TestFunc:String()
	Return test
End Function
```

__Now to the important thing__
It seems it only works for NG when it is a single dimension type.

Accessing a global array leads to a segfault:
(when calling the TestArrayFunc(), but would segfault by a direct global access too)
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Print TestArrayFunc()
Print TestArray[1]
Global TestArray:String[] = ["a", "b", "c"]

Function TestArrayFunc:String()
	Return TestArray[1]
End Function
```

In vanilla this code fails differently:
(removed direct access as that leads to ``Compile Error: Identifier 'TestArray' not found``)
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Print TestArrayFunc()
Global TestArray:String[] = ["a", "b", "c"]

Function TestArrayFunc:String()
	Return TestArray[1]
End Function
```
result in vanilla: ``Unhandled Exception:Attempt to index array element beyond array length``

## Conclusion
Inconsequent behaviour, either do not allow all variants before global is defined, or allow all.

Of course even vanilla behaves differently depending on the global type (single dimension or array)

**Comment by GWRon** [comment]
I prefer the "NG" style, but I do not know if this has unwanted side effects.

**Comment by woollybah** [comment]
There is no array bounds checking in Release mode, so I assume you ran the vanilla test in debug?
I can't remember if there is any array bounds checking in NG?

**Comment by woollybah** [comment]
So (one of) the bug(s) is that in debug mode there is no bounds checking?

**Comment by woollybah** [comment]
Okay, so I've added some array index bounds checking and initialising global variables to a default null value (I thought I had already, but apparently not). That now results in the same exception in debug that you have in vanilla.

**Comment by GWRon** [comment]
Yes...you are right. Vanilla was a debug build while NG was release.

NG segfaulted in both variants but you are right about the boundary checks.
Will correct/check it when on my computer again

**Comment by GWRon** [comment]
I do not know if the behaviour of vanilla is correct at all.

In my opinion globals only exist if they are defined via `global bla:int`. if you leave out an initial value the default value is used (null, 0, ""). Every defaultvalue of a global could only be either another global or const ... so the compiler should know the value to use.

As a"global" by definition is accessible from everywhere I assume you are able to (initially) define it everywhere in the file/scope.

Of course this is not backwards compatible with vanilla. But imho still a "bug" in vanilla.

**Comment by GWRon** [comment]
@Debug: Without debug the code "correctly" just segfaults in vanilla, so you were right.
