### ISSUE TITLE
Method overriding doesn't take return type into account

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#94]
An overridden method with a different (compatible) return type has incorrect code generated because it is using the original definition of the method, instead of creating a new one for this sub-class.

```blitzmax
SuperStrict

Framework brl.standardio

Local sub:TSub = New TSub

Print sub.getOther().two


Type TBase

	Method getOther:TOtherBase()
		Return New TOtherBase
	End Method
	
End Type

Type TSub Extends TBAse

	Method getOther:TOther()
		Return New TOther
	End Method
	
End Type

Type TOtherBase

	Field one:Int = 1

End Type

Type TOther Extends TOtherBase

	Field two:Int = 2

End Type
```

**Comment by GWRon** [comment]
I assume you tried some of my code ... I use this very often (overriding "Init:Type" methods in extending types).

Is there a reason why this only works for "return" values not params?

**Comment by woollybah** [comment]
Because BlitzMax doesn't support method overloading?

**Comment by GWRon** [comment]
I did not talk about replacing variable types in general but replacing them with extending types. isnt this similar to the return type?

**Comment by woollybah** [comment]
Dunno. Does it work with legacy?

**Comment by GWRon** [comment]
Of course not... that is why i asked what reasons exist to allow it for return typws...but not params. Just pure interest...nothing more.

**Comment by woollybah** [comment]
I think it's an overloading thing. I also tested this issue on Java, and it works in the same way.
When we get overload support in ng, your problem will go away ;-)
