### ISSUE TITLE
Syntax error - expecting identifier: Throw New "bla"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#97]
In TPersistence.mod the following line is used without trouble in vanilla: `Throw New "Reference not mapped yet : " + ref`.

In NG it creates an error: `Syntax error - expecting identifier`.

(I understand that the "New" isn't needed at all there, but for compatibility issues this might need to get fixed).

**Comment by woollybah** [comment]
Hmm... I'd say you shouldn't be allowed to use "New" there.

**Comment by GWRon** [comment]
I know that removing the "New" will make the error go away... but as vanilla is compiling fine I am not sure if NG should support that as well (was the first occourence of such a construction).

**Comment by woollybah** [comment]
This core dumps for me on legacy Linux -
```blitzmax
SuperStrict

Framework brl.standardio

Print New "Hello World"
```

**Comment by woollybah** [comment]
As I believe, it's probably a bug in legacy bcc.

**Comment by GWRon** [comment]
Hmm You are right ... it segfaults, but compiles... So I guess we found a bug:

```BlitzMax
SuperStrict

Framework brl.standardio

local s:String = New "Hello World"
print s
```
segfaults too... so "New string" is not catched properly in vanilla.
