### ISSUE TITLE
Calling inbuilts functions with return type ( chr:string(1) ) fails

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#98]
NG fails to compile 
```BlitzMax
SuperStrict
Framework brl.standardio

Function GetInt:int()
	return 1
End Function

'works
GetInt:Int()
'fails
chr:string(1)
```

Same for "asc" and other inbuilt functions. Assume they are not correctly recognized as functions.

Edit:
parser.bmx: `Method ParsePrimaryExpr:TExpr( stmt:Int )` just checks eg. for "chr" and "(" as next char - should also check for the expected return type.

Attention to things like "Min/Max" - dunno if they return the LCD of the given types or the "most detailed" one (min(int,float) = float). In that case the ":return type" might be relevant?

**Comment by GWRon** [comment]
These are actually two issues.

When fixing ":string" with:

```BlitzMax
		Case "chr"
			NextToke

			' optional brackets
			If CParse( "(" )
				expr=ParseExpr()
				print expr.ToString()
				Parse ")"
				expr=New TChrExpr.Create( expr )
			Else
				expr=ParseExpr()
				expr=New TChrExpr.Create( expr )
			EndIf
```

To 

```BlitzMax
		Case "chr"
			NextToke

			'optional return type - needing "string"
			If CParse( ":" ) Then Parse( "string" )
			
			' optional brackets
			If CParse( "(" )
				expr=ParseExpr()
				print expr.ToString()
				Parse ")"
				expr=New TChrExpr.Create( expr )
			Else
				expr=ParseExpr()
				expr=New TChrExpr.Create( expr )
			EndIf
```

you now could `print chr:string(1)` but when calling `chr:string(1)` like in the given example, you get another error: `Compile Error: Expression cannot be used as a statement.`  - as this also happens for `chr(1)` (without return type) I will create another issue for this.

**Comment by GWRon** [comment]
Interestingly this does __not__ work for Min() and Max() - so Min/Max do not allow an appended return type (why? - because it does not know the resulting type?).

Will provide a patch for this issue

**Comment by woollybah** [comment]
I'll sort it out, thanks.

**Comment by GWRon** [comment]
Interestingly some functions output specific errors in vanilla:

SizeOf:String(i) -> Compile Error: Return type for 'SizeOf' must be Int
Len:String(i) -> Compile Error: Return type for 'Len' must be Int
Asc:int(s|i) -> Compile Error: Return type for 'Asc' must be Int
Chr:string(i) -> Compile Error: Return type for 'Chr' must be String

Inbuilt not allowing ":type":
Abs: -> Compile Error: Expecting expression but encountered ':'
Min: -> Compile Error: Expecting expression but encountered ':'
Sgn: -> Compile Error: Expecting expression but encountered ':'
Max: -> Compile Error: Expecting expression but encountered ':'
(like said: all of them return varying types depending on the param)

Pi: -> Compile Error: Expecting expression but encountered ':'


Hope that helps a bit - because you do not want me to fix it (and you then later on replace it with a more proper solution)
