### ISSUE TITLE
Calling inbuilt function without doing something (single line: Chr(1) )

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#99]
```BlitzMax
SuperStrict

Framework brl.standardio

Function GetInt:Int()
	Return 1
End Function

'works
GetInt()
'fails
Chr(1)
```

Fails at `Chr(1)` with `Compile Error: Expression cannot be used as a statement.`

**Comment by woollybah** [comment]
What error do you expect instead?
```Expression of type 'String' cannot be invoked``` ?

**Comment by GWRon** [comment]
I "expect" no error at all.

It compiles and executes fine with vanilla.
It errors out with NG.

As a normal function call `GetInt()` is working fine, it is something with the inbuilt commands which is handled differently.

**Comment by woollybah** [comment]
Doesn't work for me on legacy. It reports the above mentioned error.

**Comment by GWRon** [comment]
Hmmpf... you are right, it fails there too (must have compiled the wrong thing...excusé-moi).

Ok, so we keep it "compatible" ... albeit it is some kind of "bug" then in vanilla... or a feature (as you cannot override these inbuilt-functions and therefore it is guaranteed, that no other things happen in these functions - like printing or changing other things).

You might close it as invalid if you want.
